// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: service/trips.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Place, Trip, TripDay, TripTransport, TripTraveler } from "../itinerary";

export const protobufPackage = "travelingman.service";

export interface CreateTripRequest {
  groupId: number;
  name: string;
  destination: string;
  /** RFC3339 or YYYY-MM-DD */
  startDate: string;
  endDate: string;
}

export interface GetTripRequest {
  tripId: number;
}

export interface GetTripResponse {
  trip: Trip | undefined;
  days: TripDay[];
}

export interface AddPlaceRequest {
  tripDayId: number;
  name: string;
  address: string;
  placeType: string;
  latitude: number;
  longitude: number;
  notes: string;
  /** RFC3339 */
  visitTime: string;
}

export interface UpdatePlaceRequest {
  placeId: number;
  name: string;
  address: string;
  notes: string;
  visitTime: string;
}

export interface DeletePlaceRequest {
  placeId: number;
}

export interface GetPlacesRequest {
  tripDayId: number;
}

export interface GetPlacesResponse {
  places: Place[];
}

export interface AddTripTravelerRequest {
  tripId: number;
  userId: number;
  color: string;
}

export interface GetTripTravelersRequest {
  tripId: number;
}

export interface GetTripTravelersResponse {
  travelers: TripTraveler[];
}

export interface AddTripTransportRequest {
  tripId: number;
  fromLocation: string;
  toLocation: string;
  transportMode: string;
  departureTime: string;
  arrivalTime: string;
  detailsJson: string;
  travelerIds: number[];
}

export interface GetTripTransportsRequest {
  tripId: number;
}

export interface GetTripTransportsResponse {
  transports: TripTransport[];
}

export interface GetTripFlowRequest {
  tripId: number;
}

export interface GetTripFlowResponse {
  trip: Trip | undefined;
  travelers: TripTraveler[];
  days: TripDay[];
  transports: TripTransport[];
}

function createBaseCreateTripRequest(): CreateTripRequest {
  return { groupId: 0, name: "", destination: "", startDate: "", endDate: "" };
}

export const CreateTripRequest: MessageFns<CreateTripRequest> = {
  encode(message: CreateTripRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.groupId !== 0) {
      writer.uint32(8).int64(message.groupId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.destination !== "") {
      writer.uint32(26).string(message.destination);
    }
    if (message.startDate !== "") {
      writer.uint32(34).string(message.startDate);
    }
    if (message.endDate !== "") {
      writer.uint32(42).string(message.endDate);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTripRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTripRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.destination = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startDate = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.endDate = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTripRequest {
    return {
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      destination: isSet(object.destination) ? globalThis.String(object.destination) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : "",
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : "",
    };
  },

  toJSON(message: CreateTripRequest): unknown {
    const obj: any = {};
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.destination !== "") {
      obj.destination = message.destination;
    }
    if (message.startDate !== "") {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== "") {
      obj.endDate = message.endDate;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTripRequest>, I>>(base?: I): CreateTripRequest {
    return CreateTripRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTripRequest>, I>>(object: I): CreateTripRequest {
    const message = createBaseCreateTripRequest();
    message.groupId = object.groupId ?? 0;
    message.name = object.name ?? "";
    message.destination = object.destination ?? "";
    message.startDate = object.startDate ?? "";
    message.endDate = object.endDate ?? "";
    return message;
  },
};

function createBaseGetTripRequest(): GetTripRequest {
  return { tripId: 0 };
}

export const GetTripRequest: MessageFns<GetTripRequest> = {
  encode(message: GetTripRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripRequest {
    return { tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0 };
  },

  toJSON(message: GetTripRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripRequest>, I>>(base?: I): GetTripRequest {
    return GetTripRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripRequest>, I>>(object: I): GetTripRequest {
    const message = createBaseGetTripRequest();
    message.tripId = object.tripId ?? 0;
    return message;
  },
};

function createBaseGetTripResponse(): GetTripResponse {
  return { trip: undefined, days: [] };
}

export const GetTripResponse: MessageFns<GetTripResponse> = {
  encode(message: GetTripResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trip !== undefined) {
      Trip.encode(message.trip, writer.uint32(10).fork()).join();
    }
    for (const v of message.days) {
      TripDay.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trip = Trip.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.days.push(TripDay.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripResponse {
    return {
      trip: isSet(object.trip) ? Trip.fromJSON(object.trip) : undefined,
      days: globalThis.Array.isArray(object?.days) ? object.days.map((e: any) => TripDay.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetTripResponse): unknown {
    const obj: any = {};
    if (message.trip !== undefined) {
      obj.trip = Trip.toJSON(message.trip);
    }
    if (message.days?.length) {
      obj.days = message.days.map((e) => TripDay.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripResponse>, I>>(base?: I): GetTripResponse {
    return GetTripResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripResponse>, I>>(object: I): GetTripResponse {
    const message = createBaseGetTripResponse();
    message.trip = (object.trip !== undefined && object.trip !== null) ? Trip.fromPartial(object.trip) : undefined;
    message.days = object.days?.map((e) => TripDay.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddPlaceRequest(): AddPlaceRequest {
  return { tripDayId: 0, name: "", address: "", placeType: "", latitude: 0, longitude: 0, notes: "", visitTime: "" };
}

export const AddPlaceRequest: MessageFns<AddPlaceRequest> = {
  encode(message: AddPlaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripDayId !== 0) {
      writer.uint32(8).int64(message.tripDayId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.placeType !== "") {
      writer.uint32(34).string(message.placeType);
    }
    if (message.latitude !== 0) {
      writer.uint32(41).double(message.latitude);
    }
    if (message.longitude !== 0) {
      writer.uint32(49).double(message.longitude);
    }
    if (message.notes !== "") {
      writer.uint32(58).string(message.notes);
    }
    if (message.visitTime !== "") {
      writer.uint32(66).string(message.visitTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddPlaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddPlaceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripDayId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.placeType = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 41) {
            break;
          }

          message.latitude = reader.double();
          continue;
        }
        case 6: {
          if (tag !== 49) {
            break;
          }

          message.longitude = reader.double();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.visitTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddPlaceRequest {
    return {
      tripDayId: isSet(object.tripDayId) ? globalThis.Number(object.tripDayId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      placeType: isSet(object.placeType) ? globalThis.String(object.placeType) : "",
      latitude: isSet(object.latitude) ? globalThis.Number(object.latitude) : 0,
      longitude: isSet(object.longitude) ? globalThis.Number(object.longitude) : 0,
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
      visitTime: isSet(object.visitTime) ? globalThis.String(object.visitTime) : "",
    };
  },

  toJSON(message: AddPlaceRequest): unknown {
    const obj: any = {};
    if (message.tripDayId !== 0) {
      obj.tripDayId = Math.round(message.tripDayId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.placeType !== "") {
      obj.placeType = message.placeType;
    }
    if (message.latitude !== 0) {
      obj.latitude = message.latitude;
    }
    if (message.longitude !== 0) {
      obj.longitude = message.longitude;
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    if (message.visitTime !== "") {
      obj.visitTime = message.visitTime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddPlaceRequest>, I>>(base?: I): AddPlaceRequest {
    return AddPlaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddPlaceRequest>, I>>(object: I): AddPlaceRequest {
    const message = createBaseAddPlaceRequest();
    message.tripDayId = object.tripDayId ?? 0;
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.placeType = object.placeType ?? "";
    message.latitude = object.latitude ?? 0;
    message.longitude = object.longitude ?? 0;
    message.notes = object.notes ?? "";
    message.visitTime = object.visitTime ?? "";
    return message;
  },
};

function createBaseUpdatePlaceRequest(): UpdatePlaceRequest {
  return { placeId: 0, name: "", address: "", notes: "", visitTime: "" };
}

export const UpdatePlaceRequest: MessageFns<UpdatePlaceRequest> = {
  encode(message: UpdatePlaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.placeId !== 0) {
      writer.uint32(8).int64(message.placeId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(26).string(message.address);
    }
    if (message.notes !== "") {
      writer.uint32(34).string(message.notes);
    }
    if (message.visitTime !== "") {
      writer.uint32(42).string(message.visitTime);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdatePlaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdatePlaceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.placeId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.notes = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.visitTime = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdatePlaceRequest {
    return {
      placeId: isSet(object.placeId) ? globalThis.Number(object.placeId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      notes: isSet(object.notes) ? globalThis.String(object.notes) : "",
      visitTime: isSet(object.visitTime) ? globalThis.String(object.visitTime) : "",
    };
  },

  toJSON(message: UpdatePlaceRequest): unknown {
    const obj: any = {};
    if (message.placeId !== 0) {
      obj.placeId = Math.round(message.placeId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.notes !== "") {
      obj.notes = message.notes;
    }
    if (message.visitTime !== "") {
      obj.visitTime = message.visitTime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdatePlaceRequest>, I>>(base?: I): UpdatePlaceRequest {
    return UpdatePlaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdatePlaceRequest>, I>>(object: I): UpdatePlaceRequest {
    const message = createBaseUpdatePlaceRequest();
    message.placeId = object.placeId ?? 0;
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.notes = object.notes ?? "";
    message.visitTime = object.visitTime ?? "";
    return message;
  },
};

function createBaseDeletePlaceRequest(): DeletePlaceRequest {
  return { placeId: 0 };
}

export const DeletePlaceRequest: MessageFns<DeletePlaceRequest> = {
  encode(message: DeletePlaceRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.placeId !== 0) {
      writer.uint32(8).int64(message.placeId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DeletePlaceRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDeletePlaceRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.placeId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DeletePlaceRequest {
    return { placeId: isSet(object.placeId) ? globalThis.Number(object.placeId) : 0 };
  },

  toJSON(message: DeletePlaceRequest): unknown {
    const obj: any = {};
    if (message.placeId !== 0) {
      obj.placeId = Math.round(message.placeId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DeletePlaceRequest>, I>>(base?: I): DeletePlaceRequest {
    return DeletePlaceRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DeletePlaceRequest>, I>>(object: I): DeletePlaceRequest {
    const message = createBaseDeletePlaceRequest();
    message.placeId = object.placeId ?? 0;
    return message;
  },
};

function createBaseGetPlacesRequest(): GetPlacesRequest {
  return { tripDayId: 0 };
}

export const GetPlacesRequest: MessageFns<GetPlacesRequest> = {
  encode(message: GetPlacesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripDayId !== 0) {
      writer.uint32(8).int64(message.tripDayId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPlacesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPlacesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripDayId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPlacesRequest {
    return { tripDayId: isSet(object.tripDayId) ? globalThis.Number(object.tripDayId) : 0 };
  },

  toJSON(message: GetPlacesRequest): unknown {
    const obj: any = {};
    if (message.tripDayId !== 0) {
      obj.tripDayId = Math.round(message.tripDayId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPlacesRequest>, I>>(base?: I): GetPlacesRequest {
    return GetPlacesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPlacesRequest>, I>>(object: I): GetPlacesRequest {
    const message = createBaseGetPlacesRequest();
    message.tripDayId = object.tripDayId ?? 0;
    return message;
  },
};

function createBaseGetPlacesResponse(): GetPlacesResponse {
  return { places: [] };
}

export const GetPlacesResponse: MessageFns<GetPlacesResponse> = {
  encode(message: GetPlacesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.places) {
      Place.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetPlacesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetPlacesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.places.push(Place.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetPlacesResponse {
    return { places: globalThis.Array.isArray(object?.places) ? object.places.map((e: any) => Place.fromJSON(e)) : [] };
  },

  toJSON(message: GetPlacesResponse): unknown {
    const obj: any = {};
    if (message.places?.length) {
      obj.places = message.places.map((e) => Place.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetPlacesResponse>, I>>(base?: I): GetPlacesResponse {
    return GetPlacesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetPlacesResponse>, I>>(object: I): GetPlacesResponse {
    const message = createBaseGetPlacesResponse();
    message.places = object.places?.map((e) => Place.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddTripTravelerRequest(): AddTripTravelerRequest {
  return { tripId: 0, userId: 0, color: "" };
}

export const AddTripTravelerRequest: MessageFns<AddTripTravelerRequest> = {
  encode(message: AddTripTravelerRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int64(message.userId);
    }
    if (message.color !== "") {
      writer.uint32(26).string(message.color);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddTripTravelerRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddTripTravelerRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.color = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddTripTravelerRequest {
    return {
      tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      color: isSet(object.color) ? globalThis.String(object.color) : "",
    };
  },

  toJSON(message: AddTripTravelerRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.color !== "") {
      obj.color = message.color;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddTripTravelerRequest>, I>>(base?: I): AddTripTravelerRequest {
    return AddTripTravelerRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddTripTravelerRequest>, I>>(object: I): AddTripTravelerRequest {
    const message = createBaseAddTripTravelerRequest();
    message.tripId = object.tripId ?? 0;
    message.userId = object.userId ?? 0;
    message.color = object.color ?? "";
    return message;
  },
};

function createBaseGetTripTravelersRequest(): GetTripTravelersRequest {
  return { tripId: 0 };
}

export const GetTripTravelersRequest: MessageFns<GetTripTravelersRequest> = {
  encode(message: GetTripTravelersRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripTravelersRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripTravelersRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripTravelersRequest {
    return { tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0 };
  },

  toJSON(message: GetTripTravelersRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripTravelersRequest>, I>>(base?: I): GetTripTravelersRequest {
    return GetTripTravelersRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripTravelersRequest>, I>>(object: I): GetTripTravelersRequest {
    const message = createBaseGetTripTravelersRequest();
    message.tripId = object.tripId ?? 0;
    return message;
  },
};

function createBaseGetTripTravelersResponse(): GetTripTravelersResponse {
  return { travelers: [] };
}

export const GetTripTravelersResponse: MessageFns<GetTripTravelersResponse> = {
  encode(message: GetTripTravelersResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.travelers) {
      TripTraveler.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripTravelersResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripTravelersResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.travelers.push(TripTraveler.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripTravelersResponse {
    return {
      travelers: globalThis.Array.isArray(object?.travelers)
        ? object.travelers.map((e: any) => TripTraveler.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetTripTravelersResponse): unknown {
    const obj: any = {};
    if (message.travelers?.length) {
      obj.travelers = message.travelers.map((e) => TripTraveler.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripTravelersResponse>, I>>(base?: I): GetTripTravelersResponse {
    return GetTripTravelersResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripTravelersResponse>, I>>(object: I): GetTripTravelersResponse {
    const message = createBaseGetTripTravelersResponse();
    message.travelers = object.travelers?.map((e) => TripTraveler.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddTripTransportRequest(): AddTripTransportRequest {
  return {
    tripId: 0,
    fromLocation: "",
    toLocation: "",
    transportMode: "",
    departureTime: "",
    arrivalTime: "",
    detailsJson: "",
    travelerIds: [],
  };
}

export const AddTripTransportRequest: MessageFns<AddTripTransportRequest> = {
  encode(message: AddTripTransportRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    if (message.fromLocation !== "") {
      writer.uint32(18).string(message.fromLocation);
    }
    if (message.toLocation !== "") {
      writer.uint32(26).string(message.toLocation);
    }
    if (message.transportMode !== "") {
      writer.uint32(34).string(message.transportMode);
    }
    if (message.departureTime !== "") {
      writer.uint32(42).string(message.departureTime);
    }
    if (message.arrivalTime !== "") {
      writer.uint32(50).string(message.arrivalTime);
    }
    if (message.detailsJson !== "") {
      writer.uint32(58).string(message.detailsJson);
    }
    writer.uint32(66).fork();
    for (const v of message.travelerIds) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddTripTransportRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddTripTransportRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.fromLocation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.toLocation = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transportMode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.departureTime = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.arrivalTime = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.detailsJson = reader.string();
          continue;
        }
        case 8: {
          if (tag === 64) {
            message.travelerIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.travelerIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddTripTransportRequest {
    return {
      tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0,
      fromLocation: isSet(object.fromLocation) ? globalThis.String(object.fromLocation) : "",
      toLocation: isSet(object.toLocation) ? globalThis.String(object.toLocation) : "",
      transportMode: isSet(object.transportMode) ? globalThis.String(object.transportMode) : "",
      departureTime: isSet(object.departureTime) ? globalThis.String(object.departureTime) : "",
      arrivalTime: isSet(object.arrivalTime) ? globalThis.String(object.arrivalTime) : "",
      detailsJson: isSet(object.detailsJson) ? globalThis.String(object.detailsJson) : "",
      travelerIds: globalThis.Array.isArray(object?.travelerIds)
        ? object.travelerIds.map((e: any) => globalThis.Number(e))
        : [],
    };
  },

  toJSON(message: AddTripTransportRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    if (message.fromLocation !== "") {
      obj.fromLocation = message.fromLocation;
    }
    if (message.toLocation !== "") {
      obj.toLocation = message.toLocation;
    }
    if (message.transportMode !== "") {
      obj.transportMode = message.transportMode;
    }
    if (message.departureTime !== "") {
      obj.departureTime = message.departureTime;
    }
    if (message.arrivalTime !== "") {
      obj.arrivalTime = message.arrivalTime;
    }
    if (message.detailsJson !== "") {
      obj.detailsJson = message.detailsJson;
    }
    if (message.travelerIds?.length) {
      obj.travelerIds = message.travelerIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddTripTransportRequest>, I>>(base?: I): AddTripTransportRequest {
    return AddTripTransportRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddTripTransportRequest>, I>>(object: I): AddTripTransportRequest {
    const message = createBaseAddTripTransportRequest();
    message.tripId = object.tripId ?? 0;
    message.fromLocation = object.fromLocation ?? "";
    message.toLocation = object.toLocation ?? "";
    message.transportMode = object.transportMode ?? "";
    message.departureTime = object.departureTime ?? "";
    message.arrivalTime = object.arrivalTime ?? "";
    message.detailsJson = object.detailsJson ?? "";
    message.travelerIds = object.travelerIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetTripTransportsRequest(): GetTripTransportsRequest {
  return { tripId: 0 };
}

export const GetTripTransportsRequest: MessageFns<GetTripTransportsRequest> = {
  encode(message: GetTripTransportsRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripTransportsRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripTransportsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripTransportsRequest {
    return { tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0 };
  },

  toJSON(message: GetTripTransportsRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripTransportsRequest>, I>>(base?: I): GetTripTransportsRequest {
    return GetTripTransportsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripTransportsRequest>, I>>(object: I): GetTripTransportsRequest {
    const message = createBaseGetTripTransportsRequest();
    message.tripId = object.tripId ?? 0;
    return message;
  },
};

function createBaseGetTripTransportsResponse(): GetTripTransportsResponse {
  return { transports: [] };
}

export const GetTripTransportsResponse: MessageFns<GetTripTransportsResponse> = {
  encode(message: GetTripTransportsResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.transports) {
      TripTransport.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripTransportsResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripTransportsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.transports.push(TripTransport.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripTransportsResponse {
    return {
      transports: globalThis.Array.isArray(object?.transports)
        ? object.transports.map((e: any) => TripTransport.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetTripTransportsResponse): unknown {
    const obj: any = {};
    if (message.transports?.length) {
      obj.transports = message.transports.map((e) => TripTransport.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripTransportsResponse>, I>>(base?: I): GetTripTransportsResponse {
    return GetTripTransportsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripTransportsResponse>, I>>(object: I): GetTripTransportsResponse {
    const message = createBaseGetTripTransportsResponse();
    message.transports = object.transports?.map((e) => TripTransport.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetTripFlowRequest(): GetTripFlowRequest {
  return { tripId: 0 };
}

export const GetTripFlowRequest: MessageFns<GetTripFlowRequest> = {
  encode(message: GetTripFlowRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.tripId !== 0) {
      writer.uint32(8).int64(message.tripId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripFlowRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripFlowRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.tripId = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripFlowRequest {
    return { tripId: isSet(object.tripId) ? globalThis.Number(object.tripId) : 0 };
  },

  toJSON(message: GetTripFlowRequest): unknown {
    const obj: any = {};
    if (message.tripId !== 0) {
      obj.tripId = Math.round(message.tripId);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripFlowRequest>, I>>(base?: I): GetTripFlowRequest {
    return GetTripFlowRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripFlowRequest>, I>>(object: I): GetTripFlowRequest {
    const message = createBaseGetTripFlowRequest();
    message.tripId = object.tripId ?? 0;
    return message;
  },
};

function createBaseGetTripFlowResponse(): GetTripFlowResponse {
  return { trip: undefined, travelers: [], days: [], transports: [] };
}

export const GetTripFlowResponse: MessageFns<GetTripFlowResponse> = {
  encode(message: GetTripFlowResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.trip !== undefined) {
      Trip.encode(message.trip, writer.uint32(10).fork()).join();
    }
    for (const v of message.travelers) {
      TripTraveler.encode(v!, writer.uint32(18).fork()).join();
    }
    for (const v of message.days) {
      TripDay.encode(v!, writer.uint32(26).fork()).join();
    }
    for (const v of message.transports) {
      TripTransport.encode(v!, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTripFlowResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTripFlowResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.trip = Trip.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.travelers.push(TripTraveler.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.days.push(TripDay.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transports.push(TripTransport.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTripFlowResponse {
    return {
      trip: isSet(object.trip) ? Trip.fromJSON(object.trip) : undefined,
      travelers: globalThis.Array.isArray(object?.travelers)
        ? object.travelers.map((e: any) => TripTraveler.fromJSON(e))
        : [],
      days: globalThis.Array.isArray(object?.days) ? object.days.map((e: any) => TripDay.fromJSON(e)) : [],
      transports: globalThis.Array.isArray(object?.transports)
        ? object.transports.map((e: any) => TripTransport.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetTripFlowResponse): unknown {
    const obj: any = {};
    if (message.trip !== undefined) {
      obj.trip = Trip.toJSON(message.trip);
    }
    if (message.travelers?.length) {
      obj.travelers = message.travelers.map((e) => TripTraveler.toJSON(e));
    }
    if (message.days?.length) {
      obj.days = message.days.map((e) => TripDay.toJSON(e));
    }
    if (message.transports?.length) {
      obj.transports = message.transports.map((e) => TripTransport.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTripFlowResponse>, I>>(base?: I): GetTripFlowResponse {
    return GetTripFlowResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTripFlowResponse>, I>>(object: I): GetTripFlowResponse {
    const message = createBaseGetTripFlowResponse();
    message.trip = (object.trip !== undefined && object.trip !== null) ? Trip.fromPartial(object.trip) : undefined;
    message.travelers = object.travelers?.map((e) => TripTraveler.fromPartial(e)) || [];
    message.days = object.days?.map((e) => TripDay.fromPartial(e)) || [];
    message.transports = object.transports?.map((e) => TripTransport.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
