// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: protos/service.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	pb "github.com/va6996/travelingman/pb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TravelServiceName is the fully-qualified name of the TravelService service.
	TravelServiceName = "travelingman.TravelService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TravelServicePlanTripProcedure is the fully-qualified name of the TravelService's PlanTrip RPC.
	TravelServicePlanTripProcedure = "/travelingman.TravelService/PlanTrip"
)

// TravelServiceClient is a client for the travelingman.TravelService service.
type TravelServiceClient interface {
	PlanTrip(context.Context, *connect.Request[pb.PlanTripRequest]) (*connect.Response[pb.PlanTripResponse], error)
}

// NewTravelServiceClient constructs a client for the travelingman.TravelService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTravelServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TravelServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	travelServiceMethods := pb.File_protos_service_proto.Services().ByName("TravelService").Methods()
	return &travelServiceClient{
		planTrip: connect.NewClient[pb.PlanTripRequest, pb.PlanTripResponse](
			httpClient,
			baseURL+TravelServicePlanTripProcedure,
			connect.WithSchema(travelServiceMethods.ByName("PlanTrip")),
			connect.WithClientOptions(opts...),
		),
	}
}

// travelServiceClient implements TravelServiceClient.
type travelServiceClient struct {
	planTrip *connect.Client[pb.PlanTripRequest, pb.PlanTripResponse]
}

// PlanTrip calls travelingman.TravelService.PlanTrip.
func (c *travelServiceClient) PlanTrip(ctx context.Context, req *connect.Request[pb.PlanTripRequest]) (*connect.Response[pb.PlanTripResponse], error) {
	return c.planTrip.CallUnary(ctx, req)
}

// TravelServiceHandler is an implementation of the travelingman.TravelService service.
type TravelServiceHandler interface {
	PlanTrip(context.Context, *connect.Request[pb.PlanTripRequest]) (*connect.Response[pb.PlanTripResponse], error)
}

// NewTravelServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTravelServiceHandler(svc TravelServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	travelServiceMethods := pb.File_protos_service_proto.Services().ByName("TravelService").Methods()
	travelServicePlanTripHandler := connect.NewUnaryHandler(
		TravelServicePlanTripProcedure,
		svc.PlanTrip,
		connect.WithSchema(travelServiceMethods.ByName("PlanTrip")),
		connect.WithHandlerOptions(opts...),
	)
	return "/travelingman.TravelService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TravelServicePlanTripProcedure:
			travelServicePlanTripHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTravelServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTravelServiceHandler struct{}

func (UnimplementedTravelServiceHandler) PlanTrip(context.Context, *connect.Request[pb.PlanTripRequest]) (*connect.Response[pb.PlanTripResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("travelingman.TravelService.PlanTrip is not implemented"))
}
