// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: service/bookings.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookFlightRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FlightOfferJson  []byte                 `protobuf:"bytes,1,opt,name=flight_offer_json,json=flightOfferJson,proto3" json:"flight_offer_json,omitempty"` // JSON representation of the elected FlightOffer
	TravelersJson    []byte                 `protobuf:"bytes,2,opt,name=travelers_json,json=travelersJson,proto3" json:"travelers_json,omitempty"`         // JSON list of TravelerInfo
	UserId           int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BookingReference string                 `protobuf:"bytes,4,opt,name=booking_reference,json=bookingReference,proto3" json:"booking_reference,omitempty"` // Optional: For actual booking
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BookFlightRequest) Reset() {
	*x = BookFlightRequest{}
	mi := &file_service_bookings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookFlightRequest) ProtoMessage() {}

func (x *BookFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookFlightRequest.ProtoReflect.Descriptor instead.
func (*BookFlightRequest) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{0}
}

func (x *BookFlightRequest) GetFlightOfferJson() []byte {
	if x != nil {
		return x.FlightOfferJson
	}
	return nil
}

func (x *BookFlightRequest) GetTravelersJson() []byte {
	if x != nil {
		return x.TravelersJson
	}
	return nil
}

func (x *BookFlightRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BookFlightRequest) GetBookingReference() string {
	if x != nil {
		return x.BookingReference
	}
	return ""
}

type BookFlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"` // JSON response from Amadeus (booking confirmation)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookFlightResponse) Reset() {
	*x = BookFlightResponse{}
	mi := &file_service_bookings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookFlightResponse) ProtoMessage() {}

func (x *BookFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookFlightResponse.ProtoReflect.Descriptor instead.
func (*BookFlightResponse) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{1}
}

func (x *BookFlightResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type BookHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	GuestsJson    []byte                 `protobuf:"bytes,2,opt,name=guests_json,json=guestsJson,proto3" json:"guests_json,omitempty"`    // JSON list of HotelGuest
	PaymentJson   []byte                 `protobuf:"bytes,3,opt,name=payment_json,json=paymentJson,proto3" json:"payment_json,omitempty"` // JSON of HotelPayment
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookHotelRequest) Reset() {
	*x = BookHotelRequest{}
	mi := &file_service_bookings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookHotelRequest) ProtoMessage() {}

func (x *BookHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookHotelRequest.ProtoReflect.Descriptor instead.
func (*BookHotelRequest) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{2}
}

func (x *BookHotelRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *BookHotelRequest) GetGuestsJson() []byte {
	if x != nil {
		return x.GuestsJson
	}
	return nil
}

func (x *BookHotelRequest) GetPaymentJson() []byte {
	if x != nil {
		return x.PaymentJson
	}
	return nil
}

func (x *BookHotelRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BookHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookHotelResponse) Reset() {
	*x = BookHotelResponse{}
	mi := &file_service_bookings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookHotelResponse) ProtoMessage() {}

func (x *BookHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookHotelResponse.ProtoReflect.Descriptor instead.
func (*BookHotelResponse) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{3}
}

func (x *BookHotelResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type BookTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OfferId       string                 `protobuf:"bytes,1,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	TravelersJson []byte                 `protobuf:"bytes,2,opt,name=travelers_json,json=travelersJson,proto3" json:"travelers_json,omitempty"` // JSON list of TransferTraveler
	PaymentJson   []byte                 `protobuf:"bytes,3,opt,name=payment_json,json=paymentJson,proto3" json:"payment_json,omitempty"`       // JSON of TransferPayment
	UserId        int64                  `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTransferRequest) Reset() {
	*x = BookTransferRequest{}
	mi := &file_service_bookings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTransferRequest) ProtoMessage() {}

func (x *BookTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTransferRequest.ProtoReflect.Descriptor instead.
func (*BookTransferRequest) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{4}
}

func (x *BookTransferRequest) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

func (x *BookTransferRequest) GetTravelersJson() []byte {
	if x != nil {
		return x.TravelersJson
	}
	return nil
}

func (x *BookTransferRequest) GetPaymentJson() []byte {
	if x != nil {
		return x.PaymentJson
	}
	return nil
}

func (x *BookTransferRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BookTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookTransferResponse) Reset() {
	*x = BookTransferResponse{}
	mi := &file_service_bookings_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookTransferResponse) ProtoMessage() {}

func (x *BookTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_bookings_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookTransferResponse.ProtoReflect.Descriptor instead.
func (*BookTransferResponse) Descriptor() ([]byte, []int) {
	return file_service_bookings_proto_rawDescGZIP(), []int{5}
}

func (x *BookTransferResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

var File_service_bookings_proto protoreflect.FileDescriptor

const file_service_bookings_proto_rawDesc = "" +
	"\n" +
	"\x16service/bookings.proto\x12\x14travelingman.service\"\xac\x01\n" +
	"\x11BookFlightRequest\x12*\n" +
	"\x11flight_offer_json\x18\x01 \x01(\fR\x0fflightOfferJson\x12%\n" +
	"\x0etravelers_json\x18\x02 \x01(\fR\rtravelersJson\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12+\n" +
	"\x11booking_reference\x18\x04 \x01(\tR\x10bookingReference\"/\n" +
	"\x12BookFlightResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\x8a\x01\n" +
	"\x10BookHotelRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12\x1f\n" +
	"\vguests_json\x18\x02 \x01(\fR\n" +
	"guestsJson\x12!\n" +
	"\fpayment_json\x18\x03 \x01(\fR\vpaymentJson\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\".\n" +
	"\x11BookHotelResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\x93\x01\n" +
	"\x13BookTransferRequest\x12\x19\n" +
	"\boffer_id\x18\x01 \x01(\tR\aofferId\x12%\n" +
	"\x0etravelers_json\x18\x02 \x01(\fR\rtravelersJson\x12!\n" +
	"\fpayment_json\x18\x03 \x01(\fR\vpaymentJson\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x03R\x06userId\"1\n" +
	"\x14BookTransferResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJsonB%Z#example.com/travelingman/pb/serviceb\x06proto3"

var (
	file_service_bookings_proto_rawDescOnce sync.Once
	file_service_bookings_proto_rawDescData []byte
)

func file_service_bookings_proto_rawDescGZIP() []byte {
	file_service_bookings_proto_rawDescOnce.Do(func() {
		file_service_bookings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_bookings_proto_rawDesc), len(file_service_bookings_proto_rawDesc)))
	})
	return file_service_bookings_proto_rawDescData
}

var file_service_bookings_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_bookings_proto_goTypes = []any{
	(*BookFlightRequest)(nil),    // 0: travelingman.service.BookFlightRequest
	(*BookFlightResponse)(nil),   // 1: travelingman.service.BookFlightResponse
	(*BookHotelRequest)(nil),     // 2: travelingman.service.BookHotelRequest
	(*BookHotelResponse)(nil),    // 3: travelingman.service.BookHotelResponse
	(*BookTransferRequest)(nil),  // 4: travelingman.service.BookTransferRequest
	(*BookTransferResponse)(nil), // 5: travelingman.service.BookTransferResponse
}
var file_service_bookings_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_bookings_proto_init() }
func file_service_bookings_proto_init() {
	if File_service_bookings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_bookings_proto_rawDesc), len(file_service_bookings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_bookings_proto_goTypes,
		DependencyIndexes: file_service_bookings_proto_depIdxs,
		MessageInfos:      file_service_bookings_proto_msgTypes,
	}.Build()
	File_service_bookings_proto = out.File
	file_service_bookings_proto_goTypes = nil
	file_service_bookings_proto_depIdxs = nil
}
