// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: service/search.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchFlightRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Origin            string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination       string                 `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	DepartureDate     string                 `protobuf:"bytes,3,opt,name=departure_date,json=departureDate,proto3" json:"departure_date,omitempty"`
	ReturnDate        string                 `protobuf:"bytes,4,opt,name=return_date,json=returnDate,proto3" json:"return_date,omitempty"`
	Adults            int32                  `protobuf:"varint,5,opt,name=adults,proto3" json:"adults,omitempty"`
	TargetArrivalTime string                 `protobuf:"bytes,6,opt,name=target_arrival_time,json=targetArrivalTime,proto3" json:"target_arrival_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchFlightRequest) Reset() {
	*x = SearchFlightRequest{}
	mi := &file_service_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightRequest) ProtoMessage() {}

func (x *SearchFlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightRequest.ProtoReflect.Descriptor instead.
func (*SearchFlightRequest) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchFlightRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SearchFlightRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *SearchFlightRequest) GetDepartureDate() string {
	if x != nil {
		return x.DepartureDate
	}
	return ""
}

func (x *SearchFlightRequest) GetReturnDate() string {
	if x != nil {
		return x.ReturnDate
	}
	return ""
}

func (x *SearchFlightRequest) GetAdults() int32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

func (x *SearchFlightRequest) GetTargetArrivalTime() string {
	if x != nil {
		return x.TargetArrivalTime
	}
	return ""
}

type SearchFlightResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Returning raw JSON for now to allow frontend to parse full Amadeus schema
	// without rigid proto re-definition of every segment/fee/etc.
	RawJson       []byte `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFlightResponse) Reset() {
	*x = SearchFlightResponse{}
	mi := &file_service_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFlightResponse) ProtoMessage() {}

func (x *SearchFlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFlightResponse.ProtoReflect.Descriptor instead.
func (*SearchFlightResponse) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchFlightResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type SearchHotelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CityCode      string                 `protobuf:"bytes,1,opt,name=city_code,json=cityCode,proto3" json:"city_code,omitempty"`
	HotelIds      []string               `protobuf:"bytes,5,rep,name=hotel_ids,json=hotelIds,proto3" json:"hotel_ids,omitempty"`
	CheckInDate   string                 `protobuf:"bytes,2,opt,name=check_in_date,json=checkInDate,proto3" json:"check_in_date,omitempty"`
	CheckOutDate  string                 `protobuf:"bytes,3,opt,name=check_out_date,json=checkOutDate,proto3" json:"check_out_date,omitempty"`
	Adults        int32                  `protobuf:"varint,4,opt,name=adults,proto3" json:"adults,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotelRequest) Reset() {
	*x = SearchHotelRequest{}
	mi := &file_service_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelRequest) ProtoMessage() {}

func (x *SearchHotelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelRequest.ProtoReflect.Descriptor instead.
func (*SearchHotelRequest) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchHotelRequest) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *SearchHotelRequest) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

func (x *SearchHotelRequest) GetCheckInDate() string {
	if x != nil {
		return x.CheckInDate
	}
	return ""
}

func (x *SearchHotelRequest) GetCheckOutDate() string {
	if x != nil {
		return x.CheckOutDate
	}
	return ""
}

func (x *SearchHotelRequest) GetAdults() int32 {
	if x != nil {
		return x.Adults
	}
	return 0
}

type SearchHotelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHotelResponse) Reset() {
	*x = SearchHotelResponse{}
	mi := &file_service_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHotelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHotelResponse) ProtoMessage() {}

func (x *SearchHotelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHotelResponse.ProtoReflect.Descriptor instead.
func (*SearchHotelResponse) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{3}
}

func (x *SearchHotelResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

type SearchTransferRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StartLocationCode string                 `protobuf:"bytes,1,opt,name=start_location_code,json=startLocationCode,proto3" json:"start_location_code,omitempty"`
	EndLocationCode   string                 `protobuf:"bytes,2,opt,name=end_location_code,json=endLocationCode,proto3" json:"end_location_code,omitempty"`
	StartDateTime     string                 `protobuf:"bytes,3,opt,name=start_date_time,json=startDateTime,proto3" json:"start_date_time,omitempty"`
	Passengers        int32                  `protobuf:"varint,4,opt,name=passengers,proto3" json:"passengers,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchTransferRequest) Reset() {
	*x = SearchTransferRequest{}
	mi := &file_service_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransferRequest) ProtoMessage() {}

func (x *SearchTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransferRequest.ProtoReflect.Descriptor instead.
func (*SearchTransferRequest) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchTransferRequest) GetStartLocationCode() string {
	if x != nil {
		return x.StartLocationCode
	}
	return ""
}

func (x *SearchTransferRequest) GetEndLocationCode() string {
	if x != nil {
		return x.EndLocationCode
	}
	return ""
}

func (x *SearchTransferRequest) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *SearchTransferRequest) GetPassengers() int32 {
	if x != nil {
		return x.Passengers
	}
	return 0
}

type SearchTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       []byte                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTransferResponse) Reset() {
	*x = SearchTransferResponse{}
	mi := &file_service_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTransferResponse) ProtoMessage() {}

func (x *SearchTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTransferResponse.ProtoReflect.Descriptor instead.
func (*SearchTransferResponse) Descriptor() ([]byte, []int) {
	return file_service_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchTransferResponse) GetRawJson() []byte {
	if x != nil {
		return x.RawJson
	}
	return nil
}

var File_service_search_proto protoreflect.FileDescriptor

const file_service_search_proto_rawDesc = "" +
	"\n" +
	"\x14service/search.proto\x12\x14travelingman.service\"\xdf\x01\n" +
	"\x13SearchFlightRequest\x12\x16\n" +
	"\x06origin\x18\x01 \x01(\tR\x06origin\x12 \n" +
	"\vdestination\x18\x02 \x01(\tR\vdestination\x12%\n" +
	"\x0edeparture_date\x18\x03 \x01(\tR\rdepartureDate\x12\x1f\n" +
	"\vreturn_date\x18\x04 \x01(\tR\n" +
	"returnDate\x12\x16\n" +
	"\x06adults\x18\x05 \x01(\x05R\x06adults\x12.\n" +
	"\x13target_arrival_time\x18\x06 \x01(\tR\x11targetArrivalTime\"1\n" +
	"\x14SearchFlightResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\xb0\x01\n" +
	"\x12SearchHotelRequest\x12\x1b\n" +
	"\tcity_code\x18\x01 \x01(\tR\bcityCode\x12\x1b\n" +
	"\thotel_ids\x18\x05 \x03(\tR\bhotelIds\x12\"\n" +
	"\rcheck_in_date\x18\x02 \x01(\tR\vcheckInDate\x12$\n" +
	"\x0echeck_out_date\x18\x03 \x01(\tR\fcheckOutDate\x12\x16\n" +
	"\x06adults\x18\x04 \x01(\x05R\x06adults\"0\n" +
	"\x13SearchHotelResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJson\"\xbb\x01\n" +
	"\x15SearchTransferRequest\x12.\n" +
	"\x13start_location_code\x18\x01 \x01(\tR\x11startLocationCode\x12*\n" +
	"\x11end_location_code\x18\x02 \x01(\tR\x0fendLocationCode\x12&\n" +
	"\x0fstart_date_time\x18\x03 \x01(\tR\rstartDateTime\x12\x1e\n" +
	"\n" +
	"passengers\x18\x04 \x01(\x05R\n" +
	"passengers\"3\n" +
	"\x16SearchTransferResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\fR\arawJsonB%Z#github.com/va6996/travelingman/pb/serviceb\x06proto3"

var (
	file_service_search_proto_rawDescOnce sync.Once
	file_service_search_proto_rawDescData []byte
)

func file_service_search_proto_rawDescGZIP() []byte {
	file_service_search_proto_rawDescOnce.Do(func() {
		file_service_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_search_proto_rawDesc), len(file_service_search_proto_rawDesc)))
	})
	return file_service_search_proto_rawDescData
}

var file_service_search_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_search_proto_goTypes = []any{
	(*SearchFlightRequest)(nil),    // 0: travelingman.service.SearchFlightRequest
	(*SearchFlightResponse)(nil),   // 1: travelingman.service.SearchFlightResponse
	(*SearchHotelRequest)(nil),     // 2: travelingman.service.SearchHotelRequest
	(*SearchHotelResponse)(nil),    // 3: travelingman.service.SearchHotelResponse
	(*SearchTransferRequest)(nil),  // 4: travelingman.service.SearchTransferRequest
	(*SearchTransferResponse)(nil), // 5: travelingman.service.SearchTransferResponse
}
var file_service_search_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_search_proto_init() }
func file_service_search_proto_init() {
	if File_service_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_search_proto_rawDesc), len(file_service_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_search_proto_goTypes,
		DependencyIndexes: file_service_search_proto_depIdxs,
		MessageInfos:      file_service_search_proto_msgTypes,
	}.Build()
	File_service_search_proto = out.File
	file_service_search_proto_goTypes = nil
	file_service_search_proto_depIdxs = nil
}
