// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: service/trips.proto

package service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Destination   string                 `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	StartDate     string                 `protobuf:"bytes,4,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // RFC3339 or YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,5,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_service_trips_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_trips_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_service_trips_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTripRequest) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateTripRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTripRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *CreateTripRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *CreateTripRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type GetTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripRequest) Reset() {
	*x = GetTripRequest{}
	mi := &file_service_trips_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripRequest) ProtoMessage() {}

func (x *GetTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_trips_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripRequest.ProtoReflect.Descriptor instead.
func (*GetTripRequest) Descriptor() ([]byte, []int) {
	return file_service_trips_proto_rawDescGZIP(), []int{1}
}

func (x *GetTripRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

type GetTripFlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        int64                  `protobuf:"varint,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTripFlowRequest) Reset() {
	*x = GetTripFlowRequest{}
	mi := &file_service_trips_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTripFlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTripFlowRequest) ProtoMessage() {}

func (x *GetTripFlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_trips_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTripFlowRequest.ProtoReflect.Descriptor instead.
func (*GetTripFlowRequest) Descriptor() ([]byte, []int) {
	return file_service_trips_proto_rawDescGZIP(), []int{2}
}

func (x *GetTripFlowRequest) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

var File_service_trips_proto protoreflect.FileDescriptor

const file_service_trips_proto_rawDesc = "" +
	"\n" +
	"\x13service/trips.proto\x12\x14travelingman.service\"\x9e\x01\n" +
	"\x11CreateTripRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdestination\x18\x03 \x01(\tR\vdestination\x12\x1d\n" +
	"\n" +
	"start_date\x18\x04 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x05 \x01(\tR\aendDate\")\n" +
	"\x0eGetTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripId\"-\n" +
	"\x12GetTripFlowRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\x03R\x06tripIdB%Z#example.com/travelingman/pb/serviceb\x06proto3"

var (
	file_service_trips_proto_rawDescOnce sync.Once
	file_service_trips_proto_rawDescData []byte
)

func file_service_trips_proto_rawDescGZIP() []byte {
	file_service_trips_proto_rawDescOnce.Do(func() {
		file_service_trips_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_trips_proto_rawDesc), len(file_service_trips_proto_rawDesc)))
	})
	return file_service_trips_proto_rawDescData
}

var file_service_trips_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_trips_proto_goTypes = []any{
	(*CreateTripRequest)(nil),  // 0: travelingman.service.CreateTripRequest
	(*GetTripRequest)(nil),     // 1: travelingman.service.GetTripRequest
	(*GetTripFlowRequest)(nil), // 2: travelingman.service.GetTripFlowRequest
}
var file_service_trips_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_trips_proto_init() }
func file_service_trips_proto_init() {
	if File_service_trips_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_trips_proto_rawDesc), len(file_service_trips_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_service_trips_proto_goTypes,
		DependencyIndexes: file_service_trips_proto_depIdxs,
		MessageInfos:      file_service_trips_proto_msgTypes,
	}.Build()
	File_service_trips_proto = out.File
	file_service_trips_proto_goTypes = nil
	file_service_trips_proto_depIdxs = nil
}
