// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: protos/common.proto

/* eslint-disable */

export const protobufPackage = "travelingman";
