// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: protos/graph.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { Accommodation, Transport } from "./itinerary";

export const protobufPackage = "travelingman";

export enum JourneyType {
  JOURNEY_TYPE_UNSPECIFIED = 0,
  JOURNEY_TYPE_ONE_WAY = 1,
  JOURNEY_TYPE_RETURN = 2,
  JOURNEY_TYPE_MULTI_CITY = 3,
  JOURNEY_TYPE_OPEN_JAW = 4,
  JOURNEY_TYPE_CIRCLE_TRIP = 5,
  UNRECOGNIZED = -1,
}

export function journeyTypeFromJSON(object: any): JourneyType {
  switch (object) {
    case 0:
    case "JOURNEY_TYPE_UNSPECIFIED":
      return JourneyType.JOURNEY_TYPE_UNSPECIFIED;
    case 1:
    case "JOURNEY_TYPE_ONE_WAY":
      return JourneyType.JOURNEY_TYPE_ONE_WAY;
    case 2:
    case "JOURNEY_TYPE_RETURN":
      return JourneyType.JOURNEY_TYPE_RETURN;
    case 3:
    case "JOURNEY_TYPE_MULTI_CITY":
      return JourneyType.JOURNEY_TYPE_MULTI_CITY;
    case 4:
    case "JOURNEY_TYPE_OPEN_JAW":
      return JourneyType.JOURNEY_TYPE_OPEN_JAW;
    case 5:
    case "JOURNEY_TYPE_CIRCLE_TRIP":
      return JourneyType.JOURNEY_TYPE_CIRCLE_TRIP;
    case -1:
    case "UNRECOGNIZED":
    default:
      return JourneyType.UNRECOGNIZED;
  }
}

export function journeyTypeToJSON(object: JourneyType): string {
  switch (object) {
    case JourneyType.JOURNEY_TYPE_UNSPECIFIED:
      return "JOURNEY_TYPE_UNSPECIFIED";
    case JourneyType.JOURNEY_TYPE_ONE_WAY:
      return "JOURNEY_TYPE_ONE_WAY";
    case JourneyType.JOURNEY_TYPE_RETURN:
      return "JOURNEY_TYPE_RETURN";
    case JourneyType.JOURNEY_TYPE_MULTI_CITY:
      return "JOURNEY_TYPE_MULTI_CITY";
    case JourneyType.JOURNEY_TYPE_OPEN_JAW:
      return "JOURNEY_TYPE_OPEN_JAW";
    case JourneyType.JOURNEY_TYPE_CIRCLE_TRIP:
      return "JOURNEY_TYPE_CIRCLE_TRIP";
    case JourneyType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/**
 * Node represents a location/place in the itinerary graph
 * It maps to protobuf structures: TripDay, Place, Accommodation
 */
export interface Node {
  /** Unique identifier for the node */
  id: string;
  /** Name or address of the location */
  location: string;
  /** Arrival time at this node */
  fromTimestamp:
    | Date
    | undefined;
  /** Departure time from this node */
  toTimestamp:
    | Date
    | undefined;
  /** Whether this node represents an inter-city travel point */
  isInterCity: boolean;
  /** Hotel/accommodation info (from Accommodation) */
  stay:
    | Accommodation
    | undefined;
  /** List of possible accommodations */
  stayOptions: Accommodation[];
  /** Sub-graph for daily activities */
  subGraph: Graph | undefined;
}

/**
 * Edge represents transportation between two locations
 * It maps to protobuf structures: Transport
 */
export interface Edge {
  /** ID of the source node */
  fromId: string;
  /** ID of the destination node */
  toId: string;
  /** Duration of travel in seconds */
  durationSeconds: number;
  /** Full Transport struct from Transport */
  transport:
    | Transport
    | undefined;
  /** List of possible transports */
  transportOptions: Transport[];
}

/** Graph represents the complete graph structure of a user's itinerary */
export interface Graph {
  /** List of nodes in the graph */
  nodes: Node[];
  /** List of edges in the graph */
  edges: Edge[];
  /** For intra-city details (contains Places) */
  subGraph: Graph | undefined;
}

export interface Itinerary {
  id: number;
  groupId: number;
  dayNumber: number;
  startTime: Date | undefined;
  endTime: Date | undefined;
  title: string;
  description: string;
  graph: Graph | undefined;
  travelers: number;
  tags: string[];
  journeyType: JourneyType;
}

function createBaseNode(): Node {
  return {
    id: "",
    location: "",
    fromTimestamp: undefined,
    toTimestamp: undefined,
    isInterCity: false,
    stay: undefined,
    stayOptions: [],
    subGraph: undefined,
  };
}

export const Node: MessageFns<Node> = {
  encode(message: Node, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.location !== "") {
      writer.uint32(18).string(message.location);
    }
    if (message.fromTimestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.fromTimestamp), writer.uint32(26).fork()).join();
    }
    if (message.toTimestamp !== undefined) {
      Timestamp.encode(toTimestamp(message.toTimestamp), writer.uint32(34).fork()).join();
    }
    if (message.isInterCity !== false) {
      writer.uint32(40).bool(message.isInterCity);
    }
    if (message.stay !== undefined) {
      Accommodation.encode(message.stay, writer.uint32(50).fork()).join();
    }
    for (const v of message.stayOptions) {
      Accommodation.encode(v!, writer.uint32(58).fork()).join();
    }
    if (message.subGraph !== undefined) {
      Graph.encode(message.subGraph, writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Node {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.location = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.fromTimestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.toTimestamp = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.isInterCity = reader.bool();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.stay = Accommodation.decode(reader, reader.uint32());
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.stayOptions.push(Accommodation.decode(reader, reader.uint32()));
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.subGraph = Graph.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Node {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      location: isSet(object.location) ? globalThis.String(object.location) : "",
      fromTimestamp: isSet(object.fromTimestamp) ? fromJsonTimestamp(object.fromTimestamp) : undefined,
      toTimestamp: isSet(object.toTimestamp) ? fromJsonTimestamp(object.toTimestamp) : undefined,
      isInterCity: isSet(object.isInterCity) ? globalThis.Boolean(object.isInterCity) : false,
      stay: isSet(object.stay) ? Accommodation.fromJSON(object.stay) : undefined,
      stayOptions: globalThis.Array.isArray(object?.stayOptions)
        ? object.stayOptions.map((e: any) => Accommodation.fromJSON(e))
        : [],
      subGraph: isSet(object.subGraph) ? Graph.fromJSON(object.subGraph) : undefined,
    };
  },

  toJSON(message: Node): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.location !== "") {
      obj.location = message.location;
    }
    if (message.fromTimestamp !== undefined) {
      obj.fromTimestamp = message.fromTimestamp.toISOString();
    }
    if (message.toTimestamp !== undefined) {
      obj.toTimestamp = message.toTimestamp.toISOString();
    }
    if (message.isInterCity !== false) {
      obj.isInterCity = message.isInterCity;
    }
    if (message.stay !== undefined) {
      obj.stay = Accommodation.toJSON(message.stay);
    }
    if (message.stayOptions?.length) {
      obj.stayOptions = message.stayOptions.map((e) => Accommodation.toJSON(e));
    }
    if (message.subGraph !== undefined) {
      obj.subGraph = Graph.toJSON(message.subGraph);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Node>, I>>(base?: I): Node {
    return Node.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Node>, I>>(object: I): Node {
    const message = createBaseNode();
    message.id = object.id ?? "";
    message.location = object.location ?? "";
    message.fromTimestamp = object.fromTimestamp ?? undefined;
    message.toTimestamp = object.toTimestamp ?? undefined;
    message.isInterCity = object.isInterCity ?? false;
    message.stay = (object.stay !== undefined && object.stay !== null)
      ? Accommodation.fromPartial(object.stay)
      : undefined;
    message.stayOptions = object.stayOptions?.map((e) => Accommodation.fromPartial(e)) || [];
    message.subGraph = (object.subGraph !== undefined && object.subGraph !== null)
      ? Graph.fromPartial(object.subGraph)
      : undefined;
    return message;
  },
};

function createBaseEdge(): Edge {
  return { fromId: "", toId: "", durationSeconds: 0, transport: undefined, transportOptions: [] };
}

export const Edge: MessageFns<Edge> = {
  encode(message: Edge, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.fromId !== "") {
      writer.uint32(10).string(message.fromId);
    }
    if (message.toId !== "") {
      writer.uint32(18).string(message.toId);
    }
    if (message.durationSeconds !== 0) {
      writer.uint32(24).int64(message.durationSeconds);
    }
    if (message.transport !== undefined) {
      Transport.encode(message.transport, writer.uint32(34).fork()).join();
    }
    for (const v of message.transportOptions) {
      Transport.encode(v!, writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Edge {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseEdge();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.fromId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.toId = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.durationSeconds = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.transport = Transport.decode(reader, reader.uint32());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.transportOptions.push(Transport.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Edge {
    return {
      fromId: isSet(object.fromId) ? globalThis.String(object.fromId) : "",
      toId: isSet(object.toId) ? globalThis.String(object.toId) : "",
      durationSeconds: isSet(object.durationSeconds) ? globalThis.Number(object.durationSeconds) : 0,
      transport: isSet(object.transport) ? Transport.fromJSON(object.transport) : undefined,
      transportOptions: globalThis.Array.isArray(object?.transportOptions)
        ? object.transportOptions.map((e: any) => Transport.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Edge): unknown {
    const obj: any = {};
    if (message.fromId !== "") {
      obj.fromId = message.fromId;
    }
    if (message.toId !== "") {
      obj.toId = message.toId;
    }
    if (message.durationSeconds !== 0) {
      obj.durationSeconds = Math.round(message.durationSeconds);
    }
    if (message.transport !== undefined) {
      obj.transport = Transport.toJSON(message.transport);
    }
    if (message.transportOptions?.length) {
      obj.transportOptions = message.transportOptions.map((e) => Transport.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Edge>, I>>(base?: I): Edge {
    return Edge.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Edge>, I>>(object: I): Edge {
    const message = createBaseEdge();
    message.fromId = object.fromId ?? "";
    message.toId = object.toId ?? "";
    message.durationSeconds = object.durationSeconds ?? 0;
    message.transport = (object.transport !== undefined && object.transport !== null)
      ? Transport.fromPartial(object.transport)
      : undefined;
    message.transportOptions = object.transportOptions?.map((e) => Transport.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGraph(): Graph {
  return { nodes: [], edges: [], subGraph: undefined };
}

export const Graph: MessageFns<Graph> = {
  encode(message: Graph, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.nodes) {
      Node.encode(v!, writer.uint32(10).fork()).join();
    }
    for (const v of message.edges) {
      Edge.encode(v!, writer.uint32(18).fork()).join();
    }
    if (message.subGraph !== undefined) {
      Graph.encode(message.subGraph, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Graph {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGraph();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.nodes.push(Node.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.edges.push(Edge.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subGraph = Graph.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Graph {
    return {
      nodes: globalThis.Array.isArray(object?.nodes) ? object.nodes.map((e: any) => Node.fromJSON(e)) : [],
      edges: globalThis.Array.isArray(object?.edges) ? object.edges.map((e: any) => Edge.fromJSON(e)) : [],
      subGraph: isSet(object.subGraph) ? Graph.fromJSON(object.subGraph) : undefined,
    };
  },

  toJSON(message: Graph): unknown {
    const obj: any = {};
    if (message.nodes?.length) {
      obj.nodes = message.nodes.map((e) => Node.toJSON(e));
    }
    if (message.edges?.length) {
      obj.edges = message.edges.map((e) => Edge.toJSON(e));
    }
    if (message.subGraph !== undefined) {
      obj.subGraph = Graph.toJSON(message.subGraph);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Graph>, I>>(base?: I): Graph {
    return Graph.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Graph>, I>>(object: I): Graph {
    const message = createBaseGraph();
    message.nodes = object.nodes?.map((e) => Node.fromPartial(e)) || [];
    message.edges = object.edges?.map((e) => Edge.fromPartial(e)) || [];
    message.subGraph = (object.subGraph !== undefined && object.subGraph !== null)
      ? Graph.fromPartial(object.subGraph)
      : undefined;
    return message;
  },
};

function createBaseItinerary(): Itinerary {
  return {
    id: 0,
    groupId: 0,
    dayNumber: 0,
    startTime: undefined,
    endTime: undefined,
    title: "",
    description: "",
    graph: undefined,
    travelers: 0,
    tags: [],
    journeyType: 0,
  };
}

export const Itinerary: MessageFns<Itinerary> = {
  encode(message: Itinerary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.dayNumber !== 0) {
      writer.uint32(24).int32(message.dayNumber);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(34).fork()).join();
    }
    if (message.endTime !== undefined) {
      Timestamp.encode(toTimestamp(message.endTime), writer.uint32(42).fork()).join();
    }
    if (message.title !== "") {
      writer.uint32(50).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(58).string(message.description);
    }
    if (message.graph !== undefined) {
      Graph.encode(message.graph, writer.uint32(66).fork()).join();
    }
    if (message.travelers !== 0) {
      writer.uint32(72).int32(message.travelers);
    }
    for (const v of message.tags) {
      writer.uint32(82).string(v!);
    }
    if (message.journeyType !== 0) {
      writer.uint32(88).int32(message.journeyType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Itinerary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItinerary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dayNumber = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.endTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.graph = Graph.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 72) {
            break;
          }

          message.travelers = reader.int32();
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.tags.push(reader.string());
          continue;
        }
        case 11: {
          if (tag !== 88) {
            break;
          }

          message.journeyType = reader.int32() as any;
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Itinerary {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      dayNumber: isSet(object.dayNumber) ? globalThis.Number(object.dayNumber) : 0,
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      endTime: isSet(object.endTime) ? fromJsonTimestamp(object.endTime) : undefined,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      graph: isSet(object.graph) ? Graph.fromJSON(object.graph) : undefined,
      travelers: isSet(object.travelers) ? globalThis.Number(object.travelers) : 0,
      tags: globalThis.Array.isArray(object?.tags) ? object.tags.map((e: any) => globalThis.String(e)) : [],
      journeyType: isSet(object.journeyType) ? journeyTypeFromJSON(object.journeyType) : 0,
    };
  },

  toJSON(message: Itinerary): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.dayNumber !== 0) {
      obj.dayNumber = Math.round(message.dayNumber);
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime.toISOString();
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.graph !== undefined) {
      obj.graph = Graph.toJSON(message.graph);
    }
    if (message.travelers !== 0) {
      obj.travelers = Math.round(message.travelers);
    }
    if (message.tags?.length) {
      obj.tags = message.tags;
    }
    if (message.journeyType !== 0) {
      obj.journeyType = journeyTypeToJSON(message.journeyType);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Itinerary>, I>>(base?: I): Itinerary {
    return Itinerary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Itinerary>, I>>(object: I): Itinerary {
    const message = createBaseItinerary();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.dayNumber = object.dayNumber ?? 0;
    message.startTime = object.startTime ?? undefined;
    message.endTime = object.endTime ?? undefined;
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.graph = (object.graph !== undefined && object.graph !== null) ? Graph.fromPartial(object.graph) : undefined;
    message.travelers = object.travelers ?? 0;
    message.tags = object.tags?.map((e) => e) || [];
    message.journeyType = object.journeyType ?? 0;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
