// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: protos/itinerary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";

export const protobufPackage = "travelingman";

export enum TransportType {
  TRANSPORT_TYPE_UNSPECIFIED = 0,
  TRANSPORT_TYPE_FLIGHT = 1,
  TRANSPORT_TYPE_TRAIN = 2,
  TRANSPORT_TYPE_CAR = 3,
  TRANSPORT_TYPE_WALKING = 4,
  UNRECOGNIZED = -1,
}

export function transportTypeFromJSON(object: any): TransportType {
  switch (object) {
    case 0:
    case "TRANSPORT_TYPE_UNSPECIFIED":
      return TransportType.TRANSPORT_TYPE_UNSPECIFIED;
    case 1:
    case "TRANSPORT_TYPE_FLIGHT":
      return TransportType.TRANSPORT_TYPE_FLIGHT;
    case 2:
    case "TRANSPORT_TYPE_TRAIN":
      return TransportType.TRANSPORT_TYPE_TRAIN;
    case 3:
    case "TRANSPORT_TYPE_CAR":
      return TransportType.TRANSPORT_TYPE_CAR;
    case 4:
    case "TRANSPORT_TYPE_WALKING":
      return TransportType.TRANSPORT_TYPE_WALKING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransportType.UNRECOGNIZED;
  }
}

export function transportTypeToJSON(object: TransportType): string {
  switch (object) {
    case TransportType.TRANSPORT_TYPE_UNSPECIFIED:
      return "TRANSPORT_TYPE_UNSPECIFIED";
    case TransportType.TRANSPORT_TYPE_FLIGHT:
      return "TRANSPORT_TYPE_FLIGHT";
    case TransportType.TRANSPORT_TYPE_TRAIN:
      return "TRANSPORT_TYPE_TRAIN";
    case TransportType.TRANSPORT_TYPE_CAR:
      return "TRANSPORT_TYPE_CAR";
    case TransportType.TRANSPORT_TYPE_WALKING:
      return "TRANSPORT_TYPE_WALKING";
    case TransportType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Class {
  CLASS_UNSPECIFIED = 0,
  CLASS_ECONOMY = 1,
  CLASS_PREMIUM_ECONOMY = 2,
  CLASS_BUSINESS = 3,
  CLASS_FIRST = 4,
  UNRECOGNIZED = -1,
}

export function classFromJSON(object: any): Class {
  switch (object) {
    case 0:
    case "CLASS_UNSPECIFIED":
      return Class.CLASS_UNSPECIFIED;
    case 1:
    case "CLASS_ECONOMY":
      return Class.CLASS_ECONOMY;
    case 2:
    case "CLASS_PREMIUM_ECONOMY":
      return Class.CLASS_PREMIUM_ECONOMY;
    case 3:
    case "CLASS_BUSINESS":
      return Class.CLASS_BUSINESS;
    case 4:
    case "CLASS_FIRST":
      return Class.CLASS_FIRST;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Class.UNRECOGNIZED;
  }
}

export function classToJSON(object: Class): string {
  switch (object) {
    case Class.CLASS_UNSPECIFIED:
      return "CLASS_UNSPECIFIED";
    case Class.CLASS_ECONOMY:
      return "CLASS_ECONOMY";
    case Class.CLASS_PREMIUM_ECONOMY:
      return "CLASS_PREMIUM_ECONOMY";
    case Class.CLASS_BUSINESS:
      return "CLASS_BUSINESS";
    case Class.CLASS_FIRST:
      return "CLASS_FIRST";
    case Class.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Transmission {
  TRANSMISSION_UNSPECIFIED = 0,
  TRANSMISSION_MANUAL = 1,
  TRANSMISSION_AUTOMATIC = 2,
  UNRECOGNIZED = -1,
}

export function transmissionFromJSON(object: any): Transmission {
  switch (object) {
    case 0:
    case "TRANSMISSION_UNSPECIFIED":
      return Transmission.TRANSMISSION_UNSPECIFIED;
    case 1:
    case "TRANSMISSION_MANUAL":
      return Transmission.TRANSMISSION_MANUAL;
    case 2:
    case "TRANSMISSION_AUTOMATIC":
      return Transmission.TRANSMISSION_AUTOMATIC;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Transmission.UNRECOGNIZED;
  }
}

export function transmissionToJSON(object: Transmission): string {
  switch (object) {
    case Transmission.TRANSMISSION_UNSPECIFIED:
      return "TRANSMISSION_UNSPECIFIED";
    case Transmission.TRANSMISSION_MANUAL:
      return "TRANSMISSION_MANUAL";
    case Transmission.TRANSMISSION_AUTOMATIC:
      return "TRANSMISSION_AUTOMATIC";
    case Transmission.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface AccommodationPreferences {
  roomType: string;
  area: string;
  rating: number;
  amenities: string[];
}

export interface FlightPreferences {
  travelClass: Class;
  maxStops: number;
  preferredOriginAirports: string[];
  preferredDestinationAirports: string[];
}

export interface TrainPreferences {
  travelClass: Class;
  seatType: string;
}

export interface CarRentalPreferences {
  transmission: Transmission;
  carClass: string;
}

export interface Location {
  area: string;
  city: string;
  country: string;
  iataCodes: string[];
  cityCode: string;
  geocode: string;
  zip: string;
  name: string;
}

export interface Accommodation {
  id: number;
  groupId: number;
  name: string;
  address: string;
  checkIn: Date | undefined;
  checkOut: Date | undefined;
  priceTotal: string;
  bookingReference: string;
  status: string;
  userIds: number[];
  preferences: AccommodationPreferences | undefined;
  travelerCount: number;
  location: Location | undefined;
}

export interface Transport {
  id: number;
  bookingId: number;
  plugin: string;
  referenceNumber: string;
  status: string;
  type: TransportType;
  travelerCount: number;
  originLocation: Location | undefined;
  destinationLocation: Location | undefined;
  userIds: number[];
  priceTotal: number;
  flightPreferences: FlightPreferences | undefined;
  trainPreferences: TrainPreferences | undefined;
  carRentalPreferences: CarRentalPreferences | undefined;
  flight?: Flight | undefined;
  train?: Train | undefined;
  carRental?: CarRental | undefined;
}

export interface Flight {
  carrierCode: string;
  flightNumber: string;
  departureTime: Date | undefined;
  arrivalTime: Date | undefined;
}

export interface Train {
  departureTime: Date | undefined;
  arrivalTime: Date | undefined;
  trainNumber: string;
}

export interface CarRental {
  company: string;
  pickupTime: Date | undefined;
  dropoffTime: Date | undefined;
  carType: string;
}

function createBaseAccommodationPreferences(): AccommodationPreferences {
  return { roomType: "", area: "", rating: 0, amenities: [] };
}

export const AccommodationPreferences: MessageFns<AccommodationPreferences> = {
  encode(message: AccommodationPreferences, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.roomType !== "") {
      writer.uint32(10).string(message.roomType);
    }
    if (message.area !== "") {
      writer.uint32(18).string(message.area);
    }
    if (message.rating !== 0) {
      writer.uint32(24).int32(message.rating);
    }
    for (const v of message.amenities) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AccommodationPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccommodationPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.roomType = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.rating = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amenities.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AccommodationPreferences {
    return {
      roomType: isSet(object.roomType) ? globalThis.String(object.roomType) : "",
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      rating: isSet(object.rating) ? globalThis.Number(object.rating) : 0,
      amenities: globalThis.Array.isArray(object?.amenities)
        ? object.amenities.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: AccommodationPreferences): unknown {
    const obj: any = {};
    if (message.roomType !== "") {
      obj.roomType = message.roomType;
    }
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.rating !== 0) {
      obj.rating = Math.round(message.rating);
    }
    if (message.amenities?.length) {
      obj.amenities = message.amenities;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AccommodationPreferences>, I>>(base?: I): AccommodationPreferences {
    return AccommodationPreferences.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AccommodationPreferences>, I>>(object: I): AccommodationPreferences {
    const message = createBaseAccommodationPreferences();
    message.roomType = object.roomType ?? "";
    message.area = object.area ?? "";
    message.rating = object.rating ?? 0;
    message.amenities = object.amenities?.map((e) => e) || [];
    return message;
  },
};

function createBaseFlightPreferences(): FlightPreferences {
  return { travelClass: 0, maxStops: 0, preferredOriginAirports: [], preferredDestinationAirports: [] };
}

export const FlightPreferences: MessageFns<FlightPreferences> = {
  encode(message: FlightPreferences, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.travelClass !== 0) {
      writer.uint32(8).int32(message.travelClass);
    }
    if (message.maxStops !== 0) {
      writer.uint32(16).int32(message.maxStops);
    }
    for (const v of message.preferredOriginAirports) {
      writer.uint32(26).string(v!);
    }
    for (const v of message.preferredDestinationAirports) {
      writer.uint32(34).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlightPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlightPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.travelClass = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxStops = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.preferredOriginAirports.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.preferredDestinationAirports.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FlightPreferences {
    return {
      travelClass: isSet(object.travelClass) ? classFromJSON(object.travelClass) : 0,
      maxStops: isSet(object.maxStops) ? globalThis.Number(object.maxStops) : 0,
      preferredOriginAirports: globalThis.Array.isArray(object?.preferredOriginAirports)
        ? object.preferredOriginAirports.map((e: any) => globalThis.String(e))
        : [],
      preferredDestinationAirports: globalThis.Array.isArray(object?.preferredDestinationAirports)
        ? object.preferredDestinationAirports.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: FlightPreferences): unknown {
    const obj: any = {};
    if (message.travelClass !== 0) {
      obj.travelClass = classToJSON(message.travelClass);
    }
    if (message.maxStops !== 0) {
      obj.maxStops = Math.round(message.maxStops);
    }
    if (message.preferredOriginAirports?.length) {
      obj.preferredOriginAirports = message.preferredOriginAirports;
    }
    if (message.preferredDestinationAirports?.length) {
      obj.preferredDestinationAirports = message.preferredDestinationAirports;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlightPreferences>, I>>(base?: I): FlightPreferences {
    return FlightPreferences.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlightPreferences>, I>>(object: I): FlightPreferences {
    const message = createBaseFlightPreferences();
    message.travelClass = object.travelClass ?? 0;
    message.maxStops = object.maxStops ?? 0;
    message.preferredOriginAirports = object.preferredOriginAirports?.map((e) => e) || [];
    message.preferredDestinationAirports = object.preferredDestinationAirports?.map((e) => e) || [];
    return message;
  },
};

function createBaseTrainPreferences(): TrainPreferences {
  return { travelClass: 0, seatType: "" };
}

export const TrainPreferences: MessageFns<TrainPreferences> = {
  encode(message: TrainPreferences, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.travelClass !== 0) {
      writer.uint32(8).int32(message.travelClass);
    }
    if (message.seatType !== "") {
      writer.uint32(18).string(message.seatType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TrainPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrainPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.travelClass = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.seatType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TrainPreferences {
    return {
      travelClass: isSet(object.travelClass) ? classFromJSON(object.travelClass) : 0,
      seatType: isSet(object.seatType) ? globalThis.String(object.seatType) : "",
    };
  },

  toJSON(message: TrainPreferences): unknown {
    const obj: any = {};
    if (message.travelClass !== 0) {
      obj.travelClass = classToJSON(message.travelClass);
    }
    if (message.seatType !== "") {
      obj.seatType = message.seatType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TrainPreferences>, I>>(base?: I): TrainPreferences {
    return TrainPreferences.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TrainPreferences>, I>>(object: I): TrainPreferences {
    const message = createBaseTrainPreferences();
    message.travelClass = object.travelClass ?? 0;
    message.seatType = object.seatType ?? "";
    return message;
  },
};

function createBaseCarRentalPreferences(): CarRentalPreferences {
  return { transmission: 0, carClass: "" };
}

export const CarRentalPreferences: MessageFns<CarRentalPreferences> = {
  encode(message: CarRentalPreferences, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.transmission !== 0) {
      writer.uint32(8).int32(message.transmission);
    }
    if (message.carClass !== "") {
      writer.uint32(18).string(message.carClass);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CarRentalPreferences {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCarRentalPreferences();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.transmission = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.carClass = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CarRentalPreferences {
    return {
      transmission: isSet(object.transmission) ? transmissionFromJSON(object.transmission) : 0,
      carClass: isSet(object.carClass) ? globalThis.String(object.carClass) : "",
    };
  },

  toJSON(message: CarRentalPreferences): unknown {
    const obj: any = {};
    if (message.transmission !== 0) {
      obj.transmission = transmissionToJSON(message.transmission);
    }
    if (message.carClass !== "") {
      obj.carClass = message.carClass;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CarRentalPreferences>, I>>(base?: I): CarRentalPreferences {
    return CarRentalPreferences.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CarRentalPreferences>, I>>(object: I): CarRentalPreferences {
    const message = createBaseCarRentalPreferences();
    message.transmission = object.transmission ?? 0;
    message.carClass = object.carClass ?? "";
    return message;
  },
};

function createBaseLocation(): Location {
  return { area: "", city: "", country: "", iataCodes: [], cityCode: "", geocode: "", zip: "", name: "" };
}

export const Location: MessageFns<Location> = {
  encode(message: Location, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.area !== "") {
      writer.uint32(10).string(message.area);
    }
    if (message.city !== "") {
      writer.uint32(18).string(message.city);
    }
    if (message.country !== "") {
      writer.uint32(26).string(message.country);
    }
    for (const v of message.iataCodes) {
      writer.uint32(34).string(v!);
    }
    if (message.cityCode !== "") {
      writer.uint32(42).string(message.cityCode);
    }
    if (message.geocode !== "") {
      writer.uint32(50).string(message.geocode);
    }
    if (message.zip !== "") {
      writer.uint32(58).string(message.zip);
    }
    if (message.name !== "") {
      writer.uint32(66).string(message.name);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Location {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseLocation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.area = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.city = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.country = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.iataCodes.push(reader.string());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.cityCode = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.geocode = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.zip = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.name = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Location {
    return {
      area: isSet(object.area) ? globalThis.String(object.area) : "",
      city: isSet(object.city) ? globalThis.String(object.city) : "",
      country: isSet(object.country) ? globalThis.String(object.country) : "",
      iataCodes: globalThis.Array.isArray(object?.iataCodes)
        ? object.iataCodes.map((e: any) => globalThis.String(e))
        : [],
      cityCode: isSet(object.cityCode) ? globalThis.String(object.cityCode) : "",
      geocode: isSet(object.geocode) ? globalThis.String(object.geocode) : "",
      zip: isSet(object.zip) ? globalThis.String(object.zip) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
    };
  },

  toJSON(message: Location): unknown {
    const obj: any = {};
    if (message.area !== "") {
      obj.area = message.area;
    }
    if (message.city !== "") {
      obj.city = message.city;
    }
    if (message.country !== "") {
      obj.country = message.country;
    }
    if (message.iataCodes?.length) {
      obj.iataCodes = message.iataCodes;
    }
    if (message.cityCode !== "") {
      obj.cityCode = message.cityCode;
    }
    if (message.geocode !== "") {
      obj.geocode = message.geocode;
    }
    if (message.zip !== "") {
      obj.zip = message.zip;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Location>, I>>(base?: I): Location {
    return Location.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Location>, I>>(object: I): Location {
    const message = createBaseLocation();
    message.area = object.area ?? "";
    message.city = object.city ?? "";
    message.country = object.country ?? "";
    message.iataCodes = object.iataCodes?.map((e) => e) || [];
    message.cityCode = object.cityCode ?? "";
    message.geocode = object.geocode ?? "";
    message.zip = object.zip ?? "";
    message.name = object.name ?? "";
    return message;
  },
};

function createBaseAccommodation(): Accommodation {
  return {
    id: 0,
    groupId: 0,
    name: "",
    address: "",
    checkIn: undefined,
    checkOut: undefined,
    priceTotal: "",
    bookingReference: "",
    status: "",
    userIds: [],
    preferences: undefined,
    travelerCount: 0,
    location: undefined,
  };
}

export const Accommodation: MessageFns<Accommodation> = {
  encode(message: Accommodation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.checkIn !== undefined) {
      Timestamp.encode(toTimestamp(message.checkIn), writer.uint32(42).fork()).join();
    }
    if (message.checkOut !== undefined) {
      Timestamp.encode(toTimestamp(message.checkOut), writer.uint32(50).fork()).join();
    }
    if (message.priceTotal !== "") {
      writer.uint32(58).string(message.priceTotal);
    }
    if (message.bookingReference !== "") {
      writer.uint32(66).string(message.bookingReference);
    }
    if (message.status !== "") {
      writer.uint32(74).string(message.status);
    }
    writer.uint32(82).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    if (message.preferences !== undefined) {
      AccommodationPreferences.encode(message.preferences, writer.uint32(90).fork()).join();
    }
    if (message.travelerCount !== 0) {
      writer.uint32(96).int32(message.travelerCount);
    }
    if (message.location !== undefined) {
      Location.encode(message.location, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Accommodation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccommodation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.checkIn = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.checkOut = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.priceTotal = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bookingReference = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 10: {
          if (tag === 80) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.preferences = AccommodationPreferences.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 96) {
            break;
          }

          message.travelerCount = reader.int32();
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.location = Location.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Accommodation {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      checkIn: isSet(object.checkIn) ? fromJsonTimestamp(object.checkIn) : undefined,
      checkOut: isSet(object.checkOut) ? fromJsonTimestamp(object.checkOut) : undefined,
      priceTotal: isSet(object.priceTotal) ? globalThis.String(object.priceTotal) : "",
      bookingReference: isSet(object.bookingReference) ? globalThis.String(object.bookingReference) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
      preferences: isSet(object.preferences) ? AccommodationPreferences.fromJSON(object.preferences) : undefined,
      travelerCount: isSet(object.travelerCount) ? globalThis.Number(object.travelerCount) : 0,
      location: isSet(object.location) ? Location.fromJSON(object.location) : undefined,
    };
  },

  toJSON(message: Accommodation): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.checkIn !== undefined) {
      obj.checkIn = message.checkIn.toISOString();
    }
    if (message.checkOut !== undefined) {
      obj.checkOut = message.checkOut.toISOString();
    }
    if (message.priceTotal !== "") {
      obj.priceTotal = message.priceTotal;
    }
    if (message.bookingReference !== "") {
      obj.bookingReference = message.bookingReference;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    if (message.preferences !== undefined) {
      obj.preferences = AccommodationPreferences.toJSON(message.preferences);
    }
    if (message.travelerCount !== 0) {
      obj.travelerCount = Math.round(message.travelerCount);
    }
    if (message.location !== undefined) {
      obj.location = Location.toJSON(message.location);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Accommodation>, I>>(base?: I): Accommodation {
    return Accommodation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Accommodation>, I>>(object: I): Accommodation {
    const message = createBaseAccommodation();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.checkIn = object.checkIn ?? undefined;
    message.checkOut = object.checkOut ?? undefined;
    message.priceTotal = object.priceTotal ?? "";
    message.bookingReference = object.bookingReference ?? "";
    message.status = object.status ?? "";
    message.userIds = object.userIds?.map((e) => e) || [];
    message.preferences = (object.preferences !== undefined && object.preferences !== null)
      ? AccommodationPreferences.fromPartial(object.preferences)
      : undefined;
    message.travelerCount = object.travelerCount ?? 0;
    message.location = (object.location !== undefined && object.location !== null)
      ? Location.fromPartial(object.location)
      : undefined;
    return message;
  },
};

function createBaseTransport(): Transport {
  return {
    id: 0,
    bookingId: 0,
    plugin: "",
    referenceNumber: "",
    status: "",
    type: 0,
    travelerCount: 0,
    originLocation: undefined,
    destinationLocation: undefined,
    userIds: [],
    priceTotal: 0,
    flightPreferences: undefined,
    trainPreferences: undefined,
    carRentalPreferences: undefined,
    flight: undefined,
    train: undefined,
    carRental: undefined,
  };
}

export const Transport: MessageFns<Transport> = {
  encode(message: Transport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.bookingId !== 0) {
      writer.uint32(16).int64(message.bookingId);
    }
    if (message.plugin !== "") {
      writer.uint32(26).string(message.plugin);
    }
    if (message.referenceNumber !== "") {
      writer.uint32(34).string(message.referenceNumber);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.travelerCount !== 0) {
      writer.uint32(56).int32(message.travelerCount);
    }
    if (message.originLocation !== undefined) {
      Location.encode(message.originLocation, writer.uint32(66).fork()).join();
    }
    if (message.destinationLocation !== undefined) {
      Location.encode(message.destinationLocation, writer.uint32(74).fork()).join();
    }
    writer.uint32(82).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    if (message.priceTotal !== 0) {
      writer.uint32(93).float(message.priceTotal);
    }
    if (message.flightPreferences !== undefined) {
      FlightPreferences.encode(message.flightPreferences, writer.uint32(122).fork()).join();
    }
    if (message.trainPreferences !== undefined) {
      TrainPreferences.encode(message.trainPreferences, writer.uint32(130).fork()).join();
    }
    if (message.carRentalPreferences !== undefined) {
      CarRentalPreferences.encode(message.carRentalPreferences, writer.uint32(138).fork()).join();
    }
    if (message.flight !== undefined) {
      Flight.encode(message.flight, writer.uint32(98).fork()).join();
    }
    if (message.train !== undefined) {
      Train.encode(message.train, writer.uint32(106).fork()).join();
    }
    if (message.carRental !== undefined) {
      CarRental.encode(message.carRental, writer.uint32(114).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookingId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.plugin = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.referenceNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.travelerCount = reader.int32();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.originLocation = Location.decode(reader, reader.uint32());
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.destinationLocation = Location.decode(reader, reader.uint32());
          continue;
        }
        case 10: {
          if (tag === 80) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
        case 11: {
          if (tag !== 93) {
            break;
          }

          message.priceTotal = reader.float();
          continue;
        }
        case 15: {
          if (tag !== 122) {
            break;
          }

          message.flightPreferences = FlightPreferences.decode(reader, reader.uint32());
          continue;
        }
        case 16: {
          if (tag !== 130) {
            break;
          }

          message.trainPreferences = TrainPreferences.decode(reader, reader.uint32());
          continue;
        }
        case 17: {
          if (tag !== 138) {
            break;
          }

          message.carRentalPreferences = CarRentalPreferences.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.flight = Flight.decode(reader, reader.uint32());
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.train = Train.decode(reader, reader.uint32());
          continue;
        }
        case 14: {
          if (tag !== 114) {
            break;
          }

          message.carRental = CarRental.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transport {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      bookingId: isSet(object.bookingId) ? globalThis.Number(object.bookingId) : 0,
      plugin: isSet(object.plugin) ? globalThis.String(object.plugin) : "",
      referenceNumber: isSet(object.referenceNumber) ? globalThis.String(object.referenceNumber) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      type: isSet(object.type) ? transportTypeFromJSON(object.type) : 0,
      travelerCount: isSet(object.travelerCount) ? globalThis.Number(object.travelerCount) : 0,
      originLocation: isSet(object.originLocation) ? Location.fromJSON(object.originLocation) : undefined,
      destinationLocation: isSet(object.destinationLocation)
        ? Location.fromJSON(object.destinationLocation)
        : undefined,
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
      priceTotal: isSet(object.priceTotal) ? globalThis.Number(object.priceTotal) : 0,
      flightPreferences: isSet(object.flightPreferences)
        ? FlightPreferences.fromJSON(object.flightPreferences)
        : undefined,
      trainPreferences: isSet(object.trainPreferences) ? TrainPreferences.fromJSON(object.trainPreferences) : undefined,
      carRentalPreferences: isSet(object.carRentalPreferences)
        ? CarRentalPreferences.fromJSON(object.carRentalPreferences)
        : undefined,
      flight: isSet(object.flight) ? Flight.fromJSON(object.flight) : undefined,
      train: isSet(object.train) ? Train.fromJSON(object.train) : undefined,
      carRental: isSet(object.carRental) ? CarRental.fromJSON(object.carRental) : undefined,
    };
  },

  toJSON(message: Transport): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.bookingId !== 0) {
      obj.bookingId = Math.round(message.bookingId);
    }
    if (message.plugin !== "") {
      obj.plugin = message.plugin;
    }
    if (message.referenceNumber !== "") {
      obj.referenceNumber = message.referenceNumber;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.type !== 0) {
      obj.type = transportTypeToJSON(message.type);
    }
    if (message.travelerCount !== 0) {
      obj.travelerCount = Math.round(message.travelerCount);
    }
    if (message.originLocation !== undefined) {
      obj.originLocation = Location.toJSON(message.originLocation);
    }
    if (message.destinationLocation !== undefined) {
      obj.destinationLocation = Location.toJSON(message.destinationLocation);
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    if (message.priceTotal !== 0) {
      obj.priceTotal = message.priceTotal;
    }
    if (message.flightPreferences !== undefined) {
      obj.flightPreferences = FlightPreferences.toJSON(message.flightPreferences);
    }
    if (message.trainPreferences !== undefined) {
      obj.trainPreferences = TrainPreferences.toJSON(message.trainPreferences);
    }
    if (message.carRentalPreferences !== undefined) {
      obj.carRentalPreferences = CarRentalPreferences.toJSON(message.carRentalPreferences);
    }
    if (message.flight !== undefined) {
      obj.flight = Flight.toJSON(message.flight);
    }
    if (message.train !== undefined) {
      obj.train = Train.toJSON(message.train);
    }
    if (message.carRental !== undefined) {
      obj.carRental = CarRental.toJSON(message.carRental);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transport>, I>>(base?: I): Transport {
    return Transport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transport>, I>>(object: I): Transport {
    const message = createBaseTransport();
    message.id = object.id ?? 0;
    message.bookingId = object.bookingId ?? 0;
    message.plugin = object.plugin ?? "";
    message.referenceNumber = object.referenceNumber ?? "";
    message.status = object.status ?? "";
    message.type = object.type ?? 0;
    message.travelerCount = object.travelerCount ?? 0;
    message.originLocation = (object.originLocation !== undefined && object.originLocation !== null)
      ? Location.fromPartial(object.originLocation)
      : undefined;
    message.destinationLocation = (object.destinationLocation !== undefined && object.destinationLocation !== null)
      ? Location.fromPartial(object.destinationLocation)
      : undefined;
    message.userIds = object.userIds?.map((e) => e) || [];
    message.priceTotal = object.priceTotal ?? 0;
    message.flightPreferences = (object.flightPreferences !== undefined && object.flightPreferences !== null)
      ? FlightPreferences.fromPartial(object.flightPreferences)
      : undefined;
    message.trainPreferences = (object.trainPreferences !== undefined && object.trainPreferences !== null)
      ? TrainPreferences.fromPartial(object.trainPreferences)
      : undefined;
    message.carRentalPreferences = (object.carRentalPreferences !== undefined && object.carRentalPreferences !== null)
      ? CarRentalPreferences.fromPartial(object.carRentalPreferences)
      : undefined;
    message.flight = (object.flight !== undefined && object.flight !== null)
      ? Flight.fromPartial(object.flight)
      : undefined;
    message.train = (object.train !== undefined && object.train !== null) ? Train.fromPartial(object.train) : undefined;
    message.carRental = (object.carRental !== undefined && object.carRental !== null)
      ? CarRental.fromPartial(object.carRental)
      : undefined;
    return message;
  },
};

function createBaseFlight(): Flight {
  return { carrierCode: "", flightNumber: "", departureTime: undefined, arrivalTime: undefined };
}

export const Flight: MessageFns<Flight> = {
  encode(message: Flight, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.carrierCode !== "") {
      writer.uint32(10).string(message.carrierCode);
    }
    if (message.flightNumber !== "") {
      writer.uint32(18).string(message.flightNumber);
    }
    if (message.departureTime !== undefined) {
      Timestamp.encode(toTimestamp(message.departureTime), writer.uint32(26).fork()).join();
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Flight {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.carrierCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.flightNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.departureTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Flight {
    return {
      carrierCode: isSet(object.carrierCode) ? globalThis.String(object.carrierCode) : "",
      flightNumber: isSet(object.flightNumber) ? globalThis.String(object.flightNumber) : "",
      departureTime: isSet(object.departureTime) ? fromJsonTimestamp(object.departureTime) : undefined,
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
    };
  },

  toJSON(message: Flight): unknown {
    const obj: any = {};
    if (message.carrierCode !== "") {
      obj.carrierCode = message.carrierCode;
    }
    if (message.flightNumber !== "") {
      obj.flightNumber = message.flightNumber;
    }
    if (message.departureTime !== undefined) {
      obj.departureTime = message.departureTime.toISOString();
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Flight>, I>>(base?: I): Flight {
    return Flight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Flight>, I>>(object: I): Flight {
    const message = createBaseFlight();
    message.carrierCode = object.carrierCode ?? "";
    message.flightNumber = object.flightNumber ?? "";
    message.departureTime = object.departureTime ?? undefined;
    message.arrivalTime = object.arrivalTime ?? undefined;
    return message;
  },
};

function createBaseTrain(): Train {
  return { departureTime: undefined, arrivalTime: undefined, trainNumber: "" };
}

export const Train: MessageFns<Train> = {
  encode(message: Train, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.departureTime !== undefined) {
      Timestamp.encode(toTimestamp(message.departureTime), writer.uint32(10).fork()).join();
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(18).fork()).join();
    }
    if (message.trainNumber !== "") {
      writer.uint32(26).string(message.trainNumber);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Train {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.departureTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.trainNumber = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Train {
    return {
      departureTime: isSet(object.departureTime) ? fromJsonTimestamp(object.departureTime) : undefined,
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
      trainNumber: isSet(object.trainNumber) ? globalThis.String(object.trainNumber) : "",
    };
  },

  toJSON(message: Train): unknown {
    const obj: any = {};
    if (message.departureTime !== undefined) {
      obj.departureTime = message.departureTime.toISOString();
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    if (message.trainNumber !== "") {
      obj.trainNumber = message.trainNumber;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Train>, I>>(base?: I): Train {
    return Train.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Train>, I>>(object: I): Train {
    const message = createBaseTrain();
    message.departureTime = object.departureTime ?? undefined;
    message.arrivalTime = object.arrivalTime ?? undefined;
    message.trainNumber = object.trainNumber ?? "";
    return message;
  },
};

function createBaseCarRental(): CarRental {
  return { company: "", pickupTime: undefined, dropoffTime: undefined, carType: "" };
}

export const CarRental: MessageFns<CarRental> = {
  encode(message: CarRental, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.company !== "") {
      writer.uint32(10).string(message.company);
    }
    if (message.pickupTime !== undefined) {
      Timestamp.encode(toTimestamp(message.pickupTime), writer.uint32(18).fork()).join();
    }
    if (message.dropoffTime !== undefined) {
      Timestamp.encode(toTimestamp(message.dropoffTime), writer.uint32(26).fork()).join();
    }
    if (message.carType !== "") {
      writer.uint32(34).string(message.carType);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CarRental {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCarRental();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.company = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pickupTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dropoffTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.carType = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CarRental {
    return {
      company: isSet(object.company) ? globalThis.String(object.company) : "",
      pickupTime: isSet(object.pickupTime) ? fromJsonTimestamp(object.pickupTime) : undefined,
      dropoffTime: isSet(object.dropoffTime) ? fromJsonTimestamp(object.dropoffTime) : undefined,
      carType: isSet(object.carType) ? globalThis.String(object.carType) : "",
    };
  },

  toJSON(message: CarRental): unknown {
    const obj: any = {};
    if (message.company !== "") {
      obj.company = message.company;
    }
    if (message.pickupTime !== undefined) {
      obj.pickupTime = message.pickupTime.toISOString();
    }
    if (message.dropoffTime !== undefined) {
      obj.dropoffTime = message.dropoffTime.toISOString();
    }
    if (message.carType !== "") {
      obj.carType = message.carType;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CarRental>, I>>(base?: I): CarRental {
    return CarRental.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CarRental>, I>>(object: I): CarRental {
    const message = createBaseCarRental();
    message.company = object.company ?? "";
    message.pickupTime = object.pickupTime ?? undefined;
    message.dropoffTime = object.dropoffTime ?? undefined;
    message.carType = object.carType ?? "";
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
