// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: protos/users.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "../google/protobuf/timestamp";
import { Itinerary } from "./graph";

export const protobufPackage = "travelingman";

export interface User {
  id: number;
  email: string;
  passwordHash: string;
  fullName: string;
  createdAt: Date | undefined;
  passports: Passport[];
  driversLicenses: DriversLicense[];
}

export interface Passport {
  id: number;
  userId: number;
  number: string;
  issuingCountry: string;
  expiryDate: Date | undefined;
}

export interface DriversLicense {
  id: number;
  userId: number;
  number: string;
  issuingCountry: string;
  expiryDate: Date | undefined;
}

export interface TravelGroup {
  groupId: number;
  name: string;
  organizerId: number;
  destination: string;
  travelDate: Date | undefined;
  members: User[];
  itinerary: Itinerary[];
}

function createBaseUser(): User {
  return { id: 0, email: "", passwordHash: "", fullName: "", createdAt: undefined, passports: [], driversLicenses: [] };
}

export const User: MessageFns<User> = {
  encode(message: User, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.passwordHash !== "") {
      writer.uint32(26).string(message.passwordHash);
    }
    if (message.fullName !== "") {
      writer.uint32(34).string(message.fullName);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(42).fork()).join();
    }
    for (const v of message.passports) {
      Passport.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.driversLicenses) {
      DriversLicense.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): User {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUser();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.passwordHash = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.fullName = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.passports.push(Passport.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.driversLicenses.push(DriversLicense.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): User {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      passwordHash: isSet(object.passwordHash) ? globalThis.String(object.passwordHash) : "",
      fullName: isSet(object.fullName) ? globalThis.String(object.fullName) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
      passports: globalThis.Array.isArray(object?.passports)
        ? object.passports.map((e: any) => Passport.fromJSON(e))
        : [],
      driversLicenses: globalThis.Array.isArray(object?.driversLicenses)
        ? object.driversLicenses.map((e: any) => DriversLicense.fromJSON(e))
        : [],
    };
  },

  toJSON(message: User): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.passwordHash !== "") {
      obj.passwordHash = message.passwordHash;
    }
    if (message.fullName !== "") {
      obj.fullName = message.fullName;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    if (message.passports?.length) {
      obj.passports = message.passports.map((e) => Passport.toJSON(e));
    }
    if (message.driversLicenses?.length) {
      obj.driversLicenses = message.driversLicenses.map((e) => DriversLicense.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<User>, I>>(base?: I): User {
    return User.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<User>, I>>(object: I): User {
    const message = createBaseUser();
    message.id = object.id ?? 0;
    message.email = object.email ?? "";
    message.passwordHash = object.passwordHash ?? "";
    message.fullName = object.fullName ?? "";
    message.createdAt = object.createdAt ?? undefined;
    message.passports = object.passports?.map((e) => Passport.fromPartial(e)) || [];
    message.driversLicenses = object.driversLicenses?.map((e) => DriversLicense.fromPartial(e)) || [];
    return message;
  },
};

function createBasePassport(): Passport {
  return { id: 0, userId: 0, number: "", issuingCountry: "", expiryDate: undefined };
}

export const Passport: MessageFns<Passport> = {
  encode(message: Passport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int64(message.userId);
    }
    if (message.number !== "") {
      writer.uint32(26).string(message.number);
    }
    if (message.issuingCountry !== "") {
      writer.uint32(34).string(message.issuingCountry);
    }
    if (message.expiryDate !== undefined) {
      Timestamp.encode(toTimestamp(message.expiryDate), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Passport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePassport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.number = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.issuingCountry = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.expiryDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Passport {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      number: isSet(object.number) ? globalThis.String(object.number) : "",
      issuingCountry: isSet(object.issuingCountry) ? globalThis.String(object.issuingCountry) : "",
      expiryDate: isSet(object.expiryDate) ? fromJsonTimestamp(object.expiryDate) : undefined,
    };
  },

  toJSON(message: Passport): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.number !== "") {
      obj.number = message.number;
    }
    if (message.issuingCountry !== "") {
      obj.issuingCountry = message.issuingCountry;
    }
    if (message.expiryDate !== undefined) {
      obj.expiryDate = message.expiryDate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Passport>, I>>(base?: I): Passport {
    return Passport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Passport>, I>>(object: I): Passport {
    const message = createBasePassport();
    message.id = object.id ?? 0;
    message.userId = object.userId ?? 0;
    message.number = object.number ?? "";
    message.issuingCountry = object.issuingCountry ?? "";
    message.expiryDate = object.expiryDate ?? undefined;
    return message;
  },
};

function createBaseDriversLicense(): DriversLicense {
  return { id: 0, userId: 0, number: "", issuingCountry: "", expiryDate: undefined };
}

export const DriversLicense: MessageFns<DriversLicense> = {
  encode(message: DriversLicense, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int64(message.userId);
    }
    if (message.number !== "") {
      writer.uint32(26).string(message.number);
    }
    if (message.issuingCountry !== "") {
      writer.uint32(34).string(message.issuingCountry);
    }
    if (message.expiryDate !== undefined) {
      Timestamp.encode(toTimestamp(message.expiryDate), writer.uint32(42).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DriversLicense {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDriversLicense();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.number = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.issuingCountry = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.expiryDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DriversLicense {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      number: isSet(object.number) ? globalThis.String(object.number) : "",
      issuingCountry: isSet(object.issuingCountry) ? globalThis.String(object.issuingCountry) : "",
      expiryDate: isSet(object.expiryDate) ? fromJsonTimestamp(object.expiryDate) : undefined,
    };
  },

  toJSON(message: DriversLicense): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.number !== "") {
      obj.number = message.number;
    }
    if (message.issuingCountry !== "") {
      obj.issuingCountry = message.issuingCountry;
    }
    if (message.expiryDate !== undefined) {
      obj.expiryDate = message.expiryDate.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DriversLicense>, I>>(base?: I): DriversLicense {
    return DriversLicense.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DriversLicense>, I>>(object: I): DriversLicense {
    const message = createBaseDriversLicense();
    message.id = object.id ?? 0;
    message.userId = object.userId ?? 0;
    message.number = object.number ?? "";
    message.issuingCountry = object.issuingCountry ?? "";
    message.expiryDate = object.expiryDate ?? undefined;
    return message;
  },
};

function createBaseTravelGroup(): TravelGroup {
  return { groupId: 0, name: "", organizerId: 0, destination: "", travelDate: undefined, members: [], itinerary: [] };
}

export const TravelGroup: MessageFns<TravelGroup> = {
  encode(message: TravelGroup, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.groupId !== 0) {
      writer.uint32(8).int64(message.groupId);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.organizerId !== 0) {
      writer.uint32(24).int64(message.organizerId);
    }
    if (message.destination !== "") {
      writer.uint32(34).string(message.destination);
    }
    if (message.travelDate !== undefined) {
      Timestamp.encode(toTimestamp(message.travelDate), writer.uint32(42).fork()).join();
    }
    for (const v of message.members) {
      User.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.itinerary) {
      Itinerary.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TravelGroup {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTravelGroup();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.organizerId = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.destination = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.travelDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.members.push(User.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.itinerary.push(Itinerary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TravelGroup {
    return {
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      organizerId: isSet(object.organizerId) ? globalThis.Number(object.organizerId) : 0,
      destination: isSet(object.destination) ? globalThis.String(object.destination) : "",
      travelDate: isSet(object.travelDate) ? fromJsonTimestamp(object.travelDate) : undefined,
      members: globalThis.Array.isArray(object?.members) ? object.members.map((e: any) => User.fromJSON(e)) : [],
      itinerary: globalThis.Array.isArray(object?.itinerary)
        ? object.itinerary.map((e: any) => Itinerary.fromJSON(e))
        : [],
    };
  },

  toJSON(message: TravelGroup): unknown {
    const obj: any = {};
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.organizerId !== 0) {
      obj.organizerId = Math.round(message.organizerId);
    }
    if (message.destination !== "") {
      obj.destination = message.destination;
    }
    if (message.travelDate !== undefined) {
      obj.travelDate = message.travelDate.toISOString();
    }
    if (message.members?.length) {
      obj.members = message.members.map((e) => User.toJSON(e));
    }
    if (message.itinerary?.length) {
      obj.itinerary = message.itinerary.map((e) => Itinerary.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TravelGroup>, I>>(base?: I): TravelGroup {
    return TravelGroup.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TravelGroup>, I>>(object: I): TravelGroup {
    const message = createBaseTravelGroup();
    message.groupId = object.groupId ?? 0;
    message.name = object.name ?? "";
    message.organizerId = object.organizerId ?? 0;
    message.destination = object.destination ?? "";
    message.travelDate = object.travelDate ?? undefined;
    message.members = object.members?.map((e) => User.fromPartial(e)) || [];
    message.itinerary = object.itinerary?.map((e) => Itinerary.fromPartial(e)) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
