// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: bookings.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingType int32

const (
	BookingType_BOOKING_TYPE_UNSPECIFIED BookingType = 0
	BookingType_BOOKING_TYPE_FLIGHT      BookingType = 1
	BookingType_BOOKING_TYPE_HOTEL       BookingType = 2
	BookingType_BOOKING_TYPE_CAR         BookingType = 3
	BookingType_BOOKING_TYPE_TRANSPORT   BookingType = 4
)

// Enum value maps for BookingType.
var (
	BookingType_name = map[int32]string{
		0: "BOOKING_TYPE_UNSPECIFIED",
		1: "BOOKING_TYPE_FLIGHT",
		2: "BOOKING_TYPE_HOTEL",
		3: "BOOKING_TYPE_CAR",
		4: "BOOKING_TYPE_TRANSPORT",
	}
	BookingType_value = map[string]int32{
		"BOOKING_TYPE_UNSPECIFIED": 0,
		"BOOKING_TYPE_FLIGHT":      1,
		"BOOKING_TYPE_HOTEL":       2,
		"BOOKING_TYPE_CAR":         3,
		"BOOKING_TYPE_TRANSPORT":   4,
	}
)

func (x BookingType) Enum() *BookingType {
	p := new(BookingType)
	*p = x
	return p
}

func (x BookingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingType) Descriptor() protoreflect.EnumDescriptor {
	return file_bookings_proto_enumTypes[0].Descriptor()
}

func (BookingType) Type() protoreflect.EnumType {
	return &file_bookings_proto_enumTypes[0]
}

func (x BookingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingType.Descriptor instead.
func (BookingType) EnumDescriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{0}
}

type Provider int32

const (
	Provider_PROVIDER_UNSPECIFIED Provider = 0
	Provider_PROVIDER_AMADEUS     Provider = 1
	Provider_PROVIDER_BOOKING_COM Provider = 2
	Provider_PROVIDER_MANUAL      Provider = 3
	Provider_PROVIDER_OTHER       Provider = 4
)

// Enum value maps for Provider.
var (
	Provider_name = map[int32]string{
		0: "PROVIDER_UNSPECIFIED",
		1: "PROVIDER_AMADEUS",
		2: "PROVIDER_BOOKING_COM",
		3: "PROVIDER_MANUAL",
		4: "PROVIDER_OTHER",
	}
	Provider_value = map[string]int32{
		"PROVIDER_UNSPECIFIED": 0,
		"PROVIDER_AMADEUS":     1,
		"PROVIDER_BOOKING_COM": 2,
		"PROVIDER_MANUAL":      3,
		"PROVIDER_OTHER":       4,
	}
)

func (x Provider) Enum() *Provider {
	p := new(Provider)
	*p = x
	return p
}

func (x Provider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Provider) Descriptor() protoreflect.EnumDescriptor {
	return file_bookings_proto_enumTypes[1].Descriptor()
}

func (Provider) Type() protoreflect.EnumType {
	return &file_bookings_proto_enumTypes[1]
}

func (x Provider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Provider.Descriptor instead.
func (Provider) EnumDescriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{1}
}

type FlightOffer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId          int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	AmadeusOfferId   string                 `protobuf:"bytes,3,opt,name=amadeus_offer_id,json=amadeusOfferId,proto3" json:"amadeus_offer_id,omitempty"`
	CarrierCode      string                 `protobuf:"bytes,4,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	FlightNumber     string                 `protobuf:"bytes,5,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	DepartureAirport string                 `protobuf:"bytes,6,opt,name=departure_airport,json=departureAirport,proto3" json:"departure_airport,omitempty"`
	ArrivalAirport   string                 `protobuf:"bytes,7,opt,name=arrival_airport,json=arrivalAirport,proto3" json:"arrival_airport,omitempty"`
	DepartureTime    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	PriceTotal       string                 `protobuf:"bytes,10,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	Currency         string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	RawData          string                 `protobuf:"bytes,12,opt,name=raw_data,json=rawData,proto3" json:"raw_data,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FlightOffer) Reset() {
	*x = FlightOffer{}
	mi := &file_bookings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightOffer) ProtoMessage() {}

func (x *FlightOffer) ProtoReflect() protoreflect.Message {
	mi := &file_bookings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightOffer.ProtoReflect.Descriptor instead.
func (*FlightOffer) Descriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{0}
}

func (x *FlightOffer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FlightOffer) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *FlightOffer) GetAmadeusOfferId() string {
	if x != nil {
		return x.AmadeusOfferId
	}
	return ""
}

func (x *FlightOffer) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *FlightOffer) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *FlightOffer) GetDepartureAirport() string {
	if x != nil {
		return x.DepartureAirport
	}
	return ""
}

func (x *FlightOffer) GetArrivalAirport() string {
	if x != nil {
		return x.ArrivalAirport
	}
	return ""
}

func (x *FlightOffer) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *FlightOffer) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *FlightOffer) GetPriceTotal() string {
	if x != nil {
		return x.PriceTotal
	}
	return ""
}

func (x *FlightOffer) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *FlightOffer) GetRawData() string {
	if x != nil {
		return x.RawData
	}
	return ""
}

type HotelOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	HotelName     string                 `protobuf:"bytes,3,opt,name=hotel_name,json=hotelName,proto3" json:"hotel_name,omitempty"`
	CheckIn       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	PriceTotal    string                 `protobuf:"bytes,6,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	OfferId       string                 `protobuf:"bytes,8,opt,name=offer_id,json=offerId,proto3" json:"offer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HotelOffer) Reset() {
	*x = HotelOffer{}
	mi := &file_bookings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HotelOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HotelOffer) ProtoMessage() {}

func (x *HotelOffer) ProtoReflect() protoreflect.Message {
	mi := &file_bookings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HotelOffer.ProtoReflect.Descriptor instead.
func (*HotelOffer) Descriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{1}
}

func (x *HotelOffer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HotelOffer) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *HotelOffer) GetHotelName() string {
	if x != nil {
		return x.HotelName
	}
	return ""
}

func (x *HotelOffer) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *HotelOffer) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *HotelOffer) GetPriceTotal() string {
	if x != nil {
		return x.PriceTotal
	}
	return ""
}

func (x *HotelOffer) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *HotelOffer) GetOfferId() string {
	if x != nil {
		return x.OfferId
	}
	return ""
}

type Booking struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                   int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type                     BookingType            `protobuf:"varint,3,opt,name=type,proto3,enum=travelingman.BookingType" json:"type,omitempty"`
	Provider                 Provider               `protobuf:"varint,4,opt,name=provider,proto3,enum=travelingman.Provider" json:"provider,omitempty"`
	Status                   string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ExternalBookingReference string                 `protobuf:"bytes,6,opt,name=external_booking_reference,json=externalBookingReference,proto3" json:"external_booking_reference,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_bookings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_bookings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{2}
}

func (x *Booking) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Booking) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Booking) GetType() BookingType {
	if x != nil {
		return x.Type
	}
	return BookingType_BOOKING_TYPE_UNSPECIFIED
}

func (x *Booking) GetProvider() Provider {
	if x != nil {
		return x.Provider
	}
	return Provider_PROVIDER_UNSPECIFIED
}

func (x *Booking) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Booking) GetExternalBookingReference() string {
	if x != nil {
		return x.ExternalBookingReference
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Payment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId     int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,7,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Payment) Reset() {
	*x = Payment{}
	mi := &file_bookings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_bookings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_bookings_proto_rawDescGZIP(), []int{3}
}

func (x *Payment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Payment) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Payment) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Payment) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Payment) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Payment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Payment) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Payment) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_bookings_proto protoreflect.FileDescriptor

const file_bookings_proto_rawDesc = "" +
	"\n" +
	"\x0ebookings.proto\x12\ftravelingman\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n" +
	"\vFlightOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12(\n" +
	"\x10amadeus_offer_id\x18\x03 \x01(\tR\x0eamadeusOfferId\x12!\n" +
	"\fcarrier_code\x18\x04 \x01(\tR\vcarrierCode\x12#\n" +
	"\rflight_number\x18\x05 \x01(\tR\fflightNumber\x12+\n" +
	"\x11departure_airport\x18\x06 \x01(\tR\x10departureAirport\x12'\n" +
	"\x0farrival_airport\x18\a \x01(\tR\x0earrivalAirport\x12A\n" +
	"\x0edeparture_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12=\n" +
	"\farrival_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12\x1f\n" +
	"\vprice_total\x18\n" +
	" \x01(\tR\n" +
	"priceTotal\x12\x1a\n" +
	"\bcurrency\x18\v \x01(\tR\bcurrency\x12\x19\n" +
	"\braw_data\x18\f \x01(\tR\arawData\"\x9e\x02\n" +
	"\n" +
	"HotelOffer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"hotel_name\x18\x03 \x01(\tR\thotelName\x125\n" +
	"\bcheck_in\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x1f\n" +
	"\vprice_total\x18\x06 \x01(\tR\n" +
	"priceTotal\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x19\n" +
	"\boffer_id\x18\b \x01(\tR\aofferId\"\xa6\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12-\n" +
	"\x04type\x18\x03 \x01(\x0e2\x19.travelingman.BookingTypeR\x04type\x122\n" +
	"\bprovider\x18\x04 \x01(\x0e2\x16.travelingman.ProviderR\bprovider\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12<\n" +
	"\x1aexternal_booking_reference\x18\x06 \x01(\tR\x18externalBookingReference\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xff\x01\n" +
	"\aPayment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0etransaction_id\x18\a \x01(\tR\rtransactionId\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*\x8e\x01\n" +
	"\vBookingType\x12\x1c\n" +
	"\x18BOOKING_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13BOOKING_TYPE_FLIGHT\x10\x01\x12\x16\n" +
	"\x12BOOKING_TYPE_HOTEL\x10\x02\x12\x14\n" +
	"\x10BOOKING_TYPE_CAR\x10\x03\x12\x1a\n" +
	"\x16BOOKING_TYPE_TRANSPORT\x10\x04*}\n" +
	"\bProvider\x12\x18\n" +
	"\x14PROVIDER_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PROVIDER_AMADEUS\x10\x01\x12\x18\n" +
	"\x14PROVIDER_BOOKING_COM\x10\x02\x12\x13\n" +
	"\x0fPROVIDER_MANUAL\x10\x03\x12\x12\n" +
	"\x0ePROVIDER_OTHER\x10\x04B\x1dZ\x1bexample.com/travelingman/pbb\x06proto3"

var (
	file_bookings_proto_rawDescOnce sync.Once
	file_bookings_proto_rawDescData []byte
)

func file_bookings_proto_rawDescGZIP() []byte {
	file_bookings_proto_rawDescOnce.Do(func() {
		file_bookings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bookings_proto_rawDesc), len(file_bookings_proto_rawDesc)))
	})
	return file_bookings_proto_rawDescData
}

var file_bookings_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_bookings_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_bookings_proto_goTypes = []any{
	(BookingType)(0),              // 0: travelingman.BookingType
	(Provider)(0),                 // 1: travelingman.Provider
	(*FlightOffer)(nil),           // 2: travelingman.FlightOffer
	(*HotelOffer)(nil),            // 3: travelingman.HotelOffer
	(*Booking)(nil),               // 4: travelingman.Booking
	(*Payment)(nil),               // 5: travelingman.Payment
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_bookings_proto_depIdxs = []int32{
	6, // 0: travelingman.FlightOffer.departure_time:type_name -> google.protobuf.Timestamp
	6, // 1: travelingman.FlightOffer.arrival_time:type_name -> google.protobuf.Timestamp
	6, // 2: travelingman.HotelOffer.check_in:type_name -> google.protobuf.Timestamp
	6, // 3: travelingman.HotelOffer.check_out:type_name -> google.protobuf.Timestamp
	0, // 4: travelingman.Booking.type:type_name -> travelingman.BookingType
	1, // 5: travelingman.Booking.provider:type_name -> travelingman.Provider
	6, // 6: travelingman.Booking.created_at:type_name -> google.protobuf.Timestamp
	6, // 7: travelingman.Payment.created_at:type_name -> google.protobuf.Timestamp
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_bookings_proto_init() }
func file_bookings_proto_init() {
	if File_bookings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bookings_proto_rawDesc), len(file_bookings_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bookings_proto_goTypes,
		DependencyIndexes: file_bookings_proto_depIdxs,
		EnumInfos:         file_bookings_proto_enumTypes,
		MessageInfos:      file_bookings_proto_msgTypes,
	}.Build()
	File_bookings_proto = out.File
	file_bookings_proto_goTypes = nil
	file_bookings_proto_depIdxs = nil
}
