// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: graph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Node represents a location/place in the itinerary graph
// It maps to protobuf structures: TripDay, Place, Accommodation
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Unique identifier for the node
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`                                // Location from TripDay.location, Place.name/address, or Accommodation.name/address
	FromTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"` // When user arrives at this location (from incoming edge or TripDay.date/Place.visit_time)
	ToTimestamp   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`       // When user departs from this location (from outgoing edge or Accommodation.check_out)
	Stay          *Accommodation         `protobuf:"bytes,5,opt,name=stay,proto3" json:"stay,omitempty"`                                        // Hotel/accommodation info (from Accommodation) - contains full struct, no need for ID
	IsInterCity   bool                   `protobuf:"varint,6,opt,name=is_inter_city,json=isInterCity,proto3" json:"is_inter_city,omitempty"`    // True if this is an inter-city node
	SubGraph      *Graph                 `protobuf:"bytes,7,opt,name=sub_graph,json=subGraph,proto3" json:"sub_graph,omitempty"`                // For intra-city details (contains Places)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Node) GetFromTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTimestamp
	}
	return nil
}

func (x *Node) GetToTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTimestamp
	}
	return nil
}

func (x *Node) GetStay() *Accommodation {
	if x != nil {
		return x.Stay
	}
	return nil
}

func (x *Node) GetIsInterCity() bool {
	if x != nil {
		return x.IsInterCity
	}
	return false
}

func (x *Node) GetSubGraph() *Graph {
	if x != nil {
		return x.SubGraph
	}
	return nil
}

// Edge represents transportation between two locations
// It maps to protobuf structures: Transport
type Edge struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromId          string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                             // ID of the source node
	ToId            string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                                   // ID of the destination node
	DurationSeconds int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Duration in seconds (calculated from departure_time and arrival_time)
	Transport       *Transport             `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`                                     // Full Transport struct from Transport
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Edge) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

// Graph represents the complete graph structure of a user's itinerary
type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // List of nodes in the graph
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"` // List of edges in the graph
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_graph_proto protoreflect.FileDescriptor

const file_graph_proto_rawDesc = "" +
	"\n" +
	"\vgraph.proto\x12\ftravelingman\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0fitinerary.proto\"\xbb\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12A\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rfromTimestamp\x12=\n" +
	"\fto_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtoTimestamp\x12/\n" +
	"\x04stay\x18\x05 \x01(\v2\x1b.travelingman.AccommodationR\x04stay\x12\"\n" +
	"\ris_inter_city\x18\x06 \x01(\bR\visInterCity\x120\n" +
	"\tsub_graph\x18\a \x01(\v2\x13.travelingman.GraphR\bsubGraph\"\x96\x01\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x125\n" +
	"\ttransport\x18\x04 \x01(\v2\x17.travelingman.TransportR\ttransport\"[\n" +
	"\x05Graph\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.travelingman.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x02 \x03(\v2\x12.travelingman.EdgeR\x05edgesB\x1dZ\x1bexample.com/travelingman/pbb\x06proto3"

var (
	file_graph_proto_rawDescOnce sync.Once
	file_graph_proto_rawDescData []byte
)

func file_graph_proto_rawDescGZIP() []byte {
	file_graph_proto_rawDescOnce.Do(func() {
		file_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)))
	})
	return file_graph_proto_rawDescData
}

var file_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_graph_proto_goTypes = []any{
	(*Node)(nil),                  // 0: travelingman.Node
	(*Edge)(nil),                  // 1: travelingman.Edge
	(*Graph)(nil),                 // 2: travelingman.Graph
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
	(*Accommodation)(nil),         // 4: travelingman.Accommodation
	(*Transport)(nil),             // 5: travelingman.Transport
}
var file_graph_proto_depIdxs = []int32{
	3, // 0: travelingman.Node.from_timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: travelingman.Node.to_timestamp:type_name -> google.protobuf.Timestamp
	4, // 2: travelingman.Node.stay:type_name -> travelingman.Accommodation
	2, // 3: travelingman.Node.sub_graph:type_name -> travelingman.Graph
	5, // 4: travelingman.Edge.transport:type_name -> travelingman.Transport
	0, // 5: travelingman.Graph.nodes:type_name -> travelingman.Node
	1, // 6: travelingman.Graph.edges:type_name -> travelingman.Edge
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_graph_proto_init() }
func file_graph_proto_init() {
	if File_graph_proto != nil {
		return
	}
	file_itinerary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_graph_proto_rawDesc), len(file_graph_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_graph_proto_goTypes,
		DependencyIndexes: file_graph_proto_depIdxs,
		MessageInfos:      file_graph_proto_msgTypes,
	}.Build()
	File_graph_proto = out.File
	file_graph_proto_goTypes = nil
	file_graph_proto_depIdxs = nil
}
