// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: protos/graph.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JourneyType int32

const (
	JourneyType_JOURNEY_TYPE_UNSPECIFIED JourneyType = 0
	JourneyType_JOURNEY_TYPE_ONE_WAY     JourneyType = 1
	JourneyType_JOURNEY_TYPE_RETURN      JourneyType = 2
	JourneyType_JOURNEY_TYPE_MULTI_CITY  JourneyType = 3
	JourneyType_JOURNEY_TYPE_OPEN_JAW    JourneyType = 4
	JourneyType_JOURNEY_TYPE_CIRCLE_TRIP JourneyType = 5
)

// Enum value maps for JourneyType.
var (
	JourneyType_name = map[int32]string{
		0: "JOURNEY_TYPE_UNSPECIFIED",
		1: "JOURNEY_TYPE_ONE_WAY",
		2: "JOURNEY_TYPE_RETURN",
		3: "JOURNEY_TYPE_MULTI_CITY",
		4: "JOURNEY_TYPE_OPEN_JAW",
		5: "JOURNEY_TYPE_CIRCLE_TRIP",
	}
	JourneyType_value = map[string]int32{
		"JOURNEY_TYPE_UNSPECIFIED": 0,
		"JOURNEY_TYPE_ONE_WAY":     1,
		"JOURNEY_TYPE_RETURN":      2,
		"JOURNEY_TYPE_MULTI_CITY":  3,
		"JOURNEY_TYPE_OPEN_JAW":    4,
		"JOURNEY_TYPE_CIRCLE_TRIP": 5,
	}
)

func (x JourneyType) Enum() *JourneyType {
	p := new(JourneyType)
	*p = x
	return p
}

func (x JourneyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JourneyType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_graph_proto_enumTypes[0].Descriptor()
}

func (JourneyType) Type() protoreflect.EnumType {
	return &file_protos_graph_proto_enumTypes[0]
}

func (x JourneyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JourneyType.Descriptor instead.
func (JourneyType) EnumDescriptor() ([]byte, []int) {
	return file_protos_graph_proto_rawDescGZIP(), []int{0}
}

// Node represents a location/place in the itinerary graph
// It maps to protobuf structures: TripDay, Place, Accommodation
type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // Unique identifier for the node
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`                                // Name or address of the location
	FromTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=from_timestamp,json=fromTimestamp,proto3" json:"from_timestamp,omitempty"` // Arrival time at this node
	ToTimestamp   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=to_timestamp,json=toTimestamp,proto3" json:"to_timestamp,omitempty"`       // Departure time from this node
	IsInterCity   bool                   `protobuf:"varint,5,opt,name=is_inter_city,json=isInterCity,proto3" json:"is_inter_city,omitempty"`    // Whether this node represents an inter-city travel point
	Stay          *Accommodation         `protobuf:"bytes,6,opt,name=stay,proto3" json:"stay,omitempty"`                                        // Hotel/accommodation info (from Accommodation)
	StayOptions   []*Accommodation       `protobuf:"bytes,7,rep,name=stayOptions,proto3" json:"stayOptions,omitempty"`                          // List of possible accommodations
	SubGraph      *Graph                 `protobuf:"bytes,8,opt,name=sub_graph,json=subGraph,proto3" json:"sub_graph,omitempty"`                // Sub-graph for daily activities
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_protos_graph_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_protos_graph_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Node) GetFromTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTimestamp
	}
	return nil
}

func (x *Node) GetToTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTimestamp
	}
	return nil
}

func (x *Node) GetIsInterCity() bool {
	if x != nil {
		return x.IsInterCity
	}
	return false
}

func (x *Node) GetStay() *Accommodation {
	if x != nil {
		return x.Stay
	}
	return nil
}

func (x *Node) GetStayOptions() []*Accommodation {
	if x != nil {
		return x.StayOptions
	}
	return nil
}

func (x *Node) GetSubGraph() *Graph {
	if x != nil {
		return x.SubGraph
	}
	return nil
}

// Edge represents transportation between two locations
// It maps to protobuf structures: Transport
type Edge struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FromId           string                 `protobuf:"bytes,1,opt,name=from_id,json=fromId,proto3" json:"from_id,omitempty"`                             // ID of the source node
	ToId             string                 `protobuf:"bytes,2,opt,name=to_id,json=toId,proto3" json:"to_id,omitempty"`                                   // ID of the destination node
	DurationSeconds  int64                  `protobuf:"varint,3,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"` // Duration of travel in seconds
	Transport        *Transport             `protobuf:"bytes,4,opt,name=transport,proto3" json:"transport,omitempty"`                                     // Full Transport struct from Transport
	TransportOptions []*Transport           `protobuf:"bytes,5,rep,name=transportOptions,proto3" json:"transportOptions,omitempty"`                       // List of possible transports
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_protos_graph_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_protos_graph_proto_rawDescGZIP(), []int{1}
}

func (x *Edge) GetFromId() string {
	if x != nil {
		return x.FromId
	}
	return ""
}

func (x *Edge) GetToId() string {
	if x != nil {
		return x.ToId
	}
	return ""
}

func (x *Edge) GetDurationSeconds() int64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *Edge) GetTransport() *Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Edge) GetTransportOptions() []*Transport {
	if x != nil {
		return x.TransportOptions
	}
	return nil
}

// Graph represents the complete graph structure of a user's itinerary
type Graph struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`                       // List of nodes in the graph
	Edges         []*Edge                `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`                       // List of edges in the graph
	SubGraph      *Graph                 `protobuf:"bytes,3,opt,name=sub_graph,json=subGraph,proto3" json:"sub_graph,omitempty"` // For intra-city details (contains Places)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Graph) Reset() {
	*x = Graph{}
	mi := &file_protos_graph_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Graph) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Graph) ProtoMessage() {}

func (x *Graph) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Graph.ProtoReflect.Descriptor instead.
func (*Graph) Descriptor() ([]byte, []int) {
	return file_protos_graph_proto_rawDescGZIP(), []int{2}
}

func (x *Graph) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Graph) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *Graph) GetSubGraph() *Graph {
	if x != nil {
		return x.SubGraph
	}
	return nil
}

type Itinerary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DayNumber     int32                  `protobuf:"varint,3,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Title         string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Graph         *Graph                 `protobuf:"bytes,8,opt,name=graph,proto3" json:"graph,omitempty"`
	Travelers     int32                  `protobuf:"varint,9,opt,name=travelers,proto3" json:"travelers,omitempty"`
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	JourneyType   JourneyType            `protobuf:"varint,11,opt,name=journey_type,json=journeyType,proto3,enum=travelingman.JourneyType" json:"journey_type,omitempty"`
	Error         *Error                 `protobuf:"bytes,12,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Itinerary) Reset() {
	*x = Itinerary{}
	mi := &file_protos_graph_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Itinerary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Itinerary) ProtoMessage() {}

func (x *Itinerary) ProtoReflect() protoreflect.Message {
	mi := &file_protos_graph_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Itinerary.ProtoReflect.Descriptor instead.
func (*Itinerary) Descriptor() ([]byte, []int) {
	return file_protos_graph_proto_rawDescGZIP(), []int{3}
}

func (x *Itinerary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Itinerary) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Itinerary) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

func (x *Itinerary) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Itinerary) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Itinerary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Itinerary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Itinerary) GetGraph() *Graph {
	if x != nil {
		return x.Graph
	}
	return nil
}

func (x *Itinerary) GetTravelers() int32 {
	if x != nil {
		return x.Travelers
	}
	return 0
}

func (x *Itinerary) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Itinerary) GetJourneyType() JourneyType {
	if x != nil {
		return x.JourneyType
	}
	return JourneyType_JOURNEY_TYPE_UNSPECIFIED
}

func (x *Itinerary) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_protos_graph_proto protoreflect.FileDescriptor

const file_protos_graph_proto_rawDesc = "" +
	"\n" +
	"\x12protos/graph.proto\x12\ftravelingman\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x16protos/itinerary.proto\"\xfa\x02\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12A\n" +
	"\x0efrom_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rfromTimestamp\x12=\n" +
	"\fto_timestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vtoTimestamp\x12\"\n" +
	"\ris_inter_city\x18\x05 \x01(\bR\visInterCity\x12/\n" +
	"\x04stay\x18\x06 \x01(\v2\x1b.travelingman.AccommodationR\x04stay\x12=\n" +
	"\vstayOptions\x18\a \x03(\v2\x1b.travelingman.AccommodationR\vstayOptions\x120\n" +
	"\tsub_graph\x18\b \x01(\v2\x13.travelingman.GraphR\bsubGraph\"\xdb\x01\n" +
	"\x04Edge\x12\x17\n" +
	"\afrom_id\x18\x01 \x01(\tR\x06fromId\x12\x13\n" +
	"\x05to_id\x18\x02 \x01(\tR\x04toId\x12)\n" +
	"\x10duration_seconds\x18\x03 \x01(\x03R\x0fdurationSeconds\x125\n" +
	"\ttransport\x18\x04 \x01(\v2\x17.travelingman.TransportR\ttransport\x12C\n" +
	"\x10transportOptions\x18\x05 \x03(\v2\x17.travelingman.TransportR\x10transportOptions\"\x8d\x01\n" +
	"\x05Graph\x12(\n" +
	"\x05nodes\x18\x01 \x03(\v2\x12.travelingman.NodeR\x05nodes\x12(\n" +
	"\x05edges\x18\x02 \x03(\v2\x12.travelingman.EdgeR\x05edges\x120\n" +
	"\tsub_graph\x18\x03 \x01(\v2\x13.travelingman.GraphR\bsubGraph\"\xc5\x03\n" +
	"\tItinerary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"day_number\x18\x03 \x01(\x05R\tdayNumber\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12)\n" +
	"\x05graph\x18\b \x01(\v2\x13.travelingman.GraphR\x05graph\x12\x1c\n" +
	"\ttravelers\x18\t \x01(\x05R\ttravelers\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12<\n" +
	"\fjourney_type\x18\v \x01(\x0e2\x19.travelingman.JourneyTypeR\vjourneyType\x12)\n" +
	"\x05error\x18\f \x01(\v2\x13.travelingman.ErrorR\x05error*\xb4\x01\n" +
	"\vJourneyType\x12\x1c\n" +
	"\x18JOURNEY_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14JOURNEY_TYPE_ONE_WAY\x10\x01\x12\x17\n" +
	"\x13JOURNEY_TYPE_RETURN\x10\x02\x12\x1b\n" +
	"\x17JOURNEY_TYPE_MULTI_CITY\x10\x03\x12\x19\n" +
	"\x15JOURNEY_TYPE_OPEN_JAW\x10\x04\x12\x1c\n" +
	"\x18JOURNEY_TYPE_CIRCLE_TRIP\x10\x05B#Z!github.com/va6996/travelingman/pbb\x06proto3"

var (
	file_protos_graph_proto_rawDescOnce sync.Once
	file_protos_graph_proto_rawDescData []byte
)

func file_protos_graph_proto_rawDescGZIP() []byte {
	file_protos_graph_proto_rawDescOnce.Do(func() {
		file_protos_graph_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_graph_proto_rawDesc), len(file_protos_graph_proto_rawDesc)))
	})
	return file_protos_graph_proto_rawDescData
}

var file_protos_graph_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_graph_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_graph_proto_goTypes = []any{
	(JourneyType)(0),              // 0: travelingman.JourneyType
	(*Node)(nil),                  // 1: travelingman.Node
	(*Edge)(nil),                  // 2: travelingman.Edge
	(*Graph)(nil),                 // 3: travelingman.Graph
	(*Itinerary)(nil),             // 4: travelingman.Itinerary
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
	(*Accommodation)(nil),         // 6: travelingman.Accommodation
	(*Transport)(nil),             // 7: travelingman.Transport
	(*Error)(nil),                 // 8: travelingman.Error
}
var file_protos_graph_proto_depIdxs = []int32{
	5,  // 0: travelingman.Node.from_timestamp:type_name -> google.protobuf.Timestamp
	5,  // 1: travelingman.Node.to_timestamp:type_name -> google.protobuf.Timestamp
	6,  // 2: travelingman.Node.stay:type_name -> travelingman.Accommodation
	6,  // 3: travelingman.Node.stayOptions:type_name -> travelingman.Accommodation
	3,  // 4: travelingman.Node.sub_graph:type_name -> travelingman.Graph
	7,  // 5: travelingman.Edge.transport:type_name -> travelingman.Transport
	7,  // 6: travelingman.Edge.transportOptions:type_name -> travelingman.Transport
	1,  // 7: travelingman.Graph.nodes:type_name -> travelingman.Node
	2,  // 8: travelingman.Graph.edges:type_name -> travelingman.Edge
	3,  // 9: travelingman.Graph.sub_graph:type_name -> travelingman.Graph
	5,  // 10: travelingman.Itinerary.start_time:type_name -> google.protobuf.Timestamp
	5,  // 11: travelingman.Itinerary.end_time:type_name -> google.protobuf.Timestamp
	3,  // 12: travelingman.Itinerary.graph:type_name -> travelingman.Graph
	0,  // 13: travelingman.Itinerary.journey_type:type_name -> travelingman.JourneyType
	8,  // 14: travelingman.Itinerary.error:type_name -> travelingman.Error
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_protos_graph_proto_init() }
func file_protos_graph_proto_init() {
	if File_protos_graph_proto != nil {
		return
	}
	file_protos_itinerary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_graph_proto_rawDesc), len(file_protos_graph_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_graph_proto_goTypes,
		DependencyIndexes: file_protos_graph_proto_depIdxs,
		EnumInfos:         file_protos_graph_proto_enumTypes,
		MessageInfos:      file_protos_graph_proto_msgTypes,
	}.Build()
	File_protos_graph_proto = out.File
	file_protos_graph_proto_goTypes = nil
	file_protos_graph_proto_depIdxs = nil
}
