// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: itinerary.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ItineraryType int32

const (
	ItineraryType_ITINERARY_TYPE_UNSPECIFIED ItineraryType = 0
	ItineraryType_ITINERARY_TYPE_TRANSPORT   ItineraryType = 1
	ItineraryType_ITINERARY_TYPE_HOTEL       ItineraryType = 2
	ItineraryType_ITINERARY_TYPE_EVENT       ItineraryType = 3
	ItineraryType_ITINERARY_TYPE_DAY_PLAN    ItineraryType = 4
)

// Enum value maps for ItineraryType.
var (
	ItineraryType_name = map[int32]string{
		0: "ITINERARY_TYPE_UNSPECIFIED",
		1: "ITINERARY_TYPE_TRANSPORT",
		2: "ITINERARY_TYPE_HOTEL",
		3: "ITINERARY_TYPE_EVENT",
		4: "ITINERARY_TYPE_DAY_PLAN",
	}
	ItineraryType_value = map[string]int32{
		"ITINERARY_TYPE_UNSPECIFIED": 0,
		"ITINERARY_TYPE_TRANSPORT":   1,
		"ITINERARY_TYPE_HOTEL":       2,
		"ITINERARY_TYPE_EVENT":       3,
		"ITINERARY_TYPE_DAY_PLAN":    4,
	}
)

func (x ItineraryType) Enum() *ItineraryType {
	p := new(ItineraryType)
	*p = x
	return p
}

func (x ItineraryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ItineraryType) Descriptor() protoreflect.EnumDescriptor {
	return file_itinerary_proto_enumTypes[0].Descriptor()
}

func (ItineraryType) Type() protoreflect.EnumType {
	return &file_itinerary_proto_enumTypes[0]
}

func (x ItineraryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ItineraryType.Descriptor instead.
func (ItineraryType) EnumDescriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{0}
}

type TransportType int32

const (
	TransportType_TRANSPORT_TYPE_UNSPECIFIED TransportType = 0
	TransportType_TRANSPORT_TYPE_FLIGHT      TransportType = 1
	TransportType_TRANSPORT_TYPE_TRAIN       TransportType = 2
	TransportType_TRANSPORT_TYPE_CAR         TransportType = 3
	TransportType_TRANSPORT_TYPE_WALKING     TransportType = 4
)

// Enum value maps for TransportType.
var (
	TransportType_name = map[int32]string{
		0: "TRANSPORT_TYPE_UNSPECIFIED",
		1: "TRANSPORT_TYPE_FLIGHT",
		2: "TRANSPORT_TYPE_TRAIN",
		3: "TRANSPORT_TYPE_CAR",
		4: "TRANSPORT_TYPE_WALKING",
	}
	TransportType_value = map[string]int32{
		"TRANSPORT_TYPE_UNSPECIFIED": 0,
		"TRANSPORT_TYPE_FLIGHT":      1,
		"TRANSPORT_TYPE_TRAIN":       2,
		"TRANSPORT_TYPE_CAR":         3,
		"TRANSPORT_TYPE_WALKING":     4,
	}
)

func (x TransportType) Enum() *TransportType {
	p := new(TransportType)
	*p = x
	return p
}

func (x TransportType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportType) Descriptor() protoreflect.EnumDescriptor {
	return file_itinerary_proto_enumTypes[1].Descriptor()
}

func (TransportType) Type() protoreflect.EnumType {
	return &file_itinerary_proto_enumTypes[1]
}

func (x TransportType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransportType.Descriptor instead.
func (TransportType) EnumDescriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{1}
}

type Itinerary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	DayNumber     int32                  `protobuf:"varint,3,opt,name=day_number,json=dayNumber,proto3" json:"day_number,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Type          ItineraryType          `protobuf:"varint,6,opt,name=type,proto3,enum=travelingman.ItineraryType" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Transport     []*Transport           `protobuf:"bytes,11,rep,name=transport,proto3" json:"transport,omitempty"`
	Accommodation []*Accommodation       `protobuf:"bytes,12,rep,name=accommodation,proto3" json:"accommodation,omitempty"`
	Itineraries   []*Itinerary           `protobuf:"bytes,13,rep,name=itineraries,proto3" json:"itineraries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Itinerary) Reset() {
	*x = Itinerary{}
	mi := &file_itinerary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Itinerary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Itinerary) ProtoMessage() {}

func (x *Itinerary) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Itinerary.ProtoReflect.Descriptor instead.
func (*Itinerary) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{0}
}

func (x *Itinerary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Itinerary) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Itinerary) GetDayNumber() int32 {
	if x != nil {
		return x.DayNumber
	}
	return 0
}

func (x *Itinerary) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Itinerary) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Itinerary) GetType() ItineraryType {
	if x != nil {
		return x.Type
	}
	return ItineraryType_ITINERARY_TYPE_UNSPECIFIED
}

func (x *Itinerary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Itinerary) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Itinerary) GetTransport() []*Transport {
	if x != nil {
		return x.Transport
	}
	return nil
}

func (x *Itinerary) GetAccommodation() []*Accommodation {
	if x != nil {
		return x.Accommodation
	}
	return nil
}

func (x *Itinerary) GetItineraries() []*Itinerary {
	if x != nil {
		return x.Itineraries
	}
	return nil
}

type Accommodation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId          int64                  `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Address          string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	CheckIn          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=check_in,json=checkIn,proto3" json:"check_in,omitempty"`
	CheckOut         *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=check_out,json=checkOut,proto3" json:"check_out,omitempty"`
	PriceTotal       string                 `protobuf:"bytes,7,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	BookingReference string                 `protobuf:"bytes,8,opt,name=booking_reference,json=bookingReference,proto3" json:"booking_reference,omitempty"`
	Status           string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	UserIds          []int64                `protobuf:"varint,10,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Accommodation) Reset() {
	*x = Accommodation{}
	mi := &file_itinerary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accommodation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accommodation) ProtoMessage() {}

func (x *Accommodation) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accommodation.ProtoReflect.Descriptor instead.
func (*Accommodation) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{1}
}

func (x *Accommodation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Accommodation) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *Accommodation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Accommodation) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Accommodation) GetCheckIn() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckIn
	}
	return nil
}

func (x *Accommodation) GetCheckOut() *timestamppb.Timestamp {
	if x != nil {
		return x.CheckOut
	}
	return nil
}

func (x *Accommodation) GetPriceTotal() string {
	if x != nil {
		return x.PriceTotal
	}
	return ""
}

func (x *Accommodation) GetBookingReference() string {
	if x != nil {
		return x.BookingReference
	}
	return ""
}

func (x *Accommodation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Accommodation) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Transport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BookingId       int64                  `protobuf:"varint,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	Provider        string                 `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ReferenceNumber string                 `protobuf:"bytes,4,opt,name=reference_number,json=referenceNumber,proto3" json:"reference_number,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Type            TransportType          `protobuf:"varint,6,opt,name=type,proto3,enum=travelingman.TransportType" json:"type,omitempty"`
	// Types that are valid to be assigned to Details:
	//
	//	*Transport_Flight
	//	*Transport_Train
	//	*Transport_CarRental
	Details       isTransport_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transport) Reset() {
	*x = Transport{}
	mi := &file_itinerary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transport) ProtoMessage() {}

func (x *Transport) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transport.ProtoReflect.Descriptor instead.
func (*Transport) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{2}
}

func (x *Transport) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transport) GetBookingId() int64 {
	if x != nil {
		return x.BookingId
	}
	return 0
}

func (x *Transport) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *Transport) GetReferenceNumber() string {
	if x != nil {
		return x.ReferenceNumber
	}
	return ""
}

func (x *Transport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transport) GetType() TransportType {
	if x != nil {
		return x.Type
	}
	return TransportType_TRANSPORT_TYPE_UNSPECIFIED
}

func (x *Transport) GetDetails() isTransport_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Transport) GetFlight() *Flight {
	if x != nil {
		if x, ok := x.Details.(*Transport_Flight); ok {
			return x.Flight
		}
	}
	return nil
}

func (x *Transport) GetTrain() *Train {
	if x != nil {
		if x, ok := x.Details.(*Transport_Train); ok {
			return x.Train
		}
	}
	return nil
}

func (x *Transport) GetCarRental() *CarRental {
	if x != nil {
		if x, ok := x.Details.(*Transport_CarRental); ok {
			return x.CarRental
		}
	}
	return nil
}

type isTransport_Details interface {
	isTransport_Details()
}

type Transport_Flight struct {
	Flight *Flight `protobuf:"bytes,10,opt,name=flight,proto3,oneof"`
}

type Transport_Train struct {
	Train *Train `protobuf:"bytes,11,opt,name=train,proto3,oneof"`
}

type Transport_CarRental struct {
	CarRental *CarRental `protobuf:"bytes,12,opt,name=car_rental,json=carRental,proto3,oneof"`
}

func (*Transport_Flight) isTransport_Details() {}

func (*Transport_Train) isTransport_Details() {}

func (*Transport_CarRental) isTransport_Details() {}

type Flight struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CarrierCode      string                 `protobuf:"bytes,1,opt,name=carrier_code,json=carrierCode,proto3" json:"carrier_code,omitempty"`
	FlightNumber     string                 `protobuf:"bytes,2,opt,name=flight_number,json=flightNumber,proto3" json:"flight_number,omitempty"`
	DepartureAirport string                 `protobuf:"bytes,3,opt,name=departure_airport,json=departureAirport,proto3" json:"departure_airport,omitempty"`
	ArrivalAirport   string                 `protobuf:"bytes,4,opt,name=arrival_airport,json=arrivalAirport,proto3" json:"arrival_airport,omitempty"`
	DepartureTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	UserIds          []int64                `protobuf:"varint,7,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Flight) Reset() {
	*x = Flight{}
	mi := &file_itinerary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flight) ProtoMessage() {}

func (x *Flight) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flight.ProtoReflect.Descriptor instead.
func (*Flight) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{3}
}

func (x *Flight) GetCarrierCode() string {
	if x != nil {
		return x.CarrierCode
	}
	return ""
}

func (x *Flight) GetFlightNumber() string {
	if x != nil {
		return x.FlightNumber
	}
	return ""
}

func (x *Flight) GetDepartureAirport() string {
	if x != nil {
		return x.DepartureAirport
	}
	return ""
}

func (x *Flight) GetArrivalAirport() string {
	if x != nil {
		return x.ArrivalAirport
	}
	return ""
}

func (x *Flight) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *Flight) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *Flight) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Train struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DepartureStation string                 `protobuf:"bytes,1,opt,name=departure_station,json=departureStation,proto3" json:"departure_station,omitempty"`
	ArrivalStation   string                 `protobuf:"bytes,2,opt,name=arrival_station,json=arrivalStation,proto3" json:"arrival_station,omitempty"`
	DepartureTime    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=departure_time,json=departureTime,proto3" json:"departure_time,omitempty"`
	ArrivalTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=arrival_time,json=arrivalTime,proto3" json:"arrival_time,omitempty"`
	TrainNumber      string                 `protobuf:"bytes,5,opt,name=train_number,json=trainNumber,proto3" json:"train_number,omitempty"`
	UserIds          []int64                `protobuf:"varint,6,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Train) Reset() {
	*x = Train{}
	mi := &file_itinerary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Train) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Train) ProtoMessage() {}

func (x *Train) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Train.ProtoReflect.Descriptor instead.
func (*Train) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{4}
}

func (x *Train) GetDepartureStation() string {
	if x != nil {
		return x.DepartureStation
	}
	return ""
}

func (x *Train) GetArrivalStation() string {
	if x != nil {
		return x.ArrivalStation
	}
	return ""
}

func (x *Train) GetDepartureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DepartureTime
	}
	return nil
}

func (x *Train) GetArrivalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ArrivalTime
	}
	return nil
}

func (x *Train) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

func (x *Train) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CarRental struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Company         string                 `protobuf:"bytes,1,opt,name=company,proto3" json:"company,omitempty"`
	PickupLocation  string                 `protobuf:"bytes,2,opt,name=pickup_location,json=pickupLocation,proto3" json:"pickup_location,omitempty"`
	DropoffLocation string                 `protobuf:"bytes,3,opt,name=dropoff_location,json=dropoffLocation,proto3" json:"dropoff_location,omitempty"`
	PickupTime      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=pickup_time,json=pickupTime,proto3" json:"pickup_time,omitempty"`
	DropoffTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dropoff_time,json=dropoffTime,proto3" json:"dropoff_time,omitempty"`
	CarType         string                 `protobuf:"bytes,6,opt,name=car_type,json=carType,proto3" json:"car_type,omitempty"`
	PriceTotal      string                 `protobuf:"bytes,7,opt,name=price_total,json=priceTotal,proto3" json:"price_total,omitempty"`
	UserIds         []int64                `protobuf:"varint,8,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CarRental) Reset() {
	*x = CarRental{}
	mi := &file_itinerary_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarRental) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarRental) ProtoMessage() {}

func (x *CarRental) ProtoReflect() protoreflect.Message {
	mi := &file_itinerary_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarRental.ProtoReflect.Descriptor instead.
func (*CarRental) Descriptor() ([]byte, []int) {
	return file_itinerary_proto_rawDescGZIP(), []int{5}
}

func (x *CarRental) GetCompany() string {
	if x != nil {
		return x.Company
	}
	return ""
}

func (x *CarRental) GetPickupLocation() string {
	if x != nil {
		return x.PickupLocation
	}
	return ""
}

func (x *CarRental) GetDropoffLocation() string {
	if x != nil {
		return x.DropoffLocation
	}
	return ""
}

func (x *CarRental) GetPickupTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PickupTime
	}
	return nil
}

func (x *CarRental) GetDropoffTime() *timestamppb.Timestamp {
	if x != nil {
		return x.DropoffTime
	}
	return nil
}

func (x *CarRental) GetCarType() string {
	if x != nil {
		return x.CarType
	}
	return ""
}

func (x *CarRental) GetPriceTotal() string {
	if x != nil {
		return x.PriceTotal
	}
	return ""
}

func (x *CarRental) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_itinerary_proto protoreflect.FileDescriptor

const file_itinerary_proto_rawDesc = "" +
	"\n" +
	"\x0fitinerary.proto\x12\ftravelingman\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe5\x03\n" +
	"\tItinerary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"day_number\x18\x03 \x01(\x05R\tdayNumber\x129\n" +
	"\n" +
	"start_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12/\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1b.travelingman.ItineraryTypeR\x04type\x12\x14\n" +
	"\x05title\x18\a \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x125\n" +
	"\ttransport\x18\v \x03(\v2\x17.travelingman.TransportR\ttransport\x12A\n" +
	"\raccommodation\x18\f \x03(\v2\x1b.travelingman.AccommodationR\raccommodation\x129\n" +
	"\vitineraries\x18\r \x03(\v2\x17.travelingman.ItineraryR\vitineraries\"\xd9\x02\n" +
	"\rAccommodation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x125\n" +
	"\bcheck_in\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\acheckIn\x127\n" +
	"\tcheck_out\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bcheckOut\x12\x1f\n" +
	"\vprice_total\x18\a \x01(\tR\n" +
	"priceTotal\x12+\n" +
	"\x11booking_reference\x18\b \x01(\tR\x10bookingReference\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x19\n" +
	"\buser_ids\x18\n" +
	" \x03(\x03R\auserIds\"\xec\x02\n" +
	"\tTransport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\x03R\tbookingId\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12)\n" +
	"\x10reference_number\x18\x04 \x01(\tR\x0freferenceNumber\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12/\n" +
	"\x04type\x18\x06 \x01(\x0e2\x1b.travelingman.TransportTypeR\x04type\x12.\n" +
	"\x06flight\x18\n" +
	" \x01(\v2\x14.travelingman.FlightH\x00R\x06flight\x12+\n" +
	"\x05train\x18\v \x01(\v2\x13.travelingman.TrainH\x00R\x05train\x128\n" +
	"\n" +
	"car_rental\x18\f \x01(\v2\x17.travelingman.CarRentalH\x00R\tcarRentalB\t\n" +
	"\adetails\"\xc3\x02\n" +
	"\x06Flight\x12!\n" +
	"\fcarrier_code\x18\x01 \x01(\tR\vcarrierCode\x12#\n" +
	"\rflight_number\x18\x02 \x01(\tR\fflightNumber\x12+\n" +
	"\x11departure_airport\x18\x03 \x01(\tR\x10departureAirport\x12'\n" +
	"\x0farrival_airport\x18\x04 \x01(\tR\x0earrivalAirport\x12A\n" +
	"\x0edeparture_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12=\n" +
	"\farrival_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12\x19\n" +
	"\buser_ids\x18\a \x03(\x03R\auserIds\"\x9d\x02\n" +
	"\x05Train\x12+\n" +
	"\x11departure_station\x18\x01 \x01(\tR\x10departureStation\x12'\n" +
	"\x0farrival_station\x18\x02 \x01(\tR\x0earrivalStation\x12A\n" +
	"\x0edeparture_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\rdepartureTime\x12=\n" +
	"\farrival_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\varrivalTime\x12!\n" +
	"\ftrain_number\x18\x05 \x01(\tR\vtrainNumber\x12\x19\n" +
	"\buser_ids\x18\x06 \x03(\x03R\auserIds\"\xcc\x02\n" +
	"\tCarRental\x12\x18\n" +
	"\acompany\x18\x01 \x01(\tR\acompany\x12'\n" +
	"\x0fpickup_location\x18\x02 \x01(\tR\x0epickupLocation\x12)\n" +
	"\x10dropoff_location\x18\x03 \x01(\tR\x0fdropoffLocation\x12;\n" +
	"\vpickup_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"pickupTime\x12=\n" +
	"\fdropoff_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vdropoffTime\x12\x19\n" +
	"\bcar_type\x18\x06 \x01(\tR\acarType\x12\x1f\n" +
	"\vprice_total\x18\a \x01(\tR\n" +
	"priceTotal\x12\x19\n" +
	"\buser_ids\x18\b \x03(\x03R\auserIds*\x9e\x01\n" +
	"\rItineraryType\x12\x1e\n" +
	"\x1aITINERARY_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ITINERARY_TYPE_TRANSPORT\x10\x01\x12\x18\n" +
	"\x14ITINERARY_TYPE_HOTEL\x10\x02\x12\x18\n" +
	"\x14ITINERARY_TYPE_EVENT\x10\x03\x12\x1b\n" +
	"\x17ITINERARY_TYPE_DAY_PLAN\x10\x04*\x98\x01\n" +
	"\rTransportType\x12\x1e\n" +
	"\x1aTRANSPORT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15TRANSPORT_TYPE_FLIGHT\x10\x01\x12\x18\n" +
	"\x14TRANSPORT_TYPE_TRAIN\x10\x02\x12\x16\n" +
	"\x12TRANSPORT_TYPE_CAR\x10\x03\x12\x1a\n" +
	"\x16TRANSPORT_TYPE_WALKING\x10\x04B\x1dZ\x1bexample.com/travelingman/pbb\x06proto3"

var (
	file_itinerary_proto_rawDescOnce sync.Once
	file_itinerary_proto_rawDescData []byte
)

func file_itinerary_proto_rawDescGZIP() []byte {
	file_itinerary_proto_rawDescOnce.Do(func() {
		file_itinerary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_itinerary_proto_rawDesc), len(file_itinerary_proto_rawDesc)))
	})
	return file_itinerary_proto_rawDescData
}

var file_itinerary_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_itinerary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_itinerary_proto_goTypes = []any{
	(ItineraryType)(0),            // 0: travelingman.ItineraryType
	(TransportType)(0),            // 1: travelingman.TransportType
	(*Itinerary)(nil),             // 2: travelingman.Itinerary
	(*Accommodation)(nil),         // 3: travelingman.Accommodation
	(*Transport)(nil),             // 4: travelingman.Transport
	(*Flight)(nil),                // 5: travelingman.Flight
	(*Train)(nil),                 // 6: travelingman.Train
	(*CarRental)(nil),             // 7: travelingman.CarRental
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_itinerary_proto_depIdxs = []int32{
	8,  // 0: travelingman.Itinerary.start_time:type_name -> google.protobuf.Timestamp
	8,  // 1: travelingman.Itinerary.end_time:type_name -> google.protobuf.Timestamp
	0,  // 2: travelingman.Itinerary.type:type_name -> travelingman.ItineraryType
	4,  // 3: travelingman.Itinerary.transport:type_name -> travelingman.Transport
	3,  // 4: travelingman.Itinerary.accommodation:type_name -> travelingman.Accommodation
	2,  // 5: travelingman.Itinerary.itineraries:type_name -> travelingman.Itinerary
	8,  // 6: travelingman.Accommodation.check_in:type_name -> google.protobuf.Timestamp
	8,  // 7: travelingman.Accommodation.check_out:type_name -> google.protobuf.Timestamp
	1,  // 8: travelingman.Transport.type:type_name -> travelingman.TransportType
	5,  // 9: travelingman.Transport.flight:type_name -> travelingman.Flight
	6,  // 10: travelingman.Transport.train:type_name -> travelingman.Train
	7,  // 11: travelingman.Transport.car_rental:type_name -> travelingman.CarRental
	8,  // 12: travelingman.Flight.departure_time:type_name -> google.protobuf.Timestamp
	8,  // 13: travelingman.Flight.arrival_time:type_name -> google.protobuf.Timestamp
	8,  // 14: travelingman.Train.departure_time:type_name -> google.protobuf.Timestamp
	8,  // 15: travelingman.Train.arrival_time:type_name -> google.protobuf.Timestamp
	8,  // 16: travelingman.CarRental.pickup_time:type_name -> google.protobuf.Timestamp
	8,  // 17: travelingman.CarRental.dropoff_time:type_name -> google.protobuf.Timestamp
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_itinerary_proto_init() }
func file_itinerary_proto_init() {
	if File_itinerary_proto != nil {
		return
	}
	file_itinerary_proto_msgTypes[2].OneofWrappers = []any{
		(*Transport_Flight)(nil),
		(*Transport_Train)(nil),
		(*Transport_CarRental)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_itinerary_proto_rawDesc), len(file_itinerary_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_itinerary_proto_goTypes,
		DependencyIndexes: file_itinerary_proto_depIdxs,
		EnumInfos:         file_itinerary_proto_enumTypes,
		MessageInfos:      file_itinerary_proto_msgTypes,
	}.Build()
	File_itinerary_proto = out.File
	file_itinerary_proto_goTypes = nil
	file_itinerary_proto_depIdxs = nil
}
