// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: protos/users.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email           string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PasswordHash    string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	FullName        string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Passports       []*Passport            `protobuf:"bytes,6,rep,name=passports,proto3" json:"passports,omitempty"`
	DriversLicenses []*DriversLicense      `protobuf:"bytes,7,rep,name=drivers_licenses,json=driversLicenses,proto3" json:"drivers_licenses,omitempty"`
	DateOfBirth     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Gender          string                 `protobuf:"bytes,9,opt,name=gender,proto3" json:"gender,omitempty"` // MALE, FEMALE
	Phone           string                 `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protos_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protos_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetPassports() []*Passport {
	if x != nil {
		return x.Passports
	}
	return nil
}

func (x *User) GetDriversLicenses() []*DriversLicense {
	if x != nil {
		return x.DriversLicenses
	}
	return nil
}

func (x *User) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type Passport struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number           string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	IssuingCountry   string                 `protobuf:"bytes,4,opt,name=issuing_country,json=issuingCountry,proto3" json:"issuing_country,omitempty"`
	ExpiryDate       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	IssuanceDate     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=issuance_date,json=issuanceDate,proto3" json:"issuance_date,omitempty"`
	Nationality      string                 `protobuf:"bytes,7,opt,name=nationality,proto3" json:"nationality,omitempty"`
	BirthPlace       string                 `protobuf:"bytes,8,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	IssuanceLocation string                 `protobuf:"bytes,9,opt,name=issuance_location,json=issuanceLocation,proto3" json:"issuance_location,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Passport) Reset() {
	*x = Passport{}
	mi := &file_protos_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Passport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Passport) ProtoMessage() {}

func (x *Passport) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Passport.ProtoReflect.Descriptor instead.
func (*Passport) Descriptor() ([]byte, []int) {
	return file_protos_users_proto_rawDescGZIP(), []int{1}
}

func (x *Passport) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Passport) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Passport) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Passport) GetIssuingCountry() string {
	if x != nil {
		return x.IssuingCountry
	}
	return ""
}

func (x *Passport) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *Passport) GetIssuanceDate() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuanceDate
	}
	return nil
}

func (x *Passport) GetNationality() string {
	if x != nil {
		return x.Nationality
	}
	return ""
}

func (x *Passport) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *Passport) GetIssuanceLocation() string {
	if x != nil {
		return x.IssuanceLocation
	}
	return ""
}

type DriversLicense struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Number         string                 `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	IssuingCountry string                 `protobuf:"bytes,4,opt,name=issuing_country,json=issuingCountry,proto3" json:"issuing_country,omitempty"`
	ExpiryDate     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expiry_date,json=expiryDate,proto3" json:"expiry_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DriversLicense) Reset() {
	*x = DriversLicense{}
	mi := &file_protos_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriversLicense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriversLicense) ProtoMessage() {}

func (x *DriversLicense) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriversLicense.ProtoReflect.Descriptor instead.
func (*DriversLicense) Descriptor() ([]byte, []int) {
	return file_protos_users_proto_rawDescGZIP(), []int{2}
}

func (x *DriversLicense) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriversLicense) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DriversLicense) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *DriversLicense) GetIssuingCountry() string {
	if x != nil {
		return x.IssuingCountry
	}
	return ""
}

func (x *DriversLicense) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

type TravelGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       int64                  `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OrganizerId   int64                  `protobuf:"varint,3,opt,name=organizer_id,json=organizerId,proto3" json:"organizer_id,omitempty"`
	Destination   string                 `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	TravelDate    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=travel_date,json=travelDate,proto3" json:"travel_date,omitempty"`
	Members       []*User                `protobuf:"bytes,6,rep,name=members,proto3" json:"members,omitempty"`
	Itinerary     []*Itinerary           `protobuf:"bytes,7,rep,name=itinerary,proto3" json:"itinerary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TravelGroup) Reset() {
	*x = TravelGroup{}
	mi := &file_protos_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TravelGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TravelGroup) ProtoMessage() {}

func (x *TravelGroup) ProtoReflect() protoreflect.Message {
	mi := &file_protos_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TravelGroup.ProtoReflect.Descriptor instead.
func (*TravelGroup) Descriptor() ([]byte, []int) {
	return file_protos_users_proto_rawDescGZIP(), []int{3}
}

func (x *TravelGroup) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *TravelGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TravelGroup) GetOrganizerId() int64 {
	if x != nil {
		return x.OrganizerId
	}
	return 0
}

func (x *TravelGroup) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *TravelGroup) GetTravelDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TravelDate
	}
	return nil
}

func (x *TravelGroup) GetMembers() []*User {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *TravelGroup) GetItinerary() []*Itinerary {
	if x != nil {
		return x.Itinerary
	}
	return nil
}

var File_protos_users_proto protoreflect.FileDescriptor

const file_protos_users_proto_rawDesc = "" +
	"\n" +
	"\x12protos/users.proto\x12\ftravelingman\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x12protos/graph.proto\"\x96\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x124\n" +
	"\tpassports\x18\x06 \x03(\v2\x16.travelingman.PassportR\tpassports\x12G\n" +
	"\x10drivers_licenses\x18\a \x03(\v2\x1c.travelingman.DriversLicenseR\x0fdriversLicenses\x12>\n" +
	"\rdate_of_birth\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x16\n" +
	"\x06gender\x18\t \x01(\tR\x06gender\x12\x14\n" +
	"\x05phone\x18\n" +
	" \x01(\tR\x05phone\"\xe2\x02\n" +
	"\bPassport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12'\n" +
	"\x0fissuing_country\x18\x04 \x01(\tR\x0eissuingCountry\x12;\n" +
	"\vexpiry_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\x12?\n" +
	"\rissuance_date\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\fissuanceDate\x12 \n" +
	"\vnationality\x18\a \x01(\tR\vnationality\x12\x1f\n" +
	"\vbirth_place\x18\b \x01(\tR\n" +
	"birthPlace\x12+\n" +
	"\x11issuance_location\x18\t \x01(\tR\x10issuanceLocation\"\xb7\x01\n" +
	"\x0eDriversLicense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06number\x18\x03 \x01(\tR\x06number\x12'\n" +
	"\x0fissuing_country\x18\x04 \x01(\tR\x0eissuingCountry\x12;\n" +
	"\vexpiry_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"expiryDate\"\xa3\x02\n" +
	"\vTravelGroup\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\x03R\agroupId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\forganizer_id\x18\x03 \x01(\x03R\vorganizerId\x12 \n" +
	"\vdestination\x18\x04 \x01(\tR\vdestination\x12;\n" +
	"\vtravel_date\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"travelDate\x12,\n" +
	"\amembers\x18\x06 \x03(\v2\x12.travelingman.UserR\amembers\x125\n" +
	"\titinerary\x18\a \x03(\v2\x17.travelingman.ItineraryR\titineraryB#Z!github.com/va6996/travelingman/pbb\x06proto3"

var (
	file_protos_users_proto_rawDescOnce sync.Once
	file_protos_users_proto_rawDescData []byte
)

func file_protos_users_proto_rawDescGZIP() []byte {
	file_protos_users_proto_rawDescOnce.Do(func() {
		file_protos_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_users_proto_rawDesc), len(file_protos_users_proto_rawDesc)))
	})
	return file_protos_users_proto_rawDescData
}

var file_protos_users_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_users_proto_goTypes = []any{
	(*User)(nil),                  // 0: travelingman.User
	(*Passport)(nil),              // 1: travelingman.Passport
	(*DriversLicense)(nil),        // 2: travelingman.DriversLicense
	(*TravelGroup)(nil),           // 3: travelingman.TravelGroup
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*Itinerary)(nil),             // 5: travelingman.Itinerary
}
var file_protos_users_proto_depIdxs = []int32{
	4,  // 0: travelingman.User.created_at:type_name -> google.protobuf.Timestamp
	1,  // 1: travelingman.User.passports:type_name -> travelingman.Passport
	2,  // 2: travelingman.User.drivers_licenses:type_name -> travelingman.DriversLicense
	4,  // 3: travelingman.User.date_of_birth:type_name -> google.protobuf.Timestamp
	4,  // 4: travelingman.Passport.expiry_date:type_name -> google.protobuf.Timestamp
	4,  // 5: travelingman.Passport.issuance_date:type_name -> google.protobuf.Timestamp
	4,  // 6: travelingman.DriversLicense.expiry_date:type_name -> google.protobuf.Timestamp
	4,  // 7: travelingman.TravelGroup.travel_date:type_name -> google.protobuf.Timestamp
	0,  // 8: travelingman.TravelGroup.members:type_name -> travelingman.User
	5,  // 9: travelingman.TravelGroup.itinerary:type_name -> travelingman.Itinerary
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_protos_users_proto_init() }
func file_protos_users_proto_init() {
	if File_protos_users_proto != nil {
		return
	}
	file_protos_graph_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_users_proto_rawDesc), len(file_protos_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_users_proto_goTypes,
		DependencyIndexes: file_protos_users_proto_depIdxs,
		MessageInfos:      file_protos_users_proto_msgTypes,
	}.Build()
	File_protos_users_proto = out.File
	file_protos_users_proto_goTypes = nil
	file_protos_users_proto_depIdxs = nil
}
