// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bookings/flight": {
            "post": {
                "description": "Create a new flight booking",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bookings"
                ],
                "summary": "Book Flight",
                "parameters": [
                    {
                        "description": "Booking Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.BookFlightRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.BookFlightResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/itinerary/add": {
            "post": {
                "description": "Add an item (flight, hotel, etc.) to a group itinerary",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "itinerary"
                ],
                "summary": "Add Itinerary Item",
                "parameters": [
                    {
                        "description": "Item Details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.CreateItineraryItemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.ItineraryItem"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search/flights": {
            "post": {
                "description": "Search for flights using Amadeus API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search Flights",
                "parameters": [
                    {
                        "description": "Flight Search Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SearchFlightRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SearchFlightResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/search/hotels": {
            "post": {
                "description": "Search for hotels by city or specific offers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "search"
                ],
                "summary": "Search Hotels",
                "parameters": [
                    {
                        "description": "Hotel Search Parameters",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SearchHotelRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SearchHotelResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "service.BookFlightRequest": {
            "type": "object",
            "properties": {
                "flight_offer_json": {
                    "description": "JSON representation of the elected FlightOffer",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "travelers_json": {
                    "description": "JSON list of TravelerInfo",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "user_id": {
                    "type": "integer"
                }
            }
        },
        "service.BookFlightResponse": {
            "type": "object",
            "properties": {
                "raw_json": {
                    "description": "JSON response from Amadeus (booking confirmation)",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "service.CreateItineraryItemRequest": {
            "type": "object",
            "properties": {
                "details_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "end_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "group_id": {
                    "type": "integer"
                },
                "start_time": {
                    "description": "RFC3339",
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "service.ItineraryItem": {
            "type": "object",
            "properties": {
                "details_json": {
                    "description": "Flexible meta-data",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "end_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "group_id": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "start_time": {
                    "$ref": "#/definitions/timestamppb.Timestamp"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "description": "\"flight\", \"hotel\", \"activity\", \"note\"",
                    "type": "string"
                }
            }
        },
        "service.SearchFlightRequest": {
            "type": "object",
            "properties": {
                "adults": {
                    "type": "integer"
                },
                "departure_date": {
                    "type": "string"
                },
                "destination": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "return_date": {
                    "type": "string"
                }
            }
        },
        "service.SearchFlightResponse": {
            "type": "object",
            "properties": {
                "raw_json": {
                    "description": "Returning raw JSON for now to allow frontend to parse full Amadeus schema\nwithout rigid proto re-definition of every segment/fee/etc.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "service.SearchHotelRequest": {
            "type": "object",
            "properties": {
                "adults": {
                    "type": "integer"
                },
                "check_in_date": {
                    "type": "string"
                },
                "check_out_date": {
                    "type": "string"
                },
                "city_code": {
                    "type": "string"
                },
                "hotel_ids": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "service.SearchHotelResponse": {
            "type": "object",
            "properties": {
                "raw_json": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "timestamppb.Timestamp": {
            "type": "object",
            "properties": {
                "nanos": {
                    "description": "Non-negative fractions of a second at nanosecond resolution. This field is\nthe nanosecond portion of the duration, not an alternative to seconds.\nNegative second values with fractions must still have non-negative nanos\nvalues that count forward in time. Must be between 0 and 999,999,999\ninclusive.",
                    "type": "integer"
                },
                "seconds": {
                    "description": "Represents seconds of UTC time since Unix epoch 1970-01-01T00:00:00Z. Must\nbe between -315576000000 and 315576000000 inclusive (which corresponds to\n0001-01-01T00:00:00Z to 9999-12-31T23:59:59Z).",
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Travelingman API",
	Description:      "This is the API server for the Travelingman group travel application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
