// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: bookings.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "travelingman";

export enum BookingType {
  BOOKING_TYPE_UNSPECIFIED = 0,
  BOOKING_TYPE_FLIGHT = 1,
  BOOKING_TYPE_HOTEL = 2,
  BOOKING_TYPE_CAR = 3,
  BOOKING_TYPE_TRANSPORT = 4,
  UNRECOGNIZED = -1,
}

export function bookingTypeFromJSON(object: any): BookingType {
  switch (object) {
    case 0:
    case "BOOKING_TYPE_UNSPECIFIED":
      return BookingType.BOOKING_TYPE_UNSPECIFIED;
    case 1:
    case "BOOKING_TYPE_FLIGHT":
      return BookingType.BOOKING_TYPE_FLIGHT;
    case 2:
    case "BOOKING_TYPE_HOTEL":
      return BookingType.BOOKING_TYPE_HOTEL;
    case 3:
    case "BOOKING_TYPE_CAR":
      return BookingType.BOOKING_TYPE_CAR;
    case 4:
    case "BOOKING_TYPE_TRANSPORT":
      return BookingType.BOOKING_TYPE_TRANSPORT;
    case -1:
    case "UNRECOGNIZED":
    default:
      return BookingType.UNRECOGNIZED;
  }
}

export function bookingTypeToJSON(object: BookingType): string {
  switch (object) {
    case BookingType.BOOKING_TYPE_UNSPECIFIED:
      return "BOOKING_TYPE_UNSPECIFIED";
    case BookingType.BOOKING_TYPE_FLIGHT:
      return "BOOKING_TYPE_FLIGHT";
    case BookingType.BOOKING_TYPE_HOTEL:
      return "BOOKING_TYPE_HOTEL";
    case BookingType.BOOKING_TYPE_CAR:
      return "BOOKING_TYPE_CAR";
    case BookingType.BOOKING_TYPE_TRANSPORT:
      return "BOOKING_TYPE_TRANSPORT";
    case BookingType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum Provider {
  PROVIDER_UNSPECIFIED = 0,
  PROVIDER_AMADEUS = 1,
  PROVIDER_BOOKING_COM = 2,
  PROVIDER_MANUAL = 3,
  PROVIDER_OTHER = 4,
  UNRECOGNIZED = -1,
}

export function providerFromJSON(object: any): Provider {
  switch (object) {
    case 0:
    case "PROVIDER_UNSPECIFIED":
      return Provider.PROVIDER_UNSPECIFIED;
    case 1:
    case "PROVIDER_AMADEUS":
      return Provider.PROVIDER_AMADEUS;
    case 2:
    case "PROVIDER_BOOKING_COM":
      return Provider.PROVIDER_BOOKING_COM;
    case 3:
    case "PROVIDER_MANUAL":
      return Provider.PROVIDER_MANUAL;
    case 4:
    case "PROVIDER_OTHER":
      return Provider.PROVIDER_OTHER;
    case -1:
    case "UNRECOGNIZED":
    default:
      return Provider.UNRECOGNIZED;
  }
}

export function providerToJSON(object: Provider): string {
  switch (object) {
    case Provider.PROVIDER_UNSPECIFIED:
      return "PROVIDER_UNSPECIFIED";
    case Provider.PROVIDER_AMADEUS:
      return "PROVIDER_AMADEUS";
    case Provider.PROVIDER_BOOKING_COM:
      return "PROVIDER_BOOKING_COM";
    case Provider.PROVIDER_MANUAL:
      return "PROVIDER_MANUAL";
    case Provider.PROVIDER_OTHER:
      return "PROVIDER_OTHER";
    case Provider.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface FlightOffer {
  id: number;
  groupId: number;
  amadeusOfferId: string;
  carrierCode: string;
  flightNumber: string;
  departureAirport: string;
  arrivalAirport: string;
  departureTime: Date | undefined;
  arrivalTime: Date | undefined;
  priceTotal: string;
  currency: string;
  rawData: string;
}

export interface HotelOffer {
  id: number;
  groupId: number;
  hotelName: string;
  checkIn: Date | undefined;
  checkOut: Date | undefined;
  priceTotal: string;
  currency: string;
  offerId: string;
}

export interface Booking {
  id: number;
  userId: number;
  type: BookingType;
  provider: Provider;
  status: string;
  externalBookingReference: string;
  createdAt: Date | undefined;
}

export interface Payment {
  id: number;
  bookingId: number;
  userId: number;
  amount: string;
  currency: string;
  status: string;
  transactionId: string;
  createdAt: Date | undefined;
}

function createBaseFlightOffer(): FlightOffer {
  return {
    id: 0,
    groupId: 0,
    amadeusOfferId: "",
    carrierCode: "",
    flightNumber: "",
    departureAirport: "",
    arrivalAirport: "",
    departureTime: undefined,
    arrivalTime: undefined,
    priceTotal: "",
    currency: "",
    rawData: "",
  };
}

export const FlightOffer: MessageFns<FlightOffer> = {
  encode(message: FlightOffer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.amadeusOfferId !== "") {
      writer.uint32(26).string(message.amadeusOfferId);
    }
    if (message.carrierCode !== "") {
      writer.uint32(34).string(message.carrierCode);
    }
    if (message.flightNumber !== "") {
      writer.uint32(42).string(message.flightNumber);
    }
    if (message.departureAirport !== "") {
      writer.uint32(50).string(message.departureAirport);
    }
    if (message.arrivalAirport !== "") {
      writer.uint32(58).string(message.arrivalAirport);
    }
    if (message.departureTime !== undefined) {
      Timestamp.encode(toTimestamp(message.departureTime), writer.uint32(66).fork()).join();
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(74).fork()).join();
    }
    if (message.priceTotal !== "") {
      writer.uint32(82).string(message.priceTotal);
    }
    if (message.currency !== "") {
      writer.uint32(90).string(message.currency);
    }
    if (message.rawData !== "") {
      writer.uint32(98).string(message.rawData);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FlightOffer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlightOffer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.amadeusOfferId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.carrierCode = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.flightNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.departureAirport = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.arrivalAirport = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.departureTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.priceTotal = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.rawData = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FlightOffer {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      amadeusOfferId: isSet(object.amadeusOfferId) ? globalThis.String(object.amadeusOfferId) : "",
      carrierCode: isSet(object.carrierCode) ? globalThis.String(object.carrierCode) : "",
      flightNumber: isSet(object.flightNumber) ? globalThis.String(object.flightNumber) : "",
      departureAirport: isSet(object.departureAirport) ? globalThis.String(object.departureAirport) : "",
      arrivalAirport: isSet(object.arrivalAirport) ? globalThis.String(object.arrivalAirport) : "",
      departureTime: isSet(object.departureTime) ? fromJsonTimestamp(object.departureTime) : undefined,
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
      priceTotal: isSet(object.priceTotal) ? globalThis.String(object.priceTotal) : "",
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      rawData: isSet(object.rawData) ? globalThis.String(object.rawData) : "",
    };
  },

  toJSON(message: FlightOffer): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.amadeusOfferId !== "") {
      obj.amadeusOfferId = message.amadeusOfferId;
    }
    if (message.carrierCode !== "") {
      obj.carrierCode = message.carrierCode;
    }
    if (message.flightNumber !== "") {
      obj.flightNumber = message.flightNumber;
    }
    if (message.departureAirport !== "") {
      obj.departureAirport = message.departureAirport;
    }
    if (message.arrivalAirport !== "") {
      obj.arrivalAirport = message.arrivalAirport;
    }
    if (message.departureTime !== undefined) {
      obj.departureTime = message.departureTime.toISOString();
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    if (message.priceTotal !== "") {
      obj.priceTotal = message.priceTotal;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.rawData !== "") {
      obj.rawData = message.rawData;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FlightOffer>, I>>(base?: I): FlightOffer {
    return FlightOffer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FlightOffer>, I>>(object: I): FlightOffer {
    const message = createBaseFlightOffer();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.amadeusOfferId = object.amadeusOfferId ?? "";
    message.carrierCode = object.carrierCode ?? "";
    message.flightNumber = object.flightNumber ?? "";
    message.departureAirport = object.departureAirport ?? "";
    message.arrivalAirport = object.arrivalAirport ?? "";
    message.departureTime = object.departureTime ?? undefined;
    message.arrivalTime = object.arrivalTime ?? undefined;
    message.priceTotal = object.priceTotal ?? "";
    message.currency = object.currency ?? "";
    message.rawData = object.rawData ?? "";
    return message;
  },
};

function createBaseHotelOffer(): HotelOffer {
  return {
    id: 0,
    groupId: 0,
    hotelName: "",
    checkIn: undefined,
    checkOut: undefined,
    priceTotal: "",
    currency: "",
    offerId: "",
  };
}

export const HotelOffer: MessageFns<HotelOffer> = {
  encode(message: HotelOffer, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.hotelName !== "") {
      writer.uint32(26).string(message.hotelName);
    }
    if (message.checkIn !== undefined) {
      Timestamp.encode(toTimestamp(message.checkIn), writer.uint32(34).fork()).join();
    }
    if (message.checkOut !== undefined) {
      Timestamp.encode(toTimestamp(message.checkOut), writer.uint32(42).fork()).join();
    }
    if (message.priceTotal !== "") {
      writer.uint32(50).string(message.priceTotal);
    }
    if (message.currency !== "") {
      writer.uint32(58).string(message.currency);
    }
    if (message.offerId !== "") {
      writer.uint32(66).string(message.offerId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HotelOffer {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHotelOffer();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.hotelName = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.checkIn = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.checkOut = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.priceTotal = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.offerId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HotelOffer {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      hotelName: isSet(object.hotelName) ? globalThis.String(object.hotelName) : "",
      checkIn: isSet(object.checkIn) ? fromJsonTimestamp(object.checkIn) : undefined,
      checkOut: isSet(object.checkOut) ? fromJsonTimestamp(object.checkOut) : undefined,
      priceTotal: isSet(object.priceTotal) ? globalThis.String(object.priceTotal) : "",
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      offerId: isSet(object.offerId) ? globalThis.String(object.offerId) : "",
    };
  },

  toJSON(message: HotelOffer): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.hotelName !== "") {
      obj.hotelName = message.hotelName;
    }
    if (message.checkIn !== undefined) {
      obj.checkIn = message.checkIn.toISOString();
    }
    if (message.checkOut !== undefined) {
      obj.checkOut = message.checkOut.toISOString();
    }
    if (message.priceTotal !== "") {
      obj.priceTotal = message.priceTotal;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.offerId !== "") {
      obj.offerId = message.offerId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HotelOffer>, I>>(base?: I): HotelOffer {
    return HotelOffer.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HotelOffer>, I>>(object: I): HotelOffer {
    const message = createBaseHotelOffer();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.hotelName = object.hotelName ?? "";
    message.checkIn = object.checkIn ?? undefined;
    message.checkOut = object.checkOut ?? undefined;
    message.priceTotal = object.priceTotal ?? "";
    message.currency = object.currency ?? "";
    message.offerId = object.offerId ?? "";
    return message;
  },
};

function createBaseBooking(): Booking {
  return { id: 0, userId: 0, type: 0, provider: 0, status: "", externalBookingReference: "", createdAt: undefined };
}

export const Booking: MessageFns<Booking> = {
  encode(message: Booking, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.userId !== 0) {
      writer.uint32(16).int64(message.userId);
    }
    if (message.type !== 0) {
      writer.uint32(24).int32(message.type);
    }
    if (message.provider !== 0) {
      writer.uint32(32).int32(message.provider);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.externalBookingReference !== "") {
      writer.uint32(50).string(message.externalBookingReference);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Booking {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseBooking();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.provider = reader.int32() as any;
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.externalBookingReference = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Booking {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      type: isSet(object.type) ? bookingTypeFromJSON(object.type) : 0,
      provider: isSet(object.provider) ? providerFromJSON(object.provider) : 0,
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      externalBookingReference: isSet(object.externalBookingReference)
        ? globalThis.String(object.externalBookingReference)
        : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: Booking): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.type !== 0) {
      obj.type = bookingTypeToJSON(message.type);
    }
    if (message.provider !== 0) {
      obj.provider = providerToJSON(message.provider);
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.externalBookingReference !== "") {
      obj.externalBookingReference = message.externalBookingReference;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Booking>, I>>(base?: I): Booking {
    return Booking.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Booking>, I>>(object: I): Booking {
    const message = createBaseBooking();
    message.id = object.id ?? 0;
    message.userId = object.userId ?? 0;
    message.type = object.type ?? 0;
    message.provider = object.provider ?? 0;
    message.status = object.status ?? "";
    message.externalBookingReference = object.externalBookingReference ?? "";
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

function createBasePayment(): Payment {
  return {
    id: 0,
    bookingId: 0,
    userId: 0,
    amount: "",
    currency: "",
    status: "",
    transactionId: "",
    createdAt: undefined,
  };
}

export const Payment: MessageFns<Payment> = {
  encode(message: Payment, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.bookingId !== 0) {
      writer.uint32(16).int64(message.bookingId);
    }
    if (message.userId !== 0) {
      writer.uint32(24).int64(message.userId);
    }
    if (message.amount !== "") {
      writer.uint32(34).string(message.amount);
    }
    if (message.currency !== "") {
      writer.uint32(42).string(message.currency);
    }
    if (message.status !== "") {
      writer.uint32(50).string(message.status);
    }
    if (message.transactionId !== "") {
      writer.uint32(58).string(message.transactionId);
    }
    if (message.createdAt !== undefined) {
      Timestamp.encode(toTimestamp(message.createdAt), writer.uint32(66).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Payment {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePayment();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookingId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.userId = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.amount = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.currency = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.transactionId = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.createdAt = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Payment {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      bookingId: isSet(object.bookingId) ? globalThis.Number(object.bookingId) : 0,
      userId: isSet(object.userId) ? globalThis.Number(object.userId) : 0,
      amount: isSet(object.amount) ? globalThis.String(object.amount) : "",
      currency: isSet(object.currency) ? globalThis.String(object.currency) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      transactionId: isSet(object.transactionId) ? globalThis.String(object.transactionId) : "",
      createdAt: isSet(object.createdAt) ? fromJsonTimestamp(object.createdAt) : undefined,
    };
  },

  toJSON(message: Payment): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.bookingId !== 0) {
      obj.bookingId = Math.round(message.bookingId);
    }
    if (message.userId !== 0) {
      obj.userId = Math.round(message.userId);
    }
    if (message.amount !== "") {
      obj.amount = message.amount;
    }
    if (message.currency !== "") {
      obj.currency = message.currency;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.transactionId !== "") {
      obj.transactionId = message.transactionId;
    }
    if (message.createdAt !== undefined) {
      obj.createdAt = message.createdAt.toISOString();
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Payment>, I>>(base?: I): Payment {
    return Payment.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Payment>, I>>(object: I): Payment {
    const message = createBasePayment();
    message.id = object.id ?? 0;
    message.bookingId = object.bookingId ?? 0;
    message.userId = object.userId ?? 0;
    message.amount = object.amount ?? "";
    message.currency = object.currency ?? "";
    message.status = object.status ?? "";
    message.transactionId = object.transactionId ?? "";
    message.createdAt = object.createdAt ?? undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
