// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.0
//   protoc               v5.29.2
// source: itinerary.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Timestamp } from "./google/protobuf/timestamp";

export const protobufPackage = "travelingman";

export enum ItineraryType {
  ITINERARY_TYPE_UNSPECIFIED = 0,
  ITINERARY_TYPE_TRANSPORT = 1,
  ITINERARY_TYPE_HOTEL = 2,
  ITINERARY_TYPE_EVENT = 3,
  ITINERARY_TYPE_DAY_PLAN = 4,
  UNRECOGNIZED = -1,
}

export function itineraryTypeFromJSON(object: any): ItineraryType {
  switch (object) {
    case 0:
    case "ITINERARY_TYPE_UNSPECIFIED":
      return ItineraryType.ITINERARY_TYPE_UNSPECIFIED;
    case 1:
    case "ITINERARY_TYPE_TRANSPORT":
      return ItineraryType.ITINERARY_TYPE_TRANSPORT;
    case 2:
    case "ITINERARY_TYPE_HOTEL":
      return ItineraryType.ITINERARY_TYPE_HOTEL;
    case 3:
    case "ITINERARY_TYPE_EVENT":
      return ItineraryType.ITINERARY_TYPE_EVENT;
    case 4:
    case "ITINERARY_TYPE_DAY_PLAN":
      return ItineraryType.ITINERARY_TYPE_DAY_PLAN;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ItineraryType.UNRECOGNIZED;
  }
}

export function itineraryTypeToJSON(object: ItineraryType): string {
  switch (object) {
    case ItineraryType.ITINERARY_TYPE_UNSPECIFIED:
      return "ITINERARY_TYPE_UNSPECIFIED";
    case ItineraryType.ITINERARY_TYPE_TRANSPORT:
      return "ITINERARY_TYPE_TRANSPORT";
    case ItineraryType.ITINERARY_TYPE_HOTEL:
      return "ITINERARY_TYPE_HOTEL";
    case ItineraryType.ITINERARY_TYPE_EVENT:
      return "ITINERARY_TYPE_EVENT";
    case ItineraryType.ITINERARY_TYPE_DAY_PLAN:
      return "ITINERARY_TYPE_DAY_PLAN";
    case ItineraryType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export enum TransportType {
  TRANSPORT_TYPE_UNSPECIFIED = 0,
  TRANSPORT_TYPE_FLIGHT = 1,
  TRANSPORT_TYPE_TRAIN = 2,
  TRANSPORT_TYPE_CAR = 3,
  TRANSPORT_TYPE_WALKING = 4,
  UNRECOGNIZED = -1,
}

export function transportTypeFromJSON(object: any): TransportType {
  switch (object) {
    case 0:
    case "TRANSPORT_TYPE_UNSPECIFIED":
      return TransportType.TRANSPORT_TYPE_UNSPECIFIED;
    case 1:
    case "TRANSPORT_TYPE_FLIGHT":
      return TransportType.TRANSPORT_TYPE_FLIGHT;
    case 2:
    case "TRANSPORT_TYPE_TRAIN":
      return TransportType.TRANSPORT_TYPE_TRAIN;
    case 3:
    case "TRANSPORT_TYPE_CAR":
      return TransportType.TRANSPORT_TYPE_CAR;
    case 4:
    case "TRANSPORT_TYPE_WALKING":
      return TransportType.TRANSPORT_TYPE_WALKING;
    case -1:
    case "UNRECOGNIZED":
    default:
      return TransportType.UNRECOGNIZED;
  }
}

export function transportTypeToJSON(object: TransportType): string {
  switch (object) {
    case TransportType.TRANSPORT_TYPE_UNSPECIFIED:
      return "TRANSPORT_TYPE_UNSPECIFIED";
    case TransportType.TRANSPORT_TYPE_FLIGHT:
      return "TRANSPORT_TYPE_FLIGHT";
    case TransportType.TRANSPORT_TYPE_TRAIN:
      return "TRANSPORT_TYPE_TRAIN";
    case TransportType.TRANSPORT_TYPE_CAR:
      return "TRANSPORT_TYPE_CAR";
    case TransportType.TRANSPORT_TYPE_WALKING:
      return "TRANSPORT_TYPE_WALKING";
    case TransportType.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface Itinerary {
  id: number;
  groupId: number;
  dayNumber: number;
  startTime: Date | undefined;
  endTime: Date | undefined;
  type: ItineraryType;
  title: string;
  description: string;
  transport: Transport[];
  accommodation: Accommodation[];
  itineraries: Itinerary[];
}

export interface Accommodation {
  id: number;
  groupId: number;
  name: string;
  address: string;
  checkIn: Date | undefined;
  checkOut: Date | undefined;
  priceTotal: string;
  bookingReference: string;
  status: string;
  userIds: number[];
}

export interface Transport {
  id: number;
  bookingId: number;
  provider: string;
  referenceNumber: string;
  status: string;
  type: TransportType;
  flight?: Flight | undefined;
  train?: Train | undefined;
  carRental?: CarRental | undefined;
}

export interface Flight {
  carrierCode: string;
  flightNumber: string;
  departureAirport: string;
  arrivalAirport: string;
  departureTime: Date | undefined;
  arrivalTime: Date | undefined;
  userIds: number[];
}

export interface Train {
  departureStation: string;
  arrivalStation: string;
  departureTime: Date | undefined;
  arrivalTime: Date | undefined;
  trainNumber: string;
  userIds: number[];
}

export interface CarRental {
  company: string;
  pickupLocation: string;
  dropoffLocation: string;
  pickupTime: Date | undefined;
  dropoffTime: Date | undefined;
  carType: string;
  priceTotal: string;
  userIds: number[];
}

function createBaseItinerary(): Itinerary {
  return {
    id: 0,
    groupId: 0,
    dayNumber: 0,
    startTime: undefined,
    endTime: undefined,
    type: 0,
    title: "",
    description: "",
    transport: [],
    accommodation: [],
    itineraries: [],
  };
}

export const Itinerary: MessageFns<Itinerary> = {
  encode(message: Itinerary, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.dayNumber !== 0) {
      writer.uint32(24).int32(message.dayNumber);
    }
    if (message.startTime !== undefined) {
      Timestamp.encode(toTimestamp(message.startTime), writer.uint32(34).fork()).join();
    }
    if (message.endTime !== undefined) {
      Timestamp.encode(toTimestamp(message.endTime), writer.uint32(42).fork()).join();
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.title !== "") {
      writer.uint32(58).string(message.title);
    }
    if (message.description !== "") {
      writer.uint32(66).string(message.description);
    }
    for (const v of message.transport) {
      Transport.encode(v!, writer.uint32(90).fork()).join();
    }
    for (const v of message.accommodation) {
      Accommodation.encode(v!, writer.uint32(98).fork()).join();
    }
    for (const v of message.itineraries) {
      Itinerary.encode(v!, writer.uint32(106).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Itinerary {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseItinerary();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.dayNumber = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.startTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.endTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.description = reader.string();
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.transport.push(Transport.decode(reader, reader.uint32()));
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.accommodation.push(Accommodation.decode(reader, reader.uint32()));
          continue;
        }
        case 13: {
          if (tag !== 106) {
            break;
          }

          message.itineraries.push(Itinerary.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Itinerary {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      dayNumber: isSet(object.dayNumber) ? globalThis.Number(object.dayNumber) : 0,
      startTime: isSet(object.startTime) ? fromJsonTimestamp(object.startTime) : undefined,
      endTime: isSet(object.endTime) ? fromJsonTimestamp(object.endTime) : undefined,
      type: isSet(object.type) ? itineraryTypeFromJSON(object.type) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      description: isSet(object.description) ? globalThis.String(object.description) : "",
      transport: globalThis.Array.isArray(object?.transport)
        ? object.transport.map((e: any) => Transport.fromJSON(e))
        : [],
      accommodation: globalThis.Array.isArray(object?.accommodation)
        ? object.accommodation.map((e: any) => Accommodation.fromJSON(e))
        : [],
      itineraries: globalThis.Array.isArray(object?.itineraries)
        ? object.itineraries.map((e: any) => Itinerary.fromJSON(e))
        : [],
    };
  },

  toJSON(message: Itinerary): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.dayNumber !== 0) {
      obj.dayNumber = Math.round(message.dayNumber);
    }
    if (message.startTime !== undefined) {
      obj.startTime = message.startTime.toISOString();
    }
    if (message.endTime !== undefined) {
      obj.endTime = message.endTime.toISOString();
    }
    if (message.type !== 0) {
      obj.type = itineraryTypeToJSON(message.type);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.description !== "") {
      obj.description = message.description;
    }
    if (message.transport?.length) {
      obj.transport = message.transport.map((e) => Transport.toJSON(e));
    }
    if (message.accommodation?.length) {
      obj.accommodation = message.accommodation.map((e) => Accommodation.toJSON(e));
    }
    if (message.itineraries?.length) {
      obj.itineraries = message.itineraries.map((e) => Itinerary.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Itinerary>, I>>(base?: I): Itinerary {
    return Itinerary.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Itinerary>, I>>(object: I): Itinerary {
    const message = createBaseItinerary();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.dayNumber = object.dayNumber ?? 0;
    message.startTime = object.startTime ?? undefined;
    message.endTime = object.endTime ?? undefined;
    message.type = object.type ?? 0;
    message.title = object.title ?? "";
    message.description = object.description ?? "";
    message.transport = object.transport?.map((e) => Transport.fromPartial(e)) || [];
    message.accommodation = object.accommodation?.map((e) => Accommodation.fromPartial(e)) || [];
    message.itineraries = object.itineraries?.map((e) => Itinerary.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAccommodation(): Accommodation {
  return {
    id: 0,
    groupId: 0,
    name: "",
    address: "",
    checkIn: undefined,
    checkOut: undefined,
    priceTotal: "",
    bookingReference: "",
    status: "",
    userIds: [],
  };
}

export const Accommodation: MessageFns<Accommodation> = {
  encode(message: Accommodation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.groupId !== 0) {
      writer.uint32(16).int64(message.groupId);
    }
    if (message.name !== "") {
      writer.uint32(26).string(message.name);
    }
    if (message.address !== "") {
      writer.uint32(34).string(message.address);
    }
    if (message.checkIn !== undefined) {
      Timestamp.encode(toTimestamp(message.checkIn), writer.uint32(42).fork()).join();
    }
    if (message.checkOut !== undefined) {
      Timestamp.encode(toTimestamp(message.checkOut), writer.uint32(50).fork()).join();
    }
    if (message.priceTotal !== "") {
      writer.uint32(58).string(message.priceTotal);
    }
    if (message.bookingReference !== "") {
      writer.uint32(66).string(message.bookingReference);
    }
    if (message.status !== "") {
      writer.uint32(74).string(message.status);
    }
    writer.uint32(82).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Accommodation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAccommodation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.groupId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.address = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.checkIn = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.checkOut = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.priceTotal = reader.string();
          continue;
        }
        case 8: {
          if (tag !== 66) {
            break;
          }

          message.bookingReference = reader.string();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 10: {
          if (tag === 80) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 82) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Accommodation {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      groupId: isSet(object.groupId) ? globalThis.Number(object.groupId) : 0,
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      address: isSet(object.address) ? globalThis.String(object.address) : "",
      checkIn: isSet(object.checkIn) ? fromJsonTimestamp(object.checkIn) : undefined,
      checkOut: isSet(object.checkOut) ? fromJsonTimestamp(object.checkOut) : undefined,
      priceTotal: isSet(object.priceTotal) ? globalThis.String(object.priceTotal) : "",
      bookingReference: isSet(object.bookingReference) ? globalThis.String(object.bookingReference) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: Accommodation): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.groupId !== 0) {
      obj.groupId = Math.round(message.groupId);
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.address !== "") {
      obj.address = message.address;
    }
    if (message.checkIn !== undefined) {
      obj.checkIn = message.checkIn.toISOString();
    }
    if (message.checkOut !== undefined) {
      obj.checkOut = message.checkOut.toISOString();
    }
    if (message.priceTotal !== "") {
      obj.priceTotal = message.priceTotal;
    }
    if (message.bookingReference !== "") {
      obj.bookingReference = message.bookingReference;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Accommodation>, I>>(base?: I): Accommodation {
    return Accommodation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Accommodation>, I>>(object: I): Accommodation {
    const message = createBaseAccommodation();
    message.id = object.id ?? 0;
    message.groupId = object.groupId ?? 0;
    message.name = object.name ?? "";
    message.address = object.address ?? "";
    message.checkIn = object.checkIn ?? undefined;
    message.checkOut = object.checkOut ?? undefined;
    message.priceTotal = object.priceTotal ?? "";
    message.bookingReference = object.bookingReference ?? "";
    message.status = object.status ?? "";
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseTransport(): Transport {
  return {
    id: 0,
    bookingId: 0,
    provider: "",
    referenceNumber: "",
    status: "",
    type: 0,
    flight: undefined,
    train: undefined,
    carRental: undefined,
  };
}

export const Transport: MessageFns<Transport> = {
  encode(message: Transport, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int64(message.id);
    }
    if (message.bookingId !== 0) {
      writer.uint32(16).int64(message.bookingId);
    }
    if (message.provider !== "") {
      writer.uint32(26).string(message.provider);
    }
    if (message.referenceNumber !== "") {
      writer.uint32(34).string(message.referenceNumber);
    }
    if (message.status !== "") {
      writer.uint32(42).string(message.status);
    }
    if (message.type !== 0) {
      writer.uint32(48).int32(message.type);
    }
    if (message.flight !== undefined) {
      Flight.encode(message.flight, writer.uint32(82).fork()).join();
    }
    if (message.train !== undefined) {
      Train.encode(message.train, writer.uint32(90).fork()).join();
    }
    if (message.carRental !== undefined) {
      CarRental.encode(message.carRental, writer.uint32(98).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Transport {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTransport();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = longToNumber(reader.int64());
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.bookingId = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.provider = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.referenceNumber = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.type = reader.int32() as any;
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.flight = Flight.decode(reader, reader.uint32());
          continue;
        }
        case 11: {
          if (tag !== 90) {
            break;
          }

          message.train = Train.decode(reader, reader.uint32());
          continue;
        }
        case 12: {
          if (tag !== 98) {
            break;
          }

          message.carRental = CarRental.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Transport {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      bookingId: isSet(object.bookingId) ? globalThis.Number(object.bookingId) : 0,
      provider: isSet(object.provider) ? globalThis.String(object.provider) : "",
      referenceNumber: isSet(object.referenceNumber) ? globalThis.String(object.referenceNumber) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      type: isSet(object.type) ? transportTypeFromJSON(object.type) : 0,
      flight: isSet(object.flight) ? Flight.fromJSON(object.flight) : undefined,
      train: isSet(object.train) ? Train.fromJSON(object.train) : undefined,
      carRental: isSet(object.carRental) ? CarRental.fromJSON(object.carRental) : undefined,
    };
  },

  toJSON(message: Transport): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.bookingId !== 0) {
      obj.bookingId = Math.round(message.bookingId);
    }
    if (message.provider !== "") {
      obj.provider = message.provider;
    }
    if (message.referenceNumber !== "") {
      obj.referenceNumber = message.referenceNumber;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.type !== 0) {
      obj.type = transportTypeToJSON(message.type);
    }
    if (message.flight !== undefined) {
      obj.flight = Flight.toJSON(message.flight);
    }
    if (message.train !== undefined) {
      obj.train = Train.toJSON(message.train);
    }
    if (message.carRental !== undefined) {
      obj.carRental = CarRental.toJSON(message.carRental);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Transport>, I>>(base?: I): Transport {
    return Transport.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Transport>, I>>(object: I): Transport {
    const message = createBaseTransport();
    message.id = object.id ?? 0;
    message.bookingId = object.bookingId ?? 0;
    message.provider = object.provider ?? "";
    message.referenceNumber = object.referenceNumber ?? "";
    message.status = object.status ?? "";
    message.type = object.type ?? 0;
    message.flight = (object.flight !== undefined && object.flight !== null)
      ? Flight.fromPartial(object.flight)
      : undefined;
    message.train = (object.train !== undefined && object.train !== null) ? Train.fromPartial(object.train) : undefined;
    message.carRental = (object.carRental !== undefined && object.carRental !== null)
      ? CarRental.fromPartial(object.carRental)
      : undefined;
    return message;
  },
};

function createBaseFlight(): Flight {
  return {
    carrierCode: "",
    flightNumber: "",
    departureAirport: "",
    arrivalAirport: "",
    departureTime: undefined,
    arrivalTime: undefined,
    userIds: [],
  };
}

export const Flight: MessageFns<Flight> = {
  encode(message: Flight, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.carrierCode !== "") {
      writer.uint32(10).string(message.carrierCode);
    }
    if (message.flightNumber !== "") {
      writer.uint32(18).string(message.flightNumber);
    }
    if (message.departureAirport !== "") {
      writer.uint32(26).string(message.departureAirport);
    }
    if (message.arrivalAirport !== "") {
      writer.uint32(34).string(message.arrivalAirport);
    }
    if (message.departureTime !== undefined) {
      Timestamp.encode(toTimestamp(message.departureTime), writer.uint32(42).fork()).join();
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(50).fork()).join();
    }
    writer.uint32(58).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Flight {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFlight();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.carrierCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.flightNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.departureAirport = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arrivalAirport = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.departureTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag === 56) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 58) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Flight {
    return {
      carrierCode: isSet(object.carrierCode) ? globalThis.String(object.carrierCode) : "",
      flightNumber: isSet(object.flightNumber) ? globalThis.String(object.flightNumber) : "",
      departureAirport: isSet(object.departureAirport) ? globalThis.String(object.departureAirport) : "",
      arrivalAirport: isSet(object.arrivalAirport) ? globalThis.String(object.arrivalAirport) : "",
      departureTime: isSet(object.departureTime) ? fromJsonTimestamp(object.departureTime) : undefined,
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: Flight): unknown {
    const obj: any = {};
    if (message.carrierCode !== "") {
      obj.carrierCode = message.carrierCode;
    }
    if (message.flightNumber !== "") {
      obj.flightNumber = message.flightNumber;
    }
    if (message.departureAirport !== "") {
      obj.departureAirport = message.departureAirport;
    }
    if (message.arrivalAirport !== "") {
      obj.arrivalAirport = message.arrivalAirport;
    }
    if (message.departureTime !== undefined) {
      obj.departureTime = message.departureTime.toISOString();
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Flight>, I>>(base?: I): Flight {
    return Flight.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Flight>, I>>(object: I): Flight {
    const message = createBaseFlight();
    message.carrierCode = object.carrierCode ?? "";
    message.flightNumber = object.flightNumber ?? "";
    message.departureAirport = object.departureAirport ?? "";
    message.arrivalAirport = object.arrivalAirport ?? "";
    message.departureTime = object.departureTime ?? undefined;
    message.arrivalTime = object.arrivalTime ?? undefined;
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseTrain(): Train {
  return {
    departureStation: "",
    arrivalStation: "",
    departureTime: undefined,
    arrivalTime: undefined,
    trainNumber: "",
    userIds: [],
  };
}

export const Train: MessageFns<Train> = {
  encode(message: Train, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.departureStation !== "") {
      writer.uint32(10).string(message.departureStation);
    }
    if (message.arrivalStation !== "") {
      writer.uint32(18).string(message.arrivalStation);
    }
    if (message.departureTime !== undefined) {
      Timestamp.encode(toTimestamp(message.departureTime), writer.uint32(26).fork()).join();
    }
    if (message.arrivalTime !== undefined) {
      Timestamp.encode(toTimestamp(message.arrivalTime), writer.uint32(34).fork()).join();
    }
    if (message.trainNumber !== "") {
      writer.uint32(42).string(message.trainNumber);
    }
    writer.uint32(50).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Train {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTrain();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.departureStation = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.arrivalStation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.departureTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.arrivalTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.trainNumber = reader.string();
          continue;
        }
        case 6: {
          if (tag === 48) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 50) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Train {
    return {
      departureStation: isSet(object.departureStation) ? globalThis.String(object.departureStation) : "",
      arrivalStation: isSet(object.arrivalStation) ? globalThis.String(object.arrivalStation) : "",
      departureTime: isSet(object.departureTime) ? fromJsonTimestamp(object.departureTime) : undefined,
      arrivalTime: isSet(object.arrivalTime) ? fromJsonTimestamp(object.arrivalTime) : undefined,
      trainNumber: isSet(object.trainNumber) ? globalThis.String(object.trainNumber) : "",
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: Train): unknown {
    const obj: any = {};
    if (message.departureStation !== "") {
      obj.departureStation = message.departureStation;
    }
    if (message.arrivalStation !== "") {
      obj.arrivalStation = message.arrivalStation;
    }
    if (message.departureTime !== undefined) {
      obj.departureTime = message.departureTime.toISOString();
    }
    if (message.arrivalTime !== undefined) {
      obj.arrivalTime = message.arrivalTime.toISOString();
    }
    if (message.trainNumber !== "") {
      obj.trainNumber = message.trainNumber;
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Train>, I>>(base?: I): Train {
    return Train.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Train>, I>>(object: I): Train {
    const message = createBaseTrain();
    message.departureStation = object.departureStation ?? "";
    message.arrivalStation = object.arrivalStation ?? "";
    message.departureTime = object.departureTime ?? undefined;
    message.arrivalTime = object.arrivalTime ?? undefined;
    message.trainNumber = object.trainNumber ?? "";
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseCarRental(): CarRental {
  return {
    company: "",
    pickupLocation: "",
    dropoffLocation: "",
    pickupTime: undefined,
    dropoffTime: undefined,
    carType: "",
    priceTotal: "",
    userIds: [],
  };
}

export const CarRental: MessageFns<CarRental> = {
  encode(message: CarRental, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.company !== "") {
      writer.uint32(10).string(message.company);
    }
    if (message.pickupLocation !== "") {
      writer.uint32(18).string(message.pickupLocation);
    }
    if (message.dropoffLocation !== "") {
      writer.uint32(26).string(message.dropoffLocation);
    }
    if (message.pickupTime !== undefined) {
      Timestamp.encode(toTimestamp(message.pickupTime), writer.uint32(34).fork()).join();
    }
    if (message.dropoffTime !== undefined) {
      Timestamp.encode(toTimestamp(message.dropoffTime), writer.uint32(42).fork()).join();
    }
    if (message.carType !== "") {
      writer.uint32(50).string(message.carType);
    }
    if (message.priceTotal !== "") {
      writer.uint32(58).string(message.priceTotal);
    }
    writer.uint32(66).fork();
    for (const v of message.userIds) {
      writer.int64(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CarRental {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCarRental();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.company = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pickupLocation = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.dropoffLocation = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.pickupTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.dropoffTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.carType = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.priceTotal = reader.string();
          continue;
        }
        case 8: {
          if (tag === 64) {
            message.userIds.push(longToNumber(reader.int64()));

            continue;
          }

          if (tag === 66) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.userIds.push(longToNumber(reader.int64()));
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CarRental {
    return {
      company: isSet(object.company) ? globalThis.String(object.company) : "",
      pickupLocation: isSet(object.pickupLocation) ? globalThis.String(object.pickupLocation) : "",
      dropoffLocation: isSet(object.dropoffLocation) ? globalThis.String(object.dropoffLocation) : "",
      pickupTime: isSet(object.pickupTime) ? fromJsonTimestamp(object.pickupTime) : undefined,
      dropoffTime: isSet(object.dropoffTime) ? fromJsonTimestamp(object.dropoffTime) : undefined,
      carType: isSet(object.carType) ? globalThis.String(object.carType) : "",
      priceTotal: isSet(object.priceTotal) ? globalThis.String(object.priceTotal) : "",
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.Number(e)) : [],
    };
  },

  toJSON(message: CarRental): unknown {
    const obj: any = {};
    if (message.company !== "") {
      obj.company = message.company;
    }
    if (message.pickupLocation !== "") {
      obj.pickupLocation = message.pickupLocation;
    }
    if (message.dropoffLocation !== "") {
      obj.dropoffLocation = message.dropoffLocation;
    }
    if (message.pickupTime !== undefined) {
      obj.pickupTime = message.pickupTime.toISOString();
    }
    if (message.dropoffTime !== undefined) {
      obj.dropoffTime = message.dropoffTime.toISOString();
    }
    if (message.carType !== "") {
      obj.carType = message.carType;
    }
    if (message.priceTotal !== "") {
      obj.priceTotal = message.priceTotal;
    }
    if (message.userIds?.length) {
      obj.userIds = message.userIds.map((e) => Math.round(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CarRental>, I>>(base?: I): CarRental {
    return CarRental.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CarRental>, I>>(object: I): CarRental {
    const message = createBaseCarRental();
    message.company = object.company ?? "";
    message.pickupLocation = object.pickupLocation ?? "";
    message.dropoffLocation = object.dropoffLocation ?? "";
    message.pickupTime = object.pickupTime ?? undefined;
    message.dropoffTime = object.dropoffTime ?? undefined;
    message.carType = object.carType ?? "";
    message.priceTotal = object.priceTotal ?? "";
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(date: Date): Timestamp {
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): Date {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis);
}

function fromJsonTimestamp(o: any): Date {
  if (o instanceof globalThis.Date) {
    return o;
  } else if (typeof o === "string") {
    return new globalThis.Date(o);
  } else {
    return fromTimestamp(Timestamp.fromJSON(o));
  }
}

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
